//! The Analytics UI's demo data (analytics TODO A1.18): a small, deterministic
//! set of tables for trying it — what `feldspar demo analytics [--replace]`
//! makes, and what the milestones' definition-of-done tests run over. Here
//! rather than in the CLI so that a server test can make the same rows; each
//! later milestone adds its tables here (districts and incidents in A5).
//!
//! `neighbourhoods`, `houses` and `viewings` (A1), shaped as the models
//! tutorial (`docs/tutorial-models.md`) has them — so its datasets, models and
//! `predict("House prices")` work over the demo as they do over rows typed by
//! hand — plus the columns the Analytics UI's tutorial reaches for: a year
//! built, and a date for each viewing.
//!
//! `patients` and `measurements` (A2): a blood pressure measured before and
//! after a treatment, for the paired tests, with a treatment that works — a
//! little for the low dose, more for the high one, hardly at all for the
//! placebo. And `events` (A2): a million requests to a web site, generated by
//! one `INSERT … SELECT` over a recursive CTE so that it takes a second or two
//! rather than a million round trips, for a histogram of a large table and a
//! scatter plot that has to sample. The CTE is the same text on Postgres and
//! SQLite: integer arithmetic only (a quadratic hash of the row number, so
//! two columns of it show no lattice when plotted against each other), and a
//! division by `10.0` that both backends round to the same double.
//!
//! **Datasets too.** The Data explorer reads datasets, not tables, so the demo
//! also makes three: `Houses`, `Measurements` (with each patient's treatment
//! and the change in pressure) and `Events`. A dataset of that name that is
//! already there is kept as it is — it may be the admin's own — and the
//! report says so.
//!
//! **Synthetic and deterministic.** Every row comes from a fixed-seed
//! generator, so two runs make the same rows and a tutorial can say what a
//! filter leaves. A price is a linear function of area, bedrooms, the
//! neighbourhood's income and age, plus noise, so a regression over it finds
//! something; about one house in seven is unsold, with no price, for a model
//! to predict.
//!
//! **Nothing is touched without `--replace`.** A database that already has one
//! of the demo's tables is refused, naming it: they are ordinary tables, and
//! one of them may be the admin's own. With `--replace`, they are dropped and
//! made again; datasets are never dropped.

use chrono::{Duration, NaiveDate};
use sc_catalog::{Catalog, DataField, DataFieldKind, FieldId, TableId};
use sc_dataset::{DatasetDef, Op, Operation};
use sc_db::ColumnGenerator;
use sc_error::{Context, Error, Result};
use sc_query::{Expr, Insert, Statement, Value};
use sc_types::{BasicType, TypeRef};

/// The tables the demo makes, in the order they are made (a key's target
/// first).
pub const DEMO_TABLES: [&str; 6] = [
    "neighbourhoods",
    "houses",
    "viewings",
    "patients",
    "measurements",
    "events",
];

/// The datasets the demo makes, each on the table of the same name.
pub const DEMO_DATASETS: [&str; 3] = ["Houses", "Measurements", "Events"];

/// How many houses the demo makes.
pub const DEMO_HOUSES: usize = 200;

/// How many patients the demo makes, a third on each treatment, each measured
/// once before and once after.
pub const DEMO_PATIENTS: usize = 90;

/// How many events the demo makes.
pub const DEMO_EVENTS: usize = 1_000_000;

/// What a run made.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DemoReport {
    /// Each table and how many rows it has.
    pub tables: Vec<(String, usize)>,
    /// The tables that were there and were dropped first.
    pub replaced: Vec<String>,
    /// The datasets made.
    pub datasets: Vec<String>,
    /// The datasets that were there already and were left as they are.
    pub kept: Vec<String>,
}

/// A fixed-seed generator: the same sequence on every run and every machine.
struct Rng(u64);

impl Rng {
    /// The next number in `[0, 1)`: a 64-bit LCG (Knuth's MMIX constants),
    /// its top 53 bits.
    fn next(&mut self) -> f64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        (self.0 >> 11) as f64 / (1u64 << 53) as f64
    }

    /// An integer in `lo..=hi`.
    fn int(&mut self, lo: i64, hi: i64) -> i64 {
        lo + (self.next() * (hi - lo + 1) as f64).floor() as i64
    }

    /// A standard normal, by Box–Muller.
    fn normal(&mut self) -> f64 {
        let u = self.next().max(1e-12);
        let v = self.next();
        (-2.0 * u.ln()).sqrt() * (2.0 * std::f64::consts::PI * v).cos()
    }
}

const NEIGHBOURHOODS: [(&str, f64); 5] = [
    ("Riverside", 62_000.0),
    ("Old Town", 48_000.0),
    ("Northgate", 35_000.0),
    ("Harbour", 55_000.0),
    ("Hillcrest", 71_000.0),
];

/// Each treatment and how far it lowers the pressure on average, in mmHg.
const TREATMENTS: [(&str, f64); 3] = [("placebo", 1.0), ("low dose", 6.0), ("high dose", 11.0)];

const STREETS: [&str; 8] = [
    "Mill Lane",
    "Station Road",
    "Church Street",
    "Elm Grove",
    "Harbour View",
    "Queen's Walk",
    "Orchard Close",
    "Market Street",
];

fn text() -> TypeRef {
    TypeRef::Basic(BasicType::Text)
}

fn id() -> DataField {
    DataField::plain("id", TypeRef::Basic(BasicType::Int))
        .required()
        .primary_key()
        .generated(ColumnGenerator::Identity)
}

fn key(name: &str, table: &str) -> DataField {
    let mut field = DataField::plain(name, TypeRef::Basic(BasicType::Int));
    field.kind = DataFieldKind::Key {
        target_table: TableId(table.to_owned()),
        target_field: FieldId("id".to_owned()),
        summary_field: None,
    };
    field
}

/// Make the demo's tables in `catalog`, refusing to touch any that are there
/// unless `replace`.
pub async fn demo_analytics(catalog: &Catalog, replace: bool) -> Result<DemoReport> {
    let present: Vec<String> = DEMO_TABLES
        .iter()
        .filter(|t| catalog.get(t).ok().flatten().is_some())
        .map(|t| (*t).to_owned())
        .collect();
    if !present.is_empty() && !replace {
        return Err(Error::invalid(format!(
            "the database already has {}; the demo will not touch a table that is there — \
             run it with `--replace` to drop and remake the demo's tables",
            present
                .iter()
                .map(|t| format!("`{t}`"))
                .collect::<Vec<_>>()
                .join(", ")
        )));
    }
    // Keys point the other way, so the tables go in reverse.
    for table in DEMO_TABLES.iter().rev() {
        if present.iter().any(|p| p == table) {
            catalog
                .drop_table(table)
                .await
                .with_context(|| format!("dropping `{table}`"))?;
        }
    }

    catalog
        .create_table(
            "neighbourhoods",
            &[
                id(),
                DataField::plain("name", text()).required(),
                DataField::plain("average_income", TypeRef::Basic(BasicType::Float)),
            ],
        )
        .await?;
    catalog
        .create_table(
            "houses",
            &[
                id(),
                DataField::plain("address", text()),
                DataField::plain("area", TypeRef::Basic(BasicType::Float)),
                DataField::plain("bedrooms", TypeRef::Basic(BasicType::Int)),
                key("neighbourhood", "neighbourhoods"),
                DataField::plain("year_built", TypeRef::Basic(BasicType::Int)),
                DataField::plain("sold", TypeRef::Basic(BasicType::Bool)),
                DataField::plain("price", TypeRef::Basic(BasicType::Float)),
            ],
        )
        .await?;
    catalog
        .create_table(
            "viewings",
            &[
                id(),
                key("house", "houses"),
                DataField::plain("viewed_on", TypeRef::Basic(BasicType::Date)),
                DataField::plain("attended", TypeRef::Basic(BasicType::Bool)),
            ],
        )
        .await?;
    catalog
        .create_table(
            "patients",
            &[
                id(),
                DataField::plain("code", text()).required(),
                DataField::plain("sex", text()),
                DataField::plain("age", TypeRef::Basic(BasicType::Int)),
                DataField::plain("treatment", text()),
            ],
        )
        .await?;
    catalog
        .create_table(
            "measurements",
            &[
                id(),
                key("patient", "patients"),
                DataField::plain("measured_on", TypeRef::Basic(BasicType::Date)),
                DataField::plain("before", TypeRef::Basic(BasicType::Float)),
                DataField::plain("after", TypeRef::Basic(BasicType::Float)),
            ],
        )
        .await?;
    catalog
        .create_table(
            "events",
            &[
                id(),
                DataField::plain("kind", text()),
                DataField::plain("duration_ms", TypeRef::Basic(BasicType::Float)),
                DataField::plain("size_kb", TypeRef::Basic(BasicType::Float)),
                DataField::plain("hour", TypeRef::Basic(BasicType::Int)),
            ],
        )
        .await?;

    let mut rng = Rng(20_260_929);
    let hoods: Vec<Vec<Value>> = NEIGHBOURHOODS
        .iter()
        .map(|(name, income)| vec![Value::Text((*name).to_owned()), Value::Float(*income)])
        .collect();
    insert(
        catalog,
        "neighbourhoods",
        &["name", "average_income"],
        hoods,
    )
    .await?;

    let mut houses = Vec::with_capacity(DEMO_HOUSES);
    let mut viewings = Vec::new();
    let start = NaiveDate::from_ymd_opt(2024, 1, 1).unwrap_or_default();
    for n in 0..DEMO_HOUSES {
        let hood = rng.int(0, NEIGHBOURHOODS.len() as i64 - 1) as usize;
        let area = (40.0 + rng.next() * 140.0).round();
        let bedrooms = ((area / 35.0).floor() as i64 + rng.int(-1, 1)).clamp(1, 6);
        let year = rng.int(1950, 2022);
        let sold = rng.next() < 0.86;
        let noise = rng.normal() * 18_000.0;
        let price = 1_800.0 * area
            + 12_000.0 * bedrooms as f64
            + 1.2 * NEIGHBOURHOODS[hood].1
            + 700.0 * (year - 1950) as f64
            + noise;
        let price = (price / 1_000.0).round() * 1_000.0;
        houses.push(vec![
            Value::Text(format!(
                "{} {}",
                rng.int(1, 180),
                STREETS[rng.int(0, STREETS.len() as i64 - 1) as usize]
            )),
            Value::Float(area),
            Value::Int(bedrooms),
            Value::Int(hood as i64 + 1),
            Value::Int(year),
            Value::Bool(sold),
            if sold {
                Value::Float(price)
            } else {
                Value::Null
            },
        ]);
        for _ in 0..rng.int(0, 5) {
            viewings.push(vec![
                Value::Int(n as i64 + 1),
                Value::Date(start + Duration::days(rng.int(0, 364))),
                Value::Bool(rng.next() < 0.8),
            ]);
        }
    }
    insert(
        catalog,
        "houses",
        &[
            "address",
            "area",
            "bedrooms",
            "neighbourhood",
            "year_built",
            "sold",
            "price",
        ],
        houses,
    )
    .await?;
    let viewing_count = viewings.len();
    insert(
        catalog,
        "viewings",
        &["house", "viewed_on", "attended"],
        viewings,
    )
    .await?;
    patients(catalog).await?;
    events(catalog).await?;
    catalog.reload().await?;
    let (datasets, kept) = datasets(catalog).await?;

    Ok(DemoReport {
        tables: vec![
            ("neighbourhoods".to_owned(), NEIGHBOURHOODS.len()),
            ("houses".to_owned(), DEMO_HOUSES),
            ("viewings".to_owned(), viewing_count),
            ("patients".to_owned(), DEMO_PATIENTS),
            ("measurements".to_owned(), DEMO_PATIENTS),
            ("events".to_owned(), DEMO_EVENTS),
        ],
        replaced: present,
        datasets,
        kept,
    })
}

/// The patients, a third on each treatment in turn, and one measurement of
/// each: a systolic pressure in whole mmHg, a little higher with age, before
/// the treatment and some weeks after.
async fn patients(catalog: &Catalog) -> Result<()> {
    // A generator of its own, so that the houses are the rows they were
    // before the patients came.
    let mut rng = Rng(20_261_002);
    let start = NaiveDate::from_ymd_opt(2025, 3, 3).unwrap_or_default();
    let mut patients = Vec::with_capacity(DEMO_PATIENTS);
    let mut measurements = Vec::with_capacity(DEMO_PATIENTS);
    for n in 0..DEMO_PATIENTS {
        let (treatment, effect) = TREATMENTS[n % TREATMENTS.len()];
        let age = rng.int(28, 79);
        let sex = if rng.next() < 0.5 { "F" } else { "M" };
        let before = (146.0 + 0.3 * (age - 50) as f64 + 13.0 * rng.normal()).round();
        let after = (before - effect + 7.0 * rng.normal()).round();
        patients.push(vec![
            Value::Text(format!("P{:03}", n + 1)),
            Value::Text(sex.to_owned()),
            Value::Int(age),
            Value::Text(treatment.to_owned()),
        ]);
        measurements.push(vec![
            Value::Int(n as i64 + 1),
            Value::Date(start + Duration::days(rng.int(0, 120))),
            Value::Float(before),
            Value::Float(after),
        ]);
    }
    insert(
        catalog,
        "patients",
        &["code", "sex", "age", "treatment"],
        patients,
    )
    .await?;
    insert(
        catalog,
        "measurements",
        &["patient", "measured_on", "before", "after"],
        measurements,
    )
    .await
}

/// A million events, in one statement the database runs on its own.
///
/// Row `i`'s numbers come from quadratic hashes of `i` modulo the prime
/// 2³¹ − 1 — every product under 2⁶², so no backend overflows — and are
/// integers until the last step. A kind (55% pages, 30% API calls, 15%
/// assets); a duration, the square of a sum of four uniforms, so skewed to the
/// right, and longest for pages; a size growing with the duration, steeply for
/// assets; and an hour of the day, most often around noon.
///
/// Each hash is computed from `i` alone, and `u` is `MATERIALIZED` (both
/// backends know the word): a database inlines a CTE that is read once, and a
/// chain of hashes each squaring the one before, inlined, is an expression
/// that doubles at every step — 18 seconds rather than 3 on Postgres.
async fn events(catalog: &Catalog) -> Result<()> {
    let hash = |p: u64, q: u64| {
        format!("((i * {p}) % 2147483647 * ((i * {q}) % 2147483647) + i) % 2147483647")
    };
    let sql = format!(
        "WITH RECURSIVE s(i) AS (
           SELECT CAST(1 AS bigint) UNION ALL SELECT i + 1 FROM s WHERE i < {DEMO_EVENTS}
         ),
         h AS (
           SELECT i, {b} AS b, {c} AS c, {d} AS d, {e} AS e, {f} AS f FROM s
         ),
         u AS MATERIALIZED (
           SELECT i, c % 100 AS k, b % 1000 + d % 1000 + e % 1000 + f % 1000 AS t,
                  d % 2000 AS jitter, (b % 24 + c % 24 + 1) / 2 AS hour
           FROM h
         ),
         w AS (
           SELECT i, k, jitter, hour,
                  CASE WHEN k < 55 THEN 300 + t * t / 2500
                       WHEN k < 85 THEN 100 + t * t / 5000
                       ELSE 50 + t * t / 10000 END AS dur
           FROM u
         )
         INSERT INTO events (kind, duration_ms, size_kb, hour)
         SELECT CASE WHEN k < 55 THEN 'page' WHEN k < 85 THEN 'api' ELSE 'asset' END,
                dur / 10.0,
                (dur * CASE WHEN k < 55 THEN 2 WHEN k < 85 THEN 1 ELSE 6 END + jitter) / 10.0,
                hour
         FROM w",
        b = hash(48_271, 16_807),
        c = hash(69_621, 39_373),
        d = hash(40_692, 40_014),
        e = hash(950_706_376, 742_938_285),
        f = hash(1_583_458_089, 784_588_716),
    );
    catalog
        .primary()
        .query(&Statement::raw(sql, Vec::new()))
        .await?
        .try_collect()
        .await
        .context("generating the demo's events")?;
    Ok(())
}

/// The demo's datasets, each made unless one of its name is there.
async fn datasets(catalog: &Catalog) -> Result<(Vec<String>, Vec<String>)> {
    sc_dataset::bootstrap_datasets(catalog).await?;
    let mut measurements = DatasetDef::over_table("Measurements", "measurements");
    measurements.description =
        "One blood pressure measurement per patient, before and after a treatment.".to_owned();
    measurements.operations = vec![
        Operation::new(
            "treatment",
            Op::calculated("treatment", "patientⱵtreatment"),
        ),
        Operation::new("change", Op::calculated("change", "after - before")),
    ];
    let mut houses = DatasetDef::over_table("Houses", "houses");
    houses.description = "Every house of the demo, sold or not.".to_owned();
    let mut events = DatasetDef::over_table("Events", "events");
    events.description = "A million requests to a web site.".to_owned();

    let (mut made, mut kept) = (Vec::new(), Vec::new());
    for def in [houses, measurements, events] {
        if sc_dataset::load_dataset_by_name(catalog, &def.name)
            .await?
            .is_some()
        {
            kept.push(def.name);
        } else {
            sc_dataset::save_dataset(catalog, &def)
                .await
                .with_context(|| format!("making the dataset `{}`", def.name))?;
            made.push(def.name);
        }
    }
    Ok((made, kept))
}

/// Insert `rows` into `table`, a hundred at a time.
async fn insert(
    catalog: &Catalog,
    table: &str,
    columns: &[&str],
    rows: Vec<Vec<Value>>,
) -> Result<()> {
    for chunk in rows.chunks(100) {
        let insert = Insert {
            table: table.to_owned(),
            columns: columns.iter().map(|c| (*c).to_owned()).collect(),
            rows: chunk
                .iter()
                .map(|r| r.iter().cloned().map(Expr::Lit).collect())
                .collect(),
            returning: Vec::new(),
        };
        catalog
            .primary()
            .query(&Statement::from(insert))
            .await?
            .try_collect()
            .await
            .with_context(|| format!("writing the demo's rows into `{table}`"))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generator_is_the_same_on_every_run() {
        let mut a = Rng(7);
        let mut b = Rng(7);
        let xs: Vec<f64> = (0..5).map(|_| a.next()).collect();
        let ys: Vec<f64> = (0..5).map(|_| b.next()).collect();
        assert_eq!(xs, ys);
        assert!(xs.iter().all(|x| (0.0..1.0).contains(x)));
    }
}
