//! Milestone 31's definition of done, walked end to end through the assembled
//! router: models without actions of their own.
//!
//! - The models tutorial's `houses`, with the `House prices` linear regression
//!   over a dataset holding `neighbourhoodⱵaverage_income` and
//!   `viewingsↃhouse.length`, filtered to the sold houses.
//! - A non-stored calculated field `estimated_price = predict("House prices")`:
//!   listing `houses` answers a number in every row, the unsold house
//!   included, for **one** provider call; filtering on it is refused naming it.
//! - A nightly `fit_model` with `activate: if_clean`: the new fit becomes
//!   active and the next read follows it with nothing edited, while a stub
//!   provider that warns leaves its new fit inactive.
//! - Radon, over the stub posterior provider (no CmdStan): a workflow runs
//!   `fit_model`, then a `run_js_code` step writes the posterior back through
//!   `models.get("Radon")`, filling `counties.alpha_mean` and firing the
//!   `counties` update trigger. The same body learns that a posterior does not
//!   predict (pointing at `m.draws`) and that a regression's handle has no
//!   `draws`. The Python body does the same through `m.write_posterior` (with
//!   `--features python`; without it, the sentence naming the rebuild).
//! - `listActions` has `fit_model` and neither `predict_row` nor
//!   `write_posterior`.
//!
//! The Radon half against a real CmdStan is `stan_models.rs`'s `#[ignore]`d
//! `radon_is_refitted_by_a_workflow_and_written_back_from_code`.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;
use std::time::Duration;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers, start_workflow_engine,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

use crate::fit_model_action::{WARNING, Warns};
use crate::model_formulas::count_calls;
use crate::posterior_api::{Sampler, bound, nulls_dropped, radon};

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// The models tutorial's three tables, and Radon's three.
///
/// Sixty sold houses whose price is an exact linear function of the dataset's
/// four features — area, bedrooms, the neighbourhood's income (a join) and the
/// number of viewings (an aggregation) — so the regression recovers it and a
/// prediction can be checked to the unit. House 500 is not sold, so the
/// dataset's filter excludes it.
const SCHEMA: &str = "
    CREATE TABLE neighbourhoods (id bigint primary key, name text,
                                 average_income double precision);
    CREATE TABLE houses (
        id bigint primary key,
        area double precision,
        bedrooms bigint,
        neighbourhood bigint references neighbourhoods(id),
        sold boolean not null default true,
        price double precision
    );
    CREATE TABLE viewings (id bigint generated by default as identity primary key,
                           house bigint references houses(id), attended boolean);
    INSERT INTO neighbourhoods VALUES
        (1, 'Northgate', 40000), (2, 'Old Town', 60000), (3, 'Riverside', 90000);
    INSERT INTO houses (id, area, bedrooms, neighbourhood)
      SELECT i, 50 + i, 1 + (i % 5), 1 + (i % 3) FROM generate_series(1, 60) AS i;
    INSERT INTO houses (id, area, bedrooms, neighbourhood, sold)
      VALUES (500, 100, 3, 2, false);
    INSERT INTO viewings (house, attended)
      SELECT i, true FROM generate_series(1, 60) AS i, generate_series(1, 3) AS k
      WHERE k <= i % 4;
    INSERT INTO viewings (house, attended) VALUES (500, true), (500, false);
    UPDATE houses h SET price =
        1000 * h.area + 20000 * h.bedrooms
        + 0.5 * (SELECT average_income FROM neighbourhoods n WHERE n.id = h.neighbourhood)
        + 3000 * (SELECT count(*) FROM viewings v WHERE v.house = h.id)
      WHERE sold;

    CREATE TABLE counties (
        id bigint primary key, name text, log_uranium double precision,
        alpha_mean double precision, alpha_sd double precision
    );
    CREATE TABLE homes (
        id bigint primary key, county bigint references counties(id),
        floor double precision, y double precision
    );
    CREATE TABLE audit (id bigint generated by default as identity primary key, what text);
    CREATE TABLE refits (id bigint generated by default as identity primary key, note text);
    INSERT INTO counties (id, name, log_uranium) VALUES
        (27001, 'Aitkin', -0.7), (27003, 'Anoka', -0.8), (27005, 'Becker', 0.3);
    INSERT INTO homes VALUES
        (1, 27001, 0, 0.8), (2, 27001, 1, 1.2), (3, 27003, 0, 1.9),
        (4, 27003, null, 2.1), (5, 27005, 1, 2.8), (6, 27005, 0, 3.3);
";

/// What the schema's price formula gives house 500: 100 m², three bedrooms,
/// Old Town and two viewings.
const HOUSE_500: f64 = 1000.0 * 100.0 + 20000.0 * 3.0 + 0.5 * 60000.0 + 3000.0 * 2.0;

/// The workflow's code step: write the new fit's posterior back, and ask two
/// handles for what they do not have.
const WRITE_BACK_JS: &str = r#"
const m = await models.get("Radon");
const w = await m.writePosterior({
    variable: "alpha", statistics: { mean: "alpha_mean", sd: "alpha_sd" } });
const said = {};
try { await m.predict({ id: 1 }); } catch (e) { said.predict = e.message; }
const h = await models.get("House prices");
try { await h.draws("alpha"); } catch (e) { said.draws = e.message; }
return { written: w.written, table: w.table, fit: m.fit.id, refit: context.refit,
         hasDraws: Object.keys(h).includes("draws"), said };
"#;

/// The same, in Python.
const WRITE_BACK_PY: &str = r#"
m = models.get("Radon")
w = m.write_posterior(variable="alpha", statistics={"mean": "alpha_mean", "sd": "alpha_sd"})
try:
    m.predict({"id": 1})
    predicted = None
except Exception as e:
    predicted = str(e)
h = models.get("House prices")
try:
    h.draws
    draws = None
except AttributeError as e:
    draws = str(e)
return {"written": w["written"], "predicted": predicted, "draws": draws,
        "has_draws": hasattr(h, "draws")}
"#;

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 4 * 1024 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes)
                .unwrap_or_else(|_| Value::String(String::from_utf8_lossy(&bytes).into_owned()))
        };
        (status, value)
    }

    async fn ok(&mut self, method: &str, path: &str, body: Option<Value>) -> Value {
        let (status, value) = self.send(method, path, body).await;
        assert!(status.is_success(), "{method} {path}: {status} {value}");
        value
    }

    async fn refused(&mut self, method: &str, path: &str, body: Option<Value>) -> String {
        let (status, value) = self.send(method, path, body).await;
        assert!(
            status.is_client_error(),
            "{method} {path} should be refused: {status} {value}"
        );
        value.to_string()
    }

    /// Save a model of the sold houses fitted by `provider`, answering its id.
    async fn house_model(&mut self, name: &str, provider: &str) -> String {
        let saved = self
            .ok(
                "POST",
                "/api/models",
                Some(json!({
                    "name": name,
                    "description": "what a house is worth",
                    "provider": provider,
                    "dataset": {
                        "table": "houses",
                        "columns": [
                            { "name": "price", "expr": "price" },
                            { "name": "area", "expr": "area" },
                            { "name": "bedrooms", "expr": "bedrooms" },
                            { "name": "neighbourhood_income",
                              "expr": "neighbourhoodⱵaverage_income" },
                            { "name": "viewings_count", "expr": "viewingsↃhouse.length" },
                        ],
                        "filter": "sold === true",
                    },
                    "configuration": { "label": "price" },
                    "hyperparameters": {},
                    "split": { "train": 0.8, "validation": 0.0, "test": 0.2, "seed": 7 },
                    "attributes": {},
                })),
            )
            .await;
        saved["id"].as_str().unwrap().to_owned()
    }

    /// Fit model `id` from the Models screen and press Activate, answering the
    /// fit's id.
    async fn fit_and_activate(&mut self, id: &str) -> String {
        let started = self
            .ok("POST", &format!("/api/models/{id}/fit"), Some(json!({})))
            .await;
        let instance = started["id"].as_str().unwrap().to_owned();
        for _ in 0..800 {
            let body = self
                .ok("GET", &format!("/api/model-instances/{instance}"), None)
                .await;
            if body["status"] != json!("fitting") {
                assert_eq!(body["status"], json!("fitted"), "{body}");
                self.ok(
                    "POST",
                    &format!("/api/model-instances/{instance}/activate"),
                    None,
                )
                .await;
                return instance;
            }
            tokio::time::sleep(Duration::from_millis(25)).await;
        }
        panic!("the fit of {id} never finished");
    }

    /// Model `id`'s fits, by fit id, answering whether each is active.
    async fn active_fits(&mut self, id: &str) -> Vec<(String, bool)> {
        let fits = self
            .ok("GET", &format!("/api/models/{id}/instances"), None)
            .await;
        fits.as_array()
            .unwrap()
            .iter()
            .map(|f| {
                (
                    f["id"].as_str().unwrap().to_owned(),
                    f["active"].as_bool().unwrap(),
                )
            })
            .collect()
    }

    async fn trigger(&mut self, body: Value) -> String {
        let created = self.ok("POST", "/api/triggers", Some(body)).await;
        created["id"].as_str().unwrap().to_owned()
    }

    /// Press Run on a trigger, answering what its action returned.
    async fn run(&mut self, trigger: &str) -> Value {
        self.ok(
            "POST",
            &format!("/api/triggers/{trigger}/run"),
            Some(json!({})),
        )
        .await["result"]
            .clone()
    }

    async fn rows(&mut self, path: &str) -> Vec<Value> {
        self.ok("GET", path, None)
            .await
            .as_array()
            .cloned()
            .unwrap_or_default()
    }

    /// House `id`'s `estimated_price`, as a listing answers it.
    async fn estimated_price(&mut self, id: i64) -> f64 {
        self.rows("/api/tables/houses/rows")
            .await
            .iter()
            .find(|r| r["id"] == json!(id))
            .and_then(|r| r["estimated_price"].as_f64())
            .unwrap_or_else(|| panic!("house {id} has no estimated_price"))
    }
}

fn close(value: f64, expected: f64) -> bool {
    (value - expected).abs() < 1.0
}

async fn setup() -> Result<(
    Client,
    Arc<Catalog>,
    TestDb,
    Arc<sc_workflow::WorkflowEngineTask>,
)> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    sc_catalog::bootstrap_table_meta(&catalog).await?;
    sc_catalog::bootstrap_field_meta(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let models = sc_server::install_models(&catalog, sc_model::DEFAULT_MAX_ROWS).await?;
    // The two stubs join the registry before the actions are built over it,
    // as a module's providers do on a reload.
    let mut registry = models.base_registry()?;
    registry.register(Arc::new(Sampler))?;
    registry.register(Arc::new(Warns))?;
    models.set_registry(Arc::new(registry));
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents, &models).await?;
    // Only `serve` starts the workflow engine; this stands in for it.
    let (engine, _handle) = start_workflow_engine(&catalog, &dispatcher);
    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_triggers(dispatcher.clone())
            .with_models(models),
    );
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;
    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    client
        .ok(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    Ok((client, catalog, db, engine))
}

#[tokio::test]
async fn models_predict_in_formulas_refit_nightly_and_write_back_from_code() -> Result<()> {
    let (mut client, catalog, db, _engine) = setup().await?;

    // --- The one model action --------------------------------------------
    let actions = client.ok("GET", "/api/actions", None).await;
    let names: Vec<&str> = actions
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|a| a["name"].as_str())
        .collect();
    assert!(names.contains(&"fit_model"), "{names:?}");
    assert!(!names.contains(&"predict_row"), "{names:?}");
    assert!(!names.contains(&"write_posterior"), "{names:?}");

    // --- `House prices`, and a calculated field that predicts --------------
    let house_prices = client
        .house_model("House prices", "linear_regression")
        .await;
    let first_fit = client.fit_and_activate(&house_prices).await;
    client
        .ok(
            "POST",
            "/api/tables/houses/fields",
            Some(json!({
                "name": "estimated_price",
                "type": "float8",
                "kind": { "type": "calc", "expression": "predict(\"House prices\")" },
            })),
        )
        .await;
    let counting = count_calls(&catalog)?;

    // Listing `houses` over the REST API: a number in every row, the unsold
    // house the dataset's filter excludes included, for one provider call.
    let rows = client.rows("/api/tables/houses/rows").await;
    assert_eq!(rows.len(), 61);
    assert!(
        rows.iter().all(|r| r["estimated_price"].is_number()),
        "{rows:?}"
    );
    for row in rows.iter().filter(|r| r["sold"] == json!(true)) {
        let (estimate, price) = (
            row["estimated_price"].as_f64().unwrap(),
            row["price"].as_f64().unwrap(),
        );
        assert!(close(estimate, price), "{row}");
    }
    let unsold = rows.iter().find(|r| r["id"] == json!(500)).unwrap();
    assert!(
        close(unsold["estimated_price"].as_f64().unwrap(), HOUSE_500),
        "{unsold}"
    );
    assert_eq!(counting.calls.load(Ordering::SeqCst), 1, "one call a page");

    // Filtering on it is refused, with a sentence naming the field.
    let err = client
        .refused(
            "GET",
            "/api/tables/houses/rows?estimated_price=gt.200000",
            None,
        )
        .await;
    assert!(
        err.contains(
            "cannot filter on `estimated_price`: `estimated_price` is computed after the rows \
             are read, because it calls `predict`"
        ),
        "{err}"
    );

    // --- A nightly refit --------------------------------------------------
    // The market doubles overnight.
    db.client()
        .await?
        .batch_execute("UPDATE houses SET price = 2 * price WHERE sold")
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let nightly = client
        .trigger(json!({
            "name": "refit_house_prices", "description": "", "when": "daily",
            "channel": null, "only_if": null, "action": "fit_model",
            "configuration": { "model": "House prices", "activate": "if_clean" },
            "min_role": null, "enabled": true,
        }))
        .await;
    let refit = client.run(&nightly).await;
    assert_eq!(refit["status"], json!("fitted"), "{refit}");
    assert_eq!(refit["active"], json!(true), "{refit}");
    assert_eq!(refit["warnings"], json!([]), "{refit}");
    assert!(refit["metrics"]["test"]["r2"].is_f64(), "{refit}");
    let second_fit = refit["instance"].as_str().unwrap().to_owned();
    let fits = client.active_fits(&house_prices).await;
    assert!(
        fits.contains(&(second_fit.clone(), true)) && fits.contains(&(first_fit, false)),
        "{fits:?}"
    );
    // The next read follows it, and nothing was edited.
    let estimate = client.estimated_price(500).await;
    assert!(close(estimate, 2.0 * HOUSE_500), "{estimate}");

    // A provider that warns: its nightly fit is kept, and left inactive.
    let warned = client.house_model("Warned prices", "warns").await;
    let warned_first = client.fit_and_activate(&warned).await;
    let warned_nightly = client
        .trigger(json!({
            "name": "refit_warned_prices", "description": "", "when": "daily",
            "channel": null, "only_if": null, "action": "fit_model",
            "configuration": { "model": "Warned prices", "activate": "if_clean" },
            "min_role": null, "enabled": true,
        }))
        .await;
    let refit = client.run(&warned_nightly).await;
    assert_eq!(refit["status"], json!("fitted"), "{refit}");
    assert_eq!(refit["active"], json!(false), "{refit}");
    assert_eq!(refit["warnings"], json!([WARNING]), "{refit}");
    let warned_second = refit["instance"].as_str().unwrap().to_owned();
    let fits = client.active_fits(&warned).await;
    assert!(
        fits.contains(&(warned_first, true)) && fits.contains(&(warned_second, false)),
        "{fits:?}"
    );

    // --- Radon: `fit_model`, then a code step writes the posterior back ----
    client
        .ok(
            "POST",
            "/api/models",
            Some(radon("Radon", bound(), nulls_dropped())),
        )
        .await;
    client
        .trigger(json!({
            "name": "audit_counties", "description": "", "when": "update",
            "channel": "counties", "only_if": null, "action": "insert_row",
            "configuration": { "table": "audit", "values": { "what": "row.name" } },
            "min_role": null, "enabled": true,
        }))
        .await;
    let workflow = client
        .trigger(json!({
            "name": "radon_nightly", "description": "", "when": "insert",
            "channel": "refits", "only_if": null, "body": "workflow", "action": null,
            "configuration": null, "min_role": null, "enabled": true,
        }))
        .await;
    let saved = client
        .ok(
            "POST",
            &format!("/api/workflows/{workflow}"),
            Some(json!({
                "description": "refit Radon, then write it back",
                "workflow": {
                    "start": "refit",
                    "steps": [
                        {
                            "name": "refit",
                            "kind": { "type": "action", "action": "fit_model",
                                      "configuration": { "model": "Radon",
                                                         "activate": "if_clean" } },
                            "next": { "type": "step", "step": "write_back" }
                        },
                        {
                            "name": "write_back",
                            "kind": { "type": "action", "action": "run_js_code",
                                      "configuration": { "code": WRITE_BACK_JS } },
                            "next": { "type": "end" }
                        }
                    ]
                },
            })),
        )
        .await;
    assert_eq!(saved["issues"], json!([]), "{saved}");
    client
        .ok(
            "POST",
            "/api/tables/refits/rows",
            Some(json!({ "note": "nightly" })),
        )
        .await;
    let mut run = Value::Null;
    for _ in 0..400 {
        let runs = client
            .ok("GET", &format!("/api/workflows/{workflow}/runs"), None)
            .await;
        if let Some(first) = runs.as_array().and_then(|r| r.first())
            && ["done", "failed", "aborted"].contains(&first["state"].as_str().unwrap_or(""))
        {
            let id = first["id"].as_str().unwrap().to_owned();
            run = client.ok("GET", &format!("/api/runs/{id}"), None).await;
            break;
        }
        tokio::time::sleep(Duration::from_millis(25)).await;
    }
    assert_eq!(run["state"], json!("done"), "{run}");
    let wrote = &run["context"]["context"]["write_back"];
    // The refit was clean and became active, and the handle is on it.
    assert_eq!(wrote["refit"]["active"], json!(true), "{run}");
    assert_eq!(wrote["fit"], wrote["refit"]["instance"], "{run}");
    assert_eq!(wrote["written"], json!(3), "{run}");
    assert_eq!(wrote["table"], json!("counties"), "{run}");
    let predict = wrote["said"]["predict"].as_str().unwrap_or_default();
    assert!(
        predict.contains("`Radon` is a posterior") && predict.contains("`m.draws(…)`"),
        "{run}"
    );
    assert_eq!(wrote["hasDraws"], json!(false), "{run}");
    let draws = wrote["said"]["draws"].as_str().unwrap_or_default();
    assert!(
        draws.contains("`House prices` is a linear_regression regression")
            && draws.contains("`draws` is for posterior models"),
        "{run}"
    );

    // `counties.alpha_mean` is filled, and the `counties` update trigger fired
    // once per county.
    let mut counties = client.rows("/api/tables/counties/rows").await;
    counties.sort_by_key(|r| r["id"].as_i64());
    for (k, county) in counties.iter().enumerate() {
        let mean = county["alpha_mean"].as_f64().unwrap();
        assert!((mean - (k + 1) as f64).abs() < 0.05, "{county}");
        assert!(county["alpha_sd"].as_f64().unwrap() > 0.0, "{county}");
    }
    let mut trail: Vec<String> = client
        .rows("/api/tables/audit/rows")
        .await
        .iter()
        .map(|r| r["what"].as_str().unwrap().to_owned())
        .collect();
    trail.sort();
    assert_eq!(trail, ["Aitkin", "Anoka", "Becker"]);

    // --- The same, from a Python body --------------------------------------
    db.client()
        .await?
        .batch_execute("UPDATE counties SET alpha_mean = NULL, alpha_sd = NULL")
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let python = client
        .trigger(json!({
            "name": "radon_write_back_py", "description": "", "when": "none",
            "channel": null, "only_if": null, "action": "run_python_code",
            "configuration": { "code": WRITE_BACK_PY }, "min_role": null, "enabled": true,
        }))
        .await;
    let (status, ran) = client
        .send(
            "POST",
            &format!("/api/triggers/{python}/run"),
            Some(json!({})),
        )
        .await;
    #[cfg(feature = "python")]
    {
        assert_eq!(status, StatusCode::OK, "{ran}");
        let result = &ran["result"];
        assert_eq!(result["written"], json!(3), "{ran}");
        let predicted = result["predicted"].as_str().unwrap_or_default();
        assert!(predicted.contains("`m.draws(…)`"), "{ran}");
        assert_eq!(result["has_draws"], json!(false), "{ran}");
        let draws = result["draws"].as_str().unwrap_or_default();
        assert!(draws.contains("`draws` is for posterior models"), "{ran}");
        let counties = client.rows("/api/tables/counties/rows").await;
        assert!(
            counties.iter().all(|c| c["alpha_mean"].is_f64()),
            "{counties:?}"
        );
        assert_eq!(client.rows("/api/tables/audit/rows").await.len(), 6);
    }
    #[cfg(not(feature = "python"))]
    {
        // The trigger saves in every build; firing it in one without Python
        // names the rebuild, and writes nothing.
        assert_ne!(status, StatusCode::OK, "{ran}");
        assert!(ran.to_string().contains("--features python"), "{ran}");
        let counties = client.rows("/api/tables/counties/rows").await;
        assert!(
            counties.iter().all(|c| c["alpha_mean"].is_null()),
            "{counties:?}"
        );
    }
    Ok(())
}
