//! Stan TODO 7.7: the posterior's API, its two actions and a code body's
//! `models`, driven through the assembled router over a **stub sampler** — no
//! CmdStan. What is under test is everything the host does around a
//! posterior: binding the program's data (suggested and previewed), the fit as
//! a job with a cancel, the draws read back by key and label with thinning and
//! the response cap, a summary on demand, the write-back in both modes through
//! the row layer (so the target table's own trigger fires), the run as a zip,
//! `fit_model` from a trigger, and a model handle in a JavaScript body — its
//! draws, and (milestone 31, 2.6) its `writePosterior` from a workflow step
//! after `fit_model` and under a caller's authority. The Python handle is
//! `sc-python`'s `python_models.rs`.

use std::collections::HashMap;
use std::io::Read as _;
use std::sync::Arc;
use std::time::Duration;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_model::{
    Declaration, DrawSeries, Element, FitContext, FitResult, Frame, Interface, ModelProvider,
    OutcomeSpec, PosteriorInput, PosteriorMethod, PosteriorResult, PosteriorRun, Prediction,
    SizeExpr,
};
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ModelServices, ServerConfig, StanSettings, admin_handlers,
    build_router_with_apps, default_js_evaluator, install_triggers, start_workflow_engine,
};
use sc_test_harness::TestDb;
use sc_types::{Attrs, BasicType, FormField};
use serde_json::{Value, json};
use tower::ServiceExt;

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// Three counties and six homes, one of whose `floor` is null — for the
/// preview's inline error and the `drop` policy that fixes it.
const SCHEMA: &str = "
    CREATE TABLE counties (
        id bigint primary key, name text, log_uranium double precision,
        alpha_mean double precision, alpha_sd double precision
    );
    CREATE TABLE homes (
        id bigint primary key, county bigint references counties(id),
        floor double precision, y double precision
    );
    CREATE TABLE audit (id bigint generated by default as identity primary key, what text);
    CREATE TABLE refits (id bigint generated by default as identity primary key, note text);
    CREATE TABLE estimates (
        id bigint generated by default as identity primary key,
        county bigint, county_name text, lower double precision, upper double precision,
        fit text
    );
    INSERT INTO counties (id, name, log_uranium) VALUES
        (27001, 'Aitkin', -0.7), (27003, 'Anoka', -0.8), (27005, 'Becker', 0.3);
    INSERT INTO homes VALUES
        (1, 27001, 0, 0.8), (2, 27001, 1, 1.2), (3, 27003, 0, 1.9),
        (4, 27003, null, 2.1), (5, 27005, 1, 2.8), (6, 27005, 0, 3.3);
";

/// Chains and draws the sampler makes.
const CHAINS: u32 = 4;
const DRAWS: usize = 250;

/// A sampler with a program of its own: `alpha[j]` is about county `j`, and
/// its draws are independent normals about `j` — so they mix, and a fit of
/// them has no warnings unless `diverge` puts one there. With `sleep` it
/// samples until it is cancelled.
pub(crate) struct Sampler;

/// A standard normal, from a small deterministic generator: the draws are the
/// same every run, so what the diagnostics say about them is too.
struct Normals(u64);

impl Normals {
    fn uniform(&mut self) -> f64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        ((self.0 >> 11) as f64 + 0.5) / (1u64 << 53) as f64
    }

    fn next(&mut self) -> f64 {
        let (u, v) = (self.uniform(), self.uniform());
        (-2.0 * u.ln()).sqrt() * (2.0 * std::f64::consts::PI * v).cos()
    }
}

#[async_trait::async_trait]
impl ModelProvider for Sampler {
    fn name(&self) -> &str {
        "sampler"
    }
    fn description(&self) -> &str {
        "a stub posterior with a program of its own"
    }
    fn config_declaration(&self) -> Vec<FormField> {
        vec![
            FormField::new(sc_model::BINDINGS_KEY, BasicType::Json),
            FormField::new(sc_model::DIMENSIONS_KEY, BasicType::Json),
            FormField::new(sc_model::POLICIES_KEY, BasicType::Json),
            FormField::new(sc_model::LABELS_KEY, BasicType::Json),
            FormField::new("sleep", BasicType::Bool),
            FormField::new("diverge", BasicType::Bool),
        ]
    }
    fn outcome_spec(&self) -> OutcomeSpec {
        OutcomeSpec::Posterior { prediction: None }
    }
    fn binds_data(&self) -> bool {
        true
    }
    fn cancellable(&self) -> bool {
        true
    }
    async fn fit(&self, _f: &Frame, _c: &Attrs, _h: &Attrs) -> Result<FitResult> {
        Err(Error::msg("sampled, not fitted"))
    }
    async fn predict(&self, _s: &serde_json::Value, _f: &Frame) -> Result<Vec<Prediction>> {
        Err(Error::msg("inspected, not applied"))
    }
    async fn interface(&self, _config: &Attrs) -> Result<Option<Interface>> {
        let n = || vec![SizeExpr::var("N")];
        Ok(Some(Interface {
            data: vec![
                Declaration::new("N", Element::Int, vec![], "int<lower=1>"),
                Declaration::new("J", Element::Int, vec![], "int<lower=1>"),
                Declaration::new(
                    "county",
                    Element::Int,
                    n(),
                    "array[N] int<lower=1, upper=J>",
                )
                .bounded(Some("1"), Some("J")),
                Declaration::new("x", Element::Real, n(), "vector[N]"),
                Declaration::new("y", Element::Real, n(), "vector[N]"),
            ],
            parameters: vec![
                Declaration::new(
                    "alpha",
                    Element::Real,
                    vec![SizeExpr::var("J")],
                    "vector[J]",
                ),
                Declaration::new("sigma", Element::Real, vec![], "real<lower=0>")
                    .bounded(Some("0"), None),
            ],
            ..Interface::default()
        }))
    }
    async fn fit_posterior(
        &self,
        input: &PosteriorInput,
        config: &Attrs,
        ctx: &FitContext<'_>,
    ) -> Result<PosteriorResult> {
        if config.get("sleep") == Some(&json!(true)) {
            for _ in 0..1500 {
                if ctx.cancelled() {
                    return Err(Error::msg("the fit was cancelled"));
                }
                tokio::time::sleep(Duration::from_millis(20)).await;
            }
            return Err(Error::msg("never cancelled"));
        }
        let j = input.data["J"].as_u64().unwrap_or(0) as usize;
        let mut normals = Normals(7);
        let mut draws = Vec::new();
        for chain in 1..=CHAINS {
            for k in 1..=j {
                let values = (0..DRAWS)
                    .map(|_| k as f64 + 0.1 * normals.next())
                    .collect();
                draws.push(DrawSeries::new("alpha", vec![k], chain, values));
            }
            let sigma = (0..DRAWS).map(|_| 0.5 + 0.01 * normals.next()).collect();
            draws.push(DrawSeries::new("sigma", vec![], chain, sigma));
            let lp = (0..DRAWS).map(|_| -3.0 + normals.next()).collect();
            draws.push(DrawSeries::new("lp__", vec![], chain, lp));
            let mut divergent = vec![0.0; DRAWS];
            if config.get("diverge") == Some(&json!(true)) && chain == 1 {
                divergent[3] = 1.0;
            }
            draws.push(DrawSeries::new("divergent__", vec![], chain, divergent));
        }
        Ok(PosteriorResult {
            state: json!({ "stub": true }),
            draws,
            parameters: Vec::new(),
            run: PosteriorRun {
                method: PosteriorMethod::Mcmc,
                ..PosteriorRun::default()
            },
        })
    }
}

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn raw(
        &mut self,
        method: &str,
        path: &str,
        body: Option<Value>,
    ) -> (StatusCode, HashMap<String, String>, Vec<u8>) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        let mut headers = HashMap::new();
        for (name, value) in response.headers() {
            if let Ok(text) = value.to_str() {
                headers.insert(name.as_str().to_owned(), text.to_owned());
            }
        }
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 16 * 1024 * 1024)
            .await
            .unwrap();
        (status, headers, bytes.to_vec())
    }

    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let body = match body {
            Some(mut b) if crate::named_datasets::carries_a_model(method, path) => {
                let mut ids = Vec::new();
                for (pointer, create) in crate::named_datasets::inline_datasets(&b) {
                    let (status, made) =
                        Box::pin(self.send("POST", "/api/datasets", Some(create))).await;
                    assert!(status.is_success(), "creating a dataset: {status} {made}");
                    ids.push((pointer, made["dataset"]["id"].as_str().unwrap().to_owned()));
                }
                crate::named_datasets::use_ids(&mut b, ids);
                Some(b)
            }
            other => other,
        };
        let (status, _, bytes) = self.raw(method, path, body).await;
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    async fn ok(&mut self, method: &str, path: &str, body: Option<Value>) -> Value {
        let (status, value) = self.send(method, path, body).await;
        assert!(status.is_success(), "{method} {path}: {status} {value}");
        value
    }

    /// Poll one instance until it stops saying `fitting`.
    async fn await_fit(&mut self, instance: &str) -> Value {
        for _ in 0..800 {
            let body = self
                .ok("GET", &format!("/api/model-instances/{instance}"), None)
                .await;
            if body["status"] != json!("fitting") {
                return body;
            }
            tokio::time::sleep(Duration::from_millis(25)).await;
        }
        panic!("the fit of instance {instance} never finished");
    }

    async fn rows(&mut self, table: &str) -> Vec<Value> {
        self.ok("GET", &format!("/api/tables/{table}/rows"), None)
            .await
            .as_array()
            .cloned()
            .unwrap_or_default()
    }

    async fn trigger(&mut self, body: Value) -> String {
        let created = self.ok("POST", "/api/triggers", Some(body)).await;
        created["id"].as_str().unwrap().to_owned()
    }

    async fn run(&mut self, trigger: &str, payload: Value) -> Value {
        self.ok(
            "POST",
            &format!("/api/triggers/{trigger}/run"),
            Some(payload),
        )
        .await
    }
}

struct Server {
    client: Client,
    catalog: Arc<Catalog>,
    models: ModelServices,
    dispatcher: Arc<sc_action::TriggerDispatcher>,
    _engine: Arc<sc_workflow::WorkflowEngineTask>,
    _db: TestDb,
}

async fn setup() -> Result<Server> {
    setup_with(&StanSettings::default()).await
}

/// [`setup`], with the Stan flags `stan` (TODO §20).
async fn setup_with(stan: &StanSettings) -> Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let models = sc_server::install_models_with(&catalog, sc_model::DEFAULT_MAX_ROWS, stan).await?;
    // The sampler joins the registry before the actions are built over it, as
    // a module's provider does on a reload.
    let mut registry = models.base_registry()?;
    registry.register(Arc::new(Sampler))?;
    models.set_registry(Arc::new(registry));
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents, &models).await?;
    // For the workflow that refits and then writes back from a code step;
    // only `serve` starts the engine, and this stands in for it.
    let (engine, _handle) = start_workflow_engine(&catalog, &dispatcher);
    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_triggers(dispatcher.clone())
            .with_models(models.clone()),
    );
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;
    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    client
        .ok(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    Ok(Server {
        client,
        catalog,
        models,
        dispatcher,
        _engine: engine,
        _db: db,
    })
}

/// The radon model over the sampler, with `bindings` and `extra` settings.
pub(crate) fn radon(name: &str, bindings: Value, extra: Value) -> Value {
    let mut configuration = json!({ "bindings": bindings });
    if let (Value::Object(config), Value::Object(extra)) = (&mut configuration, extra) {
        config.extend(extra);
    }
    json!({
        "name": name,
        "description": "",
        "provider": "sampler",
        "dataset": {
            "table": "homes",
            "columns": [
                { "name": "county", "expr": "county" },
                { "name": "floor", "expr": "floor" },
                { "name": "y", "expr": "y" },
            ],
        },
        "related": [{
            "name": "counties",
            "dataset": {
                "table": "counties",
                "columns": [{ "name": "log_uranium", "expr": "log_uranium" }],
            },
            "label": "name",
        }],
        "configuration": configuration,
        "hyperparameters": {},
        "attributes": {},
    })
}

/// The bindings Bind automatically proposes, plus `x`, which the names do
/// not say.
pub(crate) fn bound() -> Value {
    json!({
        "N": { "kind": "count", "dataset": "main" },
        "J": { "kind": "size", "dimension": "counties" },
        "county": { "kind": "index", "dataset": "main", "column": "county",
                    "dimension": "counties" },
        "x": { "kind": "column", "dataset": "main", "column": "floor" },
        "y": { "kind": "column", "dataset": "main", "column": "y" },
    })
}

pub(crate) fn nulls_dropped() -> Value {
    json!({ "policies": { "main": { "nulls": "drop" } } })
}

/// Save a model and fit it to the end, answering the model's id and the
/// finished instance.
async fn fitted(client: &mut Client, body: Value) -> (String, Value) {
    let saved = client.ok("POST", "/api/models", Some(body)).await;
    let id = saved["id"].as_str().unwrap().to_owned();
    let started = client
        .ok("POST", &format!("/api/models/{id}/fit"), Some(json!({})))
        .await;
    let instance = client.await_fit(started["id"].as_str().unwrap()).await;
    (id, instance)
}

#[tokio::test]
async fn a_posterior_is_bound_fitted_read_by_key_and_written_back() -> Result<()> {
    let mut server = setup().await?;
    let client = &mut server.client;

    // The picker says which providers bind data and can be stopped.
    let listed = client.ok("GET", "/api/model-providers", None).await;
    let provider = |name: &str| {
        listed["providers"]
            .as_array()
            .unwrap()
            .iter()
            .find(|p| p["name"] == json!(name))
            .cloned()
            .unwrap_or_else(|| panic!("no provider {name}"))
    };
    assert_eq!(provider("sampler")["binds_data"], json!(true));
    assert_eq!(provider("sampler")["cancellable"], json!(true));
    assert_eq!(provider("sampler")["unavailable"], Value::Null);
    assert_eq!(provider("linear_regression")["binds_data"], json!(false));
    assert_eq!(provider("linear_regression")["cancellable"], json!(false));
    assert_eq!(provider("stan")["cancellable"], json!(true));

    // Bind automatically: the names, the key into `counties` and the sizes.
    let suggested = client
        .ok(
            "POST",
            "/api/model-bindings/suggest",
            Some(radon("Radon", json!({}), json!({}))),
        )
        .await;
    assert_eq!(
        suggested["bindings"],
        json!({
            "N": { "kind": "count", "dataset": "main" },
            "J": { "kind": "size", "dimension": "counties" },
            "county": { "kind": "index", "dataset": "main", "column": "county",
                        "dimension": "counties" },
            "y": { "kind": "column", "dataset": "main", "column": "y" },
        }),
        "{suggested}"
    );
    assert!(
        suggested["reasons"]["county"]
            .as_str()
            .unwrap()
            .contains("a key into `counties`"),
        "{suggested}"
    );

    // Preview data: the null `floor` is on `x`'s row, and the rest binds.
    let preview = client
        .ok(
            "POST",
            "/api/model-data/preview",
            Some(radon("Radon", bound(), json!({}))),
        )
        .await;
    let row = |name: &str| {
        preview["variables"]
            .as_array()
            .unwrap()
            .iter()
            .find(|v| v["name"] == json!(name))
            .cloned()
            .unwrap()
    };
    assert!(
        row("x")["error"].as_str().unwrap().contains("is null"),
        "{preview}"
    );
    assert_eq!(row("N")["first"], json!([6]), "{preview}");
    assert_eq!(row("J")["first"], json!([3]), "{preview}");
    assert_eq!(row("county")["first"], json!([1, 1, 2, 2, 3]), "{preview}");
    assert_eq!(preview["errors"], json!([]));
    assert_eq!(preview["report"]["dimensions"]["counties"], json!(3));
    // With the null dropped, everything binds.
    let preview = client
        .ok(
            "POST",
            "/api/model-data/preview",
            Some(radon("Radon", bound(), nulls_dropped())),
        )
        .await;
    assert!(
        preview["variables"]
            .as_array()
            .unwrap()
            .iter()
            .all(|v| v["error"].is_null()),
        "{preview}"
    );

    // Save and fit.
    let (model_id, instance) = fitted(client, radon("Radon", bound(), nulls_dropped())).await;
    assert_eq!(instance["status"], json!("fitted"), "{instance}");
    assert_eq!(instance["warnings"], json!([]), "{instance}");
    // The sampler keeps no program, so it cannot say whether one has changed.
    assert_eq!(instance["program_changed"], Value::Null, "{instance}");
    assert_eq!(
        instance["variables"]["alpha"],
        json!({ "dims": [3], "dimensions": ["counties"] }),
        "{instance}"
    );
    let id = instance["id"].as_str().unwrap().to_owned();

    // The draws of one county, by key, thinned.
    let draws = client
        .ok(
            "GET",
            &format!(
                "/api/model-instances/{id}/draws?variable=alpha&elements={}&thin=10",
                urlencoding(&json!({ "counties": ["27003"] }).to_string())
            ),
            None,
        )
        .await;
    assert_eq!(draws["names"], json!(["alpha[Anoka]"]));
    assert_eq!(draws["dims"], json!([3]));
    assert_eq!(draws["labels"], json!([["Aitkin", "Anoka", "Becker"]]));
    assert_eq!(draws["keys"], json!([[27001, 27003, 27005]]));
    assert_eq!(draws["chains"].as_array().unwrap().len(), CHAINS as usize);
    assert_eq!(
        draws["chains"][0]["draws"][0].as_array().unwrap().len(),
        DRAWS / 10
    );
    // …and by label, and of one chain.
    let draws = client
        .ok(
            "GET",
            &format!(
                "/api/model-instances/{id}/draws?variable=alpha&chains=2&elements={}",
                urlencoding(&json!({ "counties": ["Becker"] }).to_string())
            ),
            None,
        )
        .await;
    assert_eq!(draws["names"], json!(["alpha[Becker]"]));
    assert_eq!(draws["chains"][0]["chain"], json!(2));
    assert_eq!(draws["chains"].as_array().unwrap().len(), 1);

    // The cap is a refusal with the arithmetic, before anything is read.
    server.models.set_max_draws_response(1_000);
    let (status, refused) = client
        .send(
            "GET",
            &format!("/api/model-instances/{id}/draws?variable=alpha"),
            None,
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    let said = refused.to_string();
    assert!(
        said.contains("3000 numbers (3 elements × 4 chains × 250 draws)"),
        "{said}"
    );
    assert!(said.contains("`thin`"), "{said}");
    server
        .models
        .set_max_draws_response(sc_model::DEFAULT_MAX_DRAWS_RESPONSE);

    // A summary on demand, of one county by label.
    let summary = client
        .ok(
            "GET",
            &format!(
                "/api/model-instances/{id}/summary?variable=alpha&elements={}",
                urlencoding(&json!({ "counties": ["Aitkin"] }).to_string())
            ),
            None,
        )
        .await;
    assert_eq!(summary["source"], json!("draws"));
    assert_eq!(summary["columns"][0], json!("counties"));
    assert_eq!(summary["rows"][0][0], json!("Aitkin"));
    let mean = summary["rows"][0][1].as_f64().unwrap();
    assert!((mean - 1.0).abs() < 0.05, "{summary}");

    // A write-back into the rows the variable is about fires their trigger.
    let audit = client
        .trigger(json!({
            "name": "audit_counties", "description": "", "when": "update",
            "channel": "counties", "only_if": null, "action": "insert_row",
            "configuration": { "table": "audit", "values": { "what": "row.name" } },
            "min_role": null, "enabled": true,
        }))
        .await;
    assert!(!audit.is_empty());
    let written = client
        .ok(
            "POST",
            &format!("/api/model-instances/{id}/posterior-writes"),
            Some(json!({
                "variable": "alpha", "mode": "update",
                "statistics": { "mean": "alpha_mean", "sd": "alpha_sd" },
                "table": null, "coordinates": null, "instance_field": null, "elements": null,
            })),
        )
        .await;
    assert_eq!(written["written"], json!(3));
    assert_eq!(written["table"], json!("counties"));
    let mut counties = client.rows("counties").await;
    counties.sort_by_key(|r| r["id"].as_i64());
    for (k, county) in counties.iter().enumerate() {
        let mean = county["alpha_mean"].as_f64().unwrap();
        assert!((mean - (k + 1) as f64).abs() < 0.05, "{county}");
        assert!(county["alpha_sd"].as_f64().unwrap() > 0.0, "{county}");
    }
    let mut trail: Vec<String> = client
        .rows("audit")
        .await
        .iter()
        .map(|r| r["what"].as_str().unwrap().to_owned())
        .collect();
    trail.sort();
    assert_eq!(trail, ["Aitkin", "Anoka", "Becker"]);

    // …and one new row per county into another table, with its coordinates.
    let written = client
        .ok(
            "POST",
            &format!("/api/model-instances/{id}/posterior-writes"),
            Some(json!({
                "variable": "alpha", "mode": "insert", "table": "estimates",
                "statistics": { "q5": "lower", "q95": "upper" },
                "coordinates": [
                    { "axis": "counties", "field": "county" },
                    { "axis": "counties", "field": "county_name", "value": "label" },
                ],
                "instance_field": "fit",
            })),
        )
        .await;
    assert_eq!(written["written"], json!(3));
    let estimates = client.rows("estimates").await;
    let anoka = estimates
        .iter()
        .find(|r| r["county_name"] == json!("Anoka"))
        .unwrap();
    assert_eq!(anoka["county"], json!(27003));
    assert_eq!(anoka["fit"], json!(id));
    assert!(anoka["lower"].as_f64().unwrap() < anoka["upper"].as_f64().unwrap());

    // A statistic into a text field is refused before anything is written.
    let (status, refused) = client
        .send(
            "POST",
            &format!("/api/model-instances/{id}/posterior-writes"),
            Some(json!({
                "variable": "alpha", "mode": "update", "statistics": { "mean": "name" },
            })),
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    assert!(
        refused.to_string().contains("`name` of `counties` is text"),
        "{refused}"
    );

    // The run as a zip: a CSV per chain in CmdStan's layout, and the
    // coordinates beside them.
    let (status, headers, zip) = client
        .raw("GET", &format!("/api/model-instances/{id}/run"), None)
        .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(headers["content-type"], "application/zip");
    assert!(
        headers["content-disposition"].contains("Radon-"),
        "{headers:?}"
    );
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(zip)).unwrap();
    let mut names: Vec<String> = archive.file_names().map(str::to_owned).collect();
    names.sort();
    assert_eq!(
        names,
        [
            "chain-1.csv",
            "chain-2.csv",
            "chain-3.csv",
            "chain-4.csv",
            "coordinates.json",
            "variables.json"
        ]
    );
    let mut csv = String::new();
    archive
        .by_name("chain-1.csv")
        .unwrap()
        .read_to_string(&mut csv)
        .unwrap();
    let header = csv.lines().next().unwrap();
    assert_eq!(header, "lp__,divergent__,alpha.1,alpha.2,alpha.3,sigma");
    assert_eq!(csv.lines().count(), 1 + DRAWS);
    let mut coordinates = String::new();
    archive
        .by_name("coordinates.json")
        .unwrap()
        .read_to_string(&mut coordinates)
        .unwrap();
    assert!(coordinates.contains("Becker"), "{coordinates}");

    // `compileModel` is for a program provider only.
    let (status, refused) = client
        .send("POST", &format!("/api/models/{model_id}/compile"), None)
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    assert!(
        refused.to_string().contains("no program to compile"),
        "{refused}"
    );
    Ok(())
}

/// TODO §20: the `--cmdstan`/`--stan-*` flags, as `serve` hands them over,
/// are what the services build the provider with and what every preview and
/// fit on the node works within.
#[tokio::test]
async fn the_stan_flags_reach_the_provider_the_preview_and_the_fit() -> Result<()> {
    let cache = std::env::temp_dir().join(format!("sc-stan-flags-{}", std::process::id()));
    let mut stan = StanSettings {
        cmdstan: Some("/nonexistent/cmdstan-2.40.0".into()),
        cache_dir: Some(cache.clone()),
        max_processes: Some(3),
        max_draws_response: 1_000,
        ..StanSettings::default()
    };
    // Five homes after the drop: N, J and three columns of five is 17 values.
    stan.limits.max_data_values = 10;
    let mut server = setup_with(&stan).await?;

    let provider = server.models.stan();
    assert_eq!(provider.budget().processes(), 3);
    assert_eq!(provider.compile_cache().dir(), cache.as_path());
    assert_eq!(server.models.max_draws_response(), 1_000);
    assert_eq!(server.models.posterior_limits().max_data_values, 10);
    // A named CmdStan that is not there is said, not stepped over for
    // `~/.cmdstan`'s.
    let why = provider
        .unavailable()
        .expect("the named CmdStan is missing");
    assert!(why.contains("/nonexistent/cmdstan-2.40.0"), "{why}");
    assert!(provider.cmdstan().is_none());

    let client = &mut server.client;
    let preview = client
        .ok(
            "POST",
            "/api/model-data/preview",
            Some(radon("Radon", bound(), nulls_dropped())),
        )
        .await;
    let errors = preview["errors"].to_string();
    assert!(
        errors.contains("the bound data has 17 values, more than the 10 allowed")
            && errors.contains("`--stan-max-data-values`"),
        "{preview}"
    );
    let (_, instance) = fitted(client, radon("Radon", bound(), nulls_dropped())).await;
    assert_eq!(instance["status"], json!("failed"), "{instance}");
    assert!(
        instance["error"]
            .as_str()
            .unwrap()
            .contains("`--stan-max-data-values`"),
        "{instance}"
    );

    // The draws ceiling: the fit finishes, and says its draws were not kept.
    let mut stan = StanSettings::default();
    stan.limits.max_draws_bytes = 1_000;
    let mut server = setup_with(&stan).await?;
    let (_, instance) = fitted(&mut server.client, radon("Radon", bound(), nulls_dropped())).await;
    assert_eq!(instance["status"], json!("fitted"), "{instance}");
    let warnings = instance["warnings"].to_string();
    assert!(
        warnings.contains("over the limit of") && warnings.contains("`--stan-max-draws-bytes`"),
        "{instance}"
    );
    Ok(())
}

#[tokio::test]
async fn a_running_posterior_is_cancelled_and_the_others_say_why_not() -> Result<()> {
    let mut server = setup().await?;
    let client = &mut server.client;

    let mut extra = nulls_dropped();
    extra["sleep"] = json!(true);
    let saved = client
        .ok("POST", "/api/models", Some(radon("Sleepy", bound(), extra)))
        .await;
    let model = saved["id"].as_str().unwrap().to_owned();
    let started = client
        .ok("POST", &format!("/api/models/{model}/fit"), Some(json!({})))
        .await;
    let id = started["id"].as_str().unwrap().to_owned();
    let asked = client
        .ok("POST", &format!("/api/model-instances/{id}/cancel"), None)
        .await;
    assert_eq!(asked["cancel_requested"], json!(true), "{asked}");
    let finished = client.await_fit(&id).await;
    assert_eq!(finished["status"], json!("failed"), "{finished}");
    assert!(
        finished["error"].as_str().unwrap().contains("cancelled"),
        "{finished}"
    );

    // A fit that has finished has nothing to cancel.
    let (status, refused) = client
        .send("POST", &format!("/api/model-instances/{id}/cancel"), None)
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    assert!(refused.to_string().contains("no running fit"), "{refused}");

    // And a provider whose fit is not a process cannot be stopped at all.
    let saved = client
        .ok(
            "POST",
            "/api/models",
            Some(json!({
                "name": "Plain", "provider": "linear_regression",
                "dataset": { "table": "homes", "columns": [
                    { "name": "y", "expr": "y" }, { "name": "floor", "expr": "floor" },
                ]},
                "configuration": { "label": "y" },
            })),
        )
        .await;
    let plain = sc_model::ModelId(uuid::Uuid::parse_str(saved["id"].as_str().unwrap()).unwrap());
    let running = sc_model::ModelInstance::starting(plain);
    sc_model::save_model_instance(&server.catalog, &running).await?;
    let (status, refused) = client
        .send(
            "POST",
            &format!("/api/model-instances/{}/cancel", running.id),
            None,
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    assert!(
        refused
            .to_string()
            .contains("a fit of `linear_regression` cannot be cancelled"),
        "{refused}"
    );
    Ok(())
}

#[tokio::test]
async fn triggers_refit_write_back_and_read_the_draws_from_code() -> Result<()> {
    let mut server = setup().await?;
    let client = &mut server.client;
    let saved = client
        .ok(
            "POST",
            "/api/models",
            Some(radon("Radon", bound(), nulls_dropped())),
        )
        .await;
    let model = saved["id"].as_str().unwrap().to_owned();

    // Refit from a trigger, and make the new fit active: it has no warnings.
    let refit = client
        .trigger(json!({
            "name": "refit", "description": "", "when": "none", "channel": null,
            "only_if": null, "action": "fit_model",
            "configuration": { "model": "Radon", "activate": "if_clean" },
            "min_role": null, "enabled": true,
        }))
        .await;
    let ran = client.run(&refit, json!({})).await;
    assert_eq!(ran["result"]["status"], json!("fitted"), "{ran}");
    assert_eq!(ran["result"]["active"], json!(true), "{ran}");
    let first = ran["result"]["instance"].as_str().unwrap().to_owned();
    let listed = client
        .ok("GET", &format!("/api/models/{model}/instances"), None)
        .await;
    let active: Vec<&Value> = listed
        .as_array()
        .unwrap()
        .iter()
        .filter(|i| i["active"] == json!(true))
        .collect();
    assert_eq!(active.len(), 1);
    assert_eq!(active[0]["id"], json!(first));

    // The fit the trigger made is the one written back. (Milestone 31: from
    // the admin API here; a code body's `m.writePosterior` is Phase 2's.)
    let written = client
        .ok(
            "POST",
            &format!("/api/model-instances/{first}/posterior-writes"),
            Some(json!({
                "variable": "alpha", "mode": "update",
                "statistics": { "q50": "alpha_mean" },
            })),
        )
        .await;
    assert_eq!(written["written"], json!(3), "{written}");
    assert_eq!(written["instance"], json!(first));
    let becker = client
        .rows("counties")
        .await
        .into_iter()
        .find(|r| r["name"] == json!("Becker"))
        .unwrap();
    assert!((becker["alpha_mean"].as_f64().unwrap() - 3.0).abs() < 0.05);

    // A fit with a warning is kept and left inactive.
    let mut extra = nulls_dropped();
    extra["diverge"] = json!(true);
    let mut body = radon("Radon", bound(), extra);
    body["id"] = json!(model);
    client.ok("POST", "/api/models", Some(body)).await;
    let ran = client.run(&refit, json!({})).await;
    assert_eq!(ran["result"]["status"], json!("fitted"), "{ran}");
    assert_eq!(ran["result"]["active"], json!(false), "{ran}");
    assert!(
        ran["result"]["warnings"][0]
            .as_str()
            .unwrap()
            .contains("1 divergent transition"),
        "{ran}"
    );

    // The draws from a JavaScript body: by label, by key, and a named fit.
    let code = client
        .trigger(json!({
            "name": "read_alpha", "description": "", "when": "none", "channel": null,
            "only_if": null, "action": "run_js_code",
            "configuration": { "code": r#"
                const m = await models.get("Radon");
                const d = await m.draws("alpha", { keys: ["Anoka"], thin: 50, chains: [1] });
                const s = await m.summary("alpha", { keys: [27001] });
                const byId = await models.get("Radon", { fit: payload.instance });
                const sigma = await byId.summary("sigma");
                return {
                    names: d.names, n: d.chains[0].draws[0].length, label: s.rows[0][0],
                    sigma: sigma.names, status: m.fit.status, active: m.fit.active,
                    vars: m.variables, same: byId.fit.id === payload.instance,
                };
            "# },
            "min_role": null, "enabled": true,
        }))
        .await;
    let ran = client.run(&code, json!({ "instance": first })).await;
    assert_eq!(
        ran["result"],
        json!({
            "names": ["alpha[Anoka]"], "n": 5, "label": "Aitkin", "sigma": ["sigma"],
            "status": "fitted", "active": true, "vars": ["alpha", "sigma"], "same": true,
        }),
        "{ran}"
    );
    // A mistake is the host's sentence at the call site.
    let wrong = client
        .trigger(json!({
            "name": "read_wrong", "description": "", "when": "none", "channel": null,
            "only_if": null, "action": "run_js_code",
            "configuration": { "code": r#"
                try { await (await models.get("Radon")).draws("beta"); }
                catch (e) { return e.message; }
            "# },
            "min_role": null, "enabled": true,
        }))
        .await;
    let ran = client.run(&wrong, json!({})).await;
    assert!(
        ran["result"]
            .as_str()
            .unwrap()
            .contains("has no variable `beta` (its variables are `alpha`, `sigma`)"),
        "{ran}"
    );
    Ok(())
}

/// A trigger that audits every update of a county — what a write-back must
/// fire, whoever asked for it.
async fn audited(client: &mut Client) {
    client
        .trigger(json!({
            "name": "audit_counties", "description": "", "when": "update",
            "channel": "counties", "only_if": null, "action": "insert_row",
            "configuration": { "table": "audit", "values": { "what": "row.name" } },
            "min_role": null, "enabled": true,
        }))
        .await;
}

/// Milestone 31's Radon: a workflow runs `fit_model`, and then a code step
/// writes the new fit's posterior back through the handle — firing the
/// `counties` update trigger — and learns that a posterior does not predict.
#[tokio::test]
async fn a_workflow_refits_and_a_code_step_writes_the_posterior_back() -> Result<()> {
    let mut server = setup().await?;
    let client = &mut server.client;
    client
        .ok(
            "POST",
            "/api/models",
            Some(radon("Radon", bound(), nulls_dropped())),
        )
        .await;
    audited(client).await;

    let created = client
        .ok(
            "POST",
            "/api/triggers",
            Some(json!({
                "name": "nightly", "description": "", "when": "insert", "channel": "refits",
                "only_if": null, "body": "workflow", "action": null, "configuration": null,
                "min_role": null, "enabled": true,
            })),
        )
        .await;
    let workflow = created["id"].as_str().unwrap().to_owned();
    let program = json!({
        "start": "refit",
        "steps": [
            {
                "name": "refit",
                "kind": {
                    "type": "action", "action": "fit_model",
                    "configuration": { "model": "Radon", "activate": "if_clean" }
                },
                "next": { "type": "step", "step": "write_back" }
            },
            {
                "name": "write_back",
                "kind": {
                    "type": "action", "action": "run_js_code",
                    "configuration": { "code": r#"
                        const m = await models.get("Radon");
                        const w = await m.writePosterior({
                            variable: "alpha", statistics: { mean: "alpha_mean", sd: "alpha_sd" } });
                        let predicted;
                        try { await m.predict({ id: 1 }); } catch (e) { predicted = e.message; }
                        return { written: w.written, table: w.table, fit: m.fit.id,
                                 refit: context.refit.instance, predicted };
                    "# }
                },
                "next": { "type": "end" }
            }
        ]
    });
    let saved = client
        .ok(
            "POST",
            &format!("/api/workflows/{workflow}"),
            Some(json!({ "workflow": program, "description": "refit, then write back" })),
        )
        .await;
    assert_eq!(saved["issues"], json!([]), "{saved}");

    client
        .ok(
            "POST",
            "/api/tables/refits/rows",
            Some(json!({ "note": "nightly" })),
        )
        .await;
    let mut run = Value::Null;
    for _ in 0..400 {
        let runs = client
            .ok("GET", &format!("/api/workflows/{workflow}/runs"), None)
            .await;
        if let Some(first) = runs.as_array().and_then(|r| r.first())
            && ["done", "failed", "aborted"].contains(&first["state"].as_str().unwrap_or(""))
        {
            let id = first["id"].as_str().unwrap().to_owned();
            run = client.ok("GET", &format!("/api/runs/{id}"), None).await;
            break;
        }
        tokio::time::sleep(Duration::from_millis(25)).await;
    }
    assert_eq!(run["state"], json!("done"), "{run}");
    let wrote = &run["context"]["context"]["write_back"];
    assert_eq!(wrote["written"], json!(3), "{run}");
    assert_eq!(wrote["table"], json!("counties"), "{run}");
    // The handle is on the fit the step before made active.
    assert_eq!(wrote["fit"], wrote["refit"], "{run}");
    assert!(
        wrote["predicted"]
            .as_str()
            .unwrap()
            .contains("`Radon` is a posterior")
            && wrote["predicted"]
                .as_str()
                .unwrap()
                .contains("`m.draws(…)`"),
        "{run}"
    );

    let mut counties = client.rows("counties").await;
    counties.sort_by_key(|r| r["id"].as_i64());
    for (k, county) in counties.iter().enumerate() {
        let mean = county["alpha_mean"].as_f64().unwrap();
        assert!((mean - (k + 1) as f64).abs() < 0.05, "{county}");
        assert!(county["alpha_sd"].as_f64().unwrap() > 0.0, "{county}");
    }
    // The target table's own trigger fired, once per county.
    let mut trail: Vec<String> = client
        .rows("audit")
        .await
        .iter()
        .map(|r| r["what"].as_str().unwrap().to_owned())
        .collect();
    trail.sort();
    assert_eq!(trail, ["Aitkin", "Anoka", "Becker"]);
    Ok(())
}

/// A write-back writes under the handle's authority: as the trigger by
/// default, and as the event's caller after `asUser()` — who, at role 40, may
/// not update `counties` (an admin-only table), so nothing is written.
#[tokio::test]
async fn a_callers_write_back_is_held_to_the_callers_own_rights() -> Result<()> {
    let mut server = setup().await?;
    let client = &mut server.client;
    let (_, fit) = fitted(client, radon("Radon", bound(), nulls_dropped())).await;
    let fit = fit["id"].as_str().unwrap().to_owned();
    client
        .ok(
            "POST",
            &format!("/api/model-instances/{fit}/activate"),
            None,
        )
        .await;
    audited(client).await;
    client
        .trigger(json!({
            "name": "write_back", "description": "", "when": "none", "channel": null,
            "only_if": null, "action": "run_js_code",
            "configuration": { "code": r#"
                const m = await models.get("Radon");
                const as = payload.as_user ? m.asUser() : m;
                try {
                    const w = await as.writePosterior({
                        variable: "alpha", statistics: { mean: "alpha_mean" } });
                    return { written: w.written };
                } catch (e) {
                    return { refused: e.message };
                }
            "# },
            "min_role": null, "enabled": true,
        }))
        .await;

    // Caused by a role-40 user.
    let caller = sc_catalog::CallerContext::new(
        40,
        Some(json!({
            "id": "6b1c2d64-3f3a-4a52-9a8b-0f4d2b7f1a11",
            "role": 40,
            "email": "ada@example.com",
        })),
    );
    let refused = server
        .dispatcher
        .run_trigger(
            &server.catalog,
            "write_back",
            json!({ "as_user": true }),
            Some(&caller),
        )
        .await?;
    let why = refused["refused"]
        .as_str()
        .unwrap_or_else(|| panic!("the caller's write-back was not refused: {refused}"));
    assert!(why.contains("counties"), "{why}");
    let client = &mut server.client;
    assert!(
        client
            .rows("counties")
            .await
            .iter()
            .all(|c| c["alpha_mean"].is_null()),
        "nothing was written"
    );
    assert!(client.rows("audit").await.is_empty());

    // The same body, for the same caller, under the trigger's own authority.
    let written = server
        .dispatcher
        .run_trigger(
            &server.catalog,
            "write_back",
            json!({ "as_user": false }),
            Some(&caller),
        )
        .await?;
    assert_eq!(written, json!({ "written": 3 }));
    assert_eq!(server.client.rows("audit").await.len(), 3);
    Ok(())
}

/// Percent-encode a query value.
fn urlencoding(value: &str) -> String {
    value
        .bytes()
        .map(|b| match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                (b as char).to_string()
            }
            _ => format!("%{b:02X}"),
        })
        .collect()
}
