//! Phase 6: the admin API for triggers, driven through the assembled router
//! against a real database (§10.2).
//!
//! The claim these endpoints make is not "a row was stored" but **"what the list
//! shows is what will fire"** — every save validates against the same registry
//! the dispatcher runs, and reloads the live set. So the round trip here does not
//! stop at reading the row back: it writes a row through the *other* admin
//! endpoint and asserts the trigger it just created fired.
//!
//! What else is pinned: a refusal names what is wrong and stores nothing; a
//! broken trigger stays listed with its reason (the badge the SPA renders is not
//! a guess); `runTrigger` returns the action's result, and an action that fails
//! comes back as an **error** rather than a 200 carrying a failure nobody reads;
//! `testRunTrigger` — the admin's Test run — answers **200 either way**, with
//! the failure as a value, with what a code body printed, and, for a trigger on
//! a table, run against a row of that table picked at random;
//! and `listActions` describes each action's settings, which is what lets the
//! trigger form render a configuration form for an action it has never heard of.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_action::TriggerDispatcher;
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

const SCHEMA: &str = "\
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text not null, pages bigint); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        title text, who text);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    async fn triggers(&mut self) -> Vec<Value> {
        let (status, body) = self.send("GET", "/api/triggers", None).await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }

    async fn rows(&mut self, table: &str) -> Vec<Value> {
        let (status, body) = self
            .send("GET", &format!("/api/tables/{table}/rows"), None)
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }
}

struct Server {
    client: Client,
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    _db: TestDb,
}

/// The body the SPA posts: every field of the input schema, so the test exercises
/// the contract rather than a convenient subset.
fn trigger_body(name: &str, when: &str, action: &str, configuration: Value) -> Value {
    json!({
        "name": name,
        "description": "",
        "when": when,
        "channel": Value::Null,
        "only_if": Value::Null,
        "action": action,
        "configuration": configuration,
        "min_role": Value::Null,
        "enabled": true,
    })
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let models = sc_server::install_models(&catalog, sc_model::DEFAULT_MAX_ROWS).await?;
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents, &models).await?;

    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server {
        client,
        catalog,
        dispatcher,
        _db: db,
    })
}

#[tokio::test]
async fn a_trigger_is_created_listed_updated_and_deleted_over_http() -> sc_error::Result<()> {
    let mut server = setup().await?;
    assert!(server.client.triggers().await.is_empty());

    // --- create -------------------------------------------------------------
    let mut body = trigger_body(
        "audit_books",
        "insert",
        "insert_row",
        json!({ "table": "audit", "values": { "title": "row.title", "who": "user.email" } }),
    );
    body["channel"] = json!("books");
    let (status, created) = server
        .client
        .send("POST", "/api/triggers", Some(body.clone()))
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let id = created["id"].as_str().expect("an id").to_owned();
    assert_eq!(created["name"], json!("audit_books"));
    assert_eq!(created["when"], json!("insert"));
    assert_eq!(created["channel"], json!("books"));
    assert_eq!(created["enabled"], json!(true));
    assert_eq!(created["error"], Value::Null);

    // --- listed, and *live*: the save reloaded the set, so it fires ---------
    let listed = server.client.triggers().await;
    assert_eq!(listed.len(), 1, "{listed:?}");
    assert_eq!(listed[0]["id"], json!(id));

    let (status, _) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Dune", "pages": 412 })),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED);
    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "the trigger fired: {audit:?}");
    assert_eq!(audit[0]["title"], json!("Dune"));
    assert_eq!(audit[0]["who"], json!(ADMIN));

    // --- update: a rename and a switch-off, and the set follows -------------
    body["name"] = json!("audit_books_renamed");
    body["enabled"] = json!(false);
    let (status, updated) = server
        .client
        .send("PUT", &format!("/api/triggers/{id}"), Some(body.clone()))
        .await;
    assert_eq!(status, StatusCode::OK, "{updated}");
    assert_eq!(updated["id"], json!(id), "the path's id, not the body's");
    assert_eq!(updated["name"], json!("audit_books_renamed"));
    assert_eq!(updated["enabled"], json!(false));

    let (status, _) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Emma", "pages": 300 })),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED);
    assert_eq!(
        server.client.rows("audit").await.len(),
        1,
        "a disabled trigger does not fire"
    );

    // --- delete -------------------------------------------------------------
    let (status, body) = server
        .client
        .send("DELETE", &format!("/api/triggers/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["deleted"], json!(true));
    assert!(server.client.triggers().await.is_empty());

    // Deleting it twice is a not-found, not a silent success.
    let (status, _) = server
        .client
        .send("DELETE", &format!("/api/triggers/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    Ok(())
}

#[tokio::test]
async fn a_refusal_names_what_is_wrong_and_stores_nothing() -> sc_error::Result<()> {
    let mut server = setup().await?;

    /// One refusal: the body, and the words the message must carry.
    type Case = (Value, &'static [&'static str]);
    let cases: Vec<Case> = vec![
        // An action nobody registered.
        (
            trigger_body("t", "insert", "no_such_action", json!({})),
            &["no_such_action"],
        ),
        // A table event with no table to listen to. (The action's own settings
        // are complete, so what is refused is the missing channel and not the
        // generic spec check that runs before it.)
        (
            trigger_body(
                "t",
                "insert",
                "insert_row",
                json!({ "table": "audit", "values": { "title": "\"x\"" } }),
            ),
            &["insert", "must name the table"],
        ),
        // An event kind that does not exist.
        (
            trigger_body("t", "whenever", "insert_row", json!({})),
            &["whenever"],
        ),
        // The action's own configuration check: a field the target table
        // does not have.
        (
            {
                let mut b = trigger_body(
                    "t",
                    "insert",
                    "insert_row",
                    json!({ "table": "audit", "values": { "nope": "row.title" } }),
                );
                b["channel"] = json!("books");
                b
            },
            &["nope"],
        ),
        // Out-of-range timing on a periodic trigger.
        (
            {
                let mut b = trigger_body(
                    "t",
                    "daily",
                    "insert_row",
                    json!({ "table": "audit", "values": { "title": "\"x\"" } }),
                );
                b["hour"] = json!(24);
                b
            },
            &["hour", "0 and 23"],
        ),
        // Timing on a kind that has none: refused rather than silently dropped,
        // because a setting an admin can see but the server ignores is worse
        // than one it refuses.
        (
            {
                let mut b = trigger_body(
                    "t",
                    "hourly",
                    "insert_row",
                    json!({ "table": "audit", "values": { "title": "\"x\"" } }),
                );
                b["hour"] = json!(3);
                b
            },
            &["hourly", "hour"],
        ),
        // …and the `only_if`, read in the event's scope.
        (
            {
                let mut b = trigger_body(
                    "t",
                    "insert",
                    "insert_row",
                    json!({ "table": "audit", "values": { "title": "row.title" } }),
                );
                b["channel"] = json!("books");
                b["only_if"] = json!("titel === 'x'");
                b
            },
            &["only if", "titel"],
        ),
    ];

    for (body, expected) in cases {
        let (status, response) = server
            .client
            .send("POST", "/api/triggers", Some(body.clone()))
            .await;
        // A refusal, and the client's to fix: 400 for an invalid value, 422 for
        // one the configuration model rejects (an event kind that does not
        // exist). Which of the two matters far less than the message.
        assert!(status.is_client_error(), "{body}: {status} {response}");
        let message = response["error"].as_str().unwrap_or_default();
        for fragment in expected {
            assert!(
                message.contains(fragment),
                "expected `{fragment}` in: {message}"
            );
        }
        // Nothing was stored: a refused save leaves the admin's list as it was.
        assert!(server.client.triggers().await.is_empty(), "{message}");
    }
    Ok(())
}

/// Phase 8: the periodic timing round-trips through the admin API, and
/// `last_run_at` travels the other way only.
#[tokio::test]
async fn a_periodic_triggers_timing_round_trips_and_its_last_run_is_read_only()
-> sc_error::Result<()> {
    let mut server = setup().await?;
    let mut body = trigger_body(
        "nightly",
        "weekly",
        "insert_row",
        json!({ "table": "audit", "values": { "title": "\"nightly\"" } }),
    );
    body["day_of_week"] = json!(6);
    body["hour"] = json!(3);
    body["minute"] = json!(30);
    // A client that tries to write the scheduler's record: accepted as a body,
    // ignored as a field. History is not something an edit gets to rewrite.
    body["last_run_at"] = json!("2020-01-01T00:00:00Z");

    let (status, created) = server
        .client
        .send("POST", "/api/triggers", Some(body.clone()))
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let id = created["id"].as_str().expect("an id").to_owned();
    assert_eq!(created["day_of_week"], json!(6));
    assert_eq!(created["hour"], json!(3));
    assert_eq!(created["minute"], json!(30));
    assert_eq!(created["last_run_at"], Value::Null);

    // Read back from storage, not echoed from the request.
    let listed = server.client.triggers().await;
    assert_eq!(listed[0]["when"], json!("weekly"));
    assert_eq!(listed[0]["day_of_week"], json!(6));
    assert_eq!(listed[0]["minute"], json!(30));
    assert_eq!(listed[0]["last_run_at"], Value::Null);

    // The scheduler records a run…
    let trigger_id = sc_action::TriggerId(uuid::Uuid::parse_str(&id).unwrap());
    let ran_at = chrono::DateTime::parse_from_rfc3339("2026-07-19T03:30:00Z")
        .unwrap()
        .with_timezone(&chrono::Utc);
    sc_action::record_trigger_run(&server.catalog, trigger_id, ran_at).await?;
    server.dispatcher.reload(&server.catalog).await?;
    let listed = server.client.triggers().await;
    assert!(
        listed[0]["last_run_at"]
            .as_str()
            .is_some_and(|t| t.starts_with("2026-07-19T03:30")),
        "{}",
        listed[0]
    );

    // …and an ordinary edit does not disturb it. This is why `last_run_at` is a
    // column the save path does not write: an admin changing the hour at 3pm
    // must not thereby tell the scheduler the job ran at 3pm, or never ran.
    body["hour"] = json!(4);
    let (status, updated) = server
        .client
        .send("PUT", &format!("/api/triggers/{id}"), Some(body))
        .await;
    assert_eq!(status, StatusCode::OK, "{updated}");
    assert_eq!(updated["hour"], json!(4));
    let listed = server.client.triggers().await;
    assert_eq!(listed[0]["hour"], json!(4));
    assert!(
        listed[0]["last_run_at"]
            .as_str()
            .is_some_and(|t| t.starts_with("2026-07-19T03:30")),
        "the edit must not have lost the last run: {}",
        listed[0]
    );
    Ok(())
}

#[tokio::test]
async fn a_trigger_that_stops_validating_stays_listed_with_its_reason() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let mut body = trigger_body(
        "audit_books",
        "insert",
        "insert_row",
        json!({ "table": "audit", "values": { "title": "row.title" } }),
    );
    body["channel"] = json!("books");
    let (status, created) = server
        .client
        .send("POST", "/api/triggers", Some(body))
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");

    // The world changes underneath it: the table it listens to is dropped.
    server
        ._db
        .client()
        .await?
        .batch_execute("DROP TABLE books")
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    server.catalog.reload().await?;
    server.dispatcher.reload(&server.catalog).await?;

    // Still listed, still editable, and carrying the reason — which is the only
    // thing that says what to fix. (A trigger that merely vanished from the list
    // would be a trigger nobody could repair.)
    let listed = server.client.triggers().await;
    assert_eq!(listed.len(), 1, "{listed:?}");
    let error = listed[0]["error"].as_str().unwrap_or_default();
    assert!(error.contains("books"), "{error}");
    Ok(())
}

#[tokio::test]
async fn run_returns_the_actions_result_and_reports_its_failures() -> sc_error::Result<()> {
    let mut server = setup().await?;

    let (status, created) = server
        .client
        .send(
            "POST",
            "/api/triggers",
            Some(trigger_body(
                "double",
                "none",
                "run_js_code",
                json!({ "code": "return { doubled: payload.n * 2, by: user.email };" }),
            )),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let id = created["id"].as_str().unwrap().to_owned();

    // The posted body is the event's payload and the action's result comes back.
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(json!({ "n": 21 })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["result"]["doubled"], json!(42));
    // The admin who pressed the button is the event's caller.
    assert_eq!(body["result"]["by"], json!(ADMIN));

    // An action that fails is an **error**, not a 200 with a hidden failure —
    // which is the whole point of a "test this now" button.
    let (status, created) = server
        .client
        .send(
            "POST",
            "/api/triggers",
            Some(trigger_body(
                "boom",
                "none",
                "run_js_code",
                json!({ "code": "throw new Error('the service is down');" }),
            )),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let boom = created["id"].as_str().unwrap().to_owned();
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{boom}/run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");
    let message = body["error"].as_str().unwrap_or_default();
    assert!(message.contains("the service is down"), "{message}");
    assert!(message.contains("boom"), "the trigger is named: {message}");

    // A trigger that is not there is a not-found, whatever the id looks like.
    let (status, _) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{}/run", uuid::Uuid::new_v4()),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    Ok(())
}

/// The admin's **Test run**: a 200 either way, with what the body printed.
#[tokio::test]
async fn a_test_run_answers_with_the_console_and_with_the_failure() -> sc_error::Result<()> {
    let mut server = setup().await?;

    let (status, created) = server
        .client
        .send(
            "POST",
            "/api/triggers",
            Some(trigger_body(
                "chatty",
                "none",
                "run_js_code",
                json!({
                    "code": "console.log('starting', { n: payload.n });\n\
                             console.error('nearly');\n\
                             return payload.n * 2;",
                }),
            )),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let id = created["id"].as_str().unwrap().to_owned();

    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/test-run"),
            Some(json!({ "n": 21 })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["ok"], json!(true));
    assert_eq!(body["result"], json!(42));
    // Every console method, in order, with its level — and the arguments
    // formatted by the guest, which is the only side that can tell an object
    // from a string.
    assert_eq!(body["console"][0]["level"], json!("log"));
    assert_eq!(body["console"][0]["text"], json!("starting {\"n\":21}"));
    assert_eq!(body["console"][1]["level"], json!("error"));
    assert_eq!(body["console"][1]["text"], json!("nearly"));
    // A `none` trigger has no row, and none is invented for it.
    assert_eq!(body["row"], Value::Null);

    // A failing action is a **200 carrying the failure**, not an error status:
    // the message is the answer, and what the body printed before it threw is
    // what explains it.
    let (status, created) = server
        .client
        .send(
            "POST",
            "/api/triggers",
            Some(trigger_body(
                "boom",
                "none",
                "run_js_code",
                json!({
                    "code": "console.log('about to fail');\n\
                             throw new Error('the service is down');",
                }),
            )),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let boom = created["id"].as_str().unwrap().to_owned();
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{boom}/test-run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["ok"], json!(false));
    let message = body["error"].as_str().unwrap_or_default();
    assert!(message.contains("the service is down"), "{message}");
    assert!(message.contains("boom"), "the trigger is named: {message}");
    assert_eq!(body["console"][0]["text"], json!("about to fail"));

    // A switched-off trigger is not run, however it is asked — and that, too,
    // is news rather than an error status.
    let (status, body) = server
        .client
        .send(
            "PUT",
            &format!("/api/triggers/{boom}"),
            Some({
                let mut off = trigger_body(
                    "boom",
                    "none",
                    "run_js_code",
                    json!({ "code": "return 1;" }),
                );
                off["enabled"] = json!(false);
                off
            }),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{boom}/test-run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["ok"], json!(false));
    assert!(
        body["error"]
            .as_str()
            .unwrap_or_default()
            .contains("disabled"),
        "{body}"
    );

    // A trigger that is not there is still a not-found: nothing ran, so there
    // is no outcome to carry.
    let (status, _) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{}/test-run", uuid::Uuid::new_v4()),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    Ok(())
}

/// A trigger on a table has no occurrence of its own when a person presses a
/// button, so the test run borrows one: a row of that table, picked at random,
/// bound to `row` — and to `old` as well on an update.
#[tokio::test]
async fn a_table_triggers_test_run_is_given_a_random_row() -> sc_error::Result<()> {
    let mut server = setup().await?;

    let (status, created) = server
        .client
        .send(
            "POST",
            "/api/triggers",
            Some({
                let mut body = trigger_body(
                    "on update",
                    "update",
                    "run_js_code",
                    json!({ "code": "return { title: row.title, same: old.title === row.title };" }),
                );
                body["channel"] = json!("books");
                body
            }),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{created}");
    let id = created["id"].as_str().unwrap().to_owned();

    // An empty table is not an error: the trigger still runs, with no row, and
    // the answer says which row it got — none.
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/test-run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["row"], Value::Null);

    for title in ["Dune", "Emma", "Ulysses"] {
        let (status, body) = server
            .client
            .send(
                "POST",
                "/api/tables/books/rows",
                Some(json!({ "title": title, "pages": 100 })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{body}");
    }

    // Now there are rows, and the run is given one of them — the same one it
    // reports, and the same one `old` sees.
    let mut seen = std::collections::HashSet::new();
    for _ in 0..12 {
        let (status, body) = server
            .client
            .send(
                "POST",
                &format!("/api/triggers/{id}/test-run"),
                Some(Value::Null),
            )
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        assert_eq!(body["ok"], json!(true), "{body}");
        let title = body["result"]["title"].as_str().unwrap().to_owned();
        assert_eq!(body["row"]["title"], json!(title), "the row is reported");
        assert_eq!(body["result"]["same"], json!(true), "`old` is bound too");
        seen.insert(title);
    }
    // Random, not "the first row" — twelve draws from three rows finding one
    // title would be a one-in-2.8-million coincidence.
    assert!(seen.len() > 1, "always the same row: {seen:?}");
    Ok(())
}

#[tokio::test]
async fn the_actions_describe_their_own_settings() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let (status, actions) = server.client.send("GET", "/api/actions", None).await;
    assert_eq!(status, StatusCode::OK, "{actions}");
    let actions = actions.as_array().cloned().unwrap_or_default();

    let names: Vec<&str> = actions.iter().filter_map(|a| a["name"].as_str()).collect();
    // `run_agent` is among them although it is not one of `sc-core-actions`'
    // built-ins (§11.5): a server registers it beside them from the assembled
    // agent services, and the trigger form must offer it like any other.
    assert_eq!(
        names,
        vec![
            "delete_rows",
            "fetch",
            // The one model action is registered beside `run_agent` and for
            // the same reason (Stan TODO 7.5): it needs the model provider
            // registry and the fits assembled first. There is no
            // `predict_row` and no `write_posterior` (milestone 31 §1).
            "fit_model",
            "insert_row",
            "run_agent",
            "run_js_code",
            "run_python_code",
            "send_email",
            "update_rows"
        ]
    );

    // Each one describes itself and its settings in the same `FormField`
    // vocabulary a framework and a file-store backend use — which is what lets
    // the trigger form render a configuration form for an action it has never
    // heard of.
    for action in &actions {
        assert!(
            !action["description"]
                .as_str()
                .unwrap_or_default()
                .is_empty(),
            "{action}"
        );
        let spec = action["config_spec"]
            .as_array()
            .cloned()
            .unwrap_or_default();
        assert!(!spec.is_empty(), "{action}");
        for field in &spec {
            assert!(field["name"].is_string(), "{field}");
            assert!(field["label"].is_string(), "{field}");
            assert!(field["type"].is_string(), "{field}");
            assert!(field["required"].is_boolean(), "{field}");
            assert!(field["options"].is_array(), "{field}");
        }
    }

    let fetch = actions
        .iter()
        .find(|a| a["name"] == json!("fetch"))
        .unwrap();
    let method = fetch["config_spec"]
        .as_array()
        .unwrap()
        .iter()
        .find(|f| f["name"] == json!("method"))
        .unwrap();
    // A setting that restricts its values says so, so the form renders a picker
    // rather than a free-text box.
    assert_eq!(method["options"][0], json!("POST"));
    assert_eq!(method["default"], json!("POST"));
    Ok(())
}

/// An action's declaration may depend on the **table** the trigger fires on:
/// `send_email` offers one attachment checkbox per File field of it. So the
/// endpoint takes the table, and the answer changes with it — which is what lets
/// the trigger form show those checkboxes while still knowing nothing about
/// attachments.
#[tokio::test]
async fn an_actions_settings_can_depend_on_the_triggers_table() -> sc_error::Result<()> {
    let mut server = setup().await?;

    // `books.cover` becomes a File field in a connected store — the arrangement
    // that puts a checkbox on the form.
    let dir = std::env::temp_dir().join(format!("sc-trigger-actions-{}", std::process::id()));
    std::fs::remove_dir_all(&dir).ok();
    std::fs::create_dir_all(&dir).unwrap();
    sc_catalog::bootstrap_file_stores(&server.catalog).await?;
    sc_catalog::bootstrap_field_meta(&server.catalog).await?;
    sc_catalog::save_file_store(
        &server.catalog,
        &sc_files::FileStoreDef::local("uploads", dir.to_string_lossy().as_ref()),
    )
    .await?;
    sc_catalog::connect_all_file_stores(&server.catalog).await?;
    server
        .catalog
        .create_field(
            "books",
            &sc_catalog::DataField::plain(
                "cover",
                sc_types::TypeRef::Basic(sc_types::BasicType::Text),
            ),
        )
        .await?;
    sc_catalog::save_field_meta(
        &server.catalog,
        &sc_catalog::FieldMeta::new("books", "cover").kind(sc_catalog::DataFieldKind::File {
            store: sc_catalog::FileStoreId("uploads".to_owned()),
            folder: None,
            mime_allow: Vec::new(),
        }),
    )
    .await?;

    let settings = |actions: &Value| -> Vec<String> {
        actions
            .as_array()
            .cloned()
            .unwrap_or_default()
            .iter()
            .find(|a| a["name"] == json!("send_email"))
            .and_then(|a| a["config_spec"].as_array().cloned())
            .unwrap_or_default()
            .iter()
            .filter_map(|f| f["name"].as_str().map(str::to_owned))
            .collect()
    };

    // With no table named, the table-independent declaration.
    let (status, actions) = server.client.send("GET", "/api/actions", None).await;
    assert_eq!(status, StatusCode::OK, "{actions}");
    assert!(!settings(&actions).iter().any(|n| n.starts_with("attach_")));

    // With the table, the checkbox for its File field.
    let (status, actions) = server
        .client
        .send("GET", "/api/actions?table=books", None)
        .await;
    assert_eq!(status, StatusCode::OK, "{actions}");
    assert!(
        settings(&actions).contains(&"attach_cover".to_owned()),
        "{actions}"
    );

    // A table with no File field is the table-independent answer again — the
    // checkboxes are the table's files, not a fixed extra setting.
    let (status, actions) = server
        .client
        .send("GET", "/api/actions?table=audit", None)
        .await;
    assert_eq!(status, StatusCode::OK, "{actions}");
    assert!(!settings(&actions).iter().any(|n| n.starts_with("attach_")));
    std::fs::remove_dir_all(&dir).ok();
    Ok(())
}
