//! Integration test for §2.3: the **server** creates a React application's
//! project, and what it creates builds and serves.
//!
//! The generator itself is pure and unit-tested in `sc-app`'s `scaffold::files`
//! module. What needs a database and a real tree is everything around it: the
//! project is generated against the app's *actual* tables (which come from the
//! catalog), written through the file store, refused when the directory is
//! occupied, and handed to `git init` when the store is not already a repo.
//!
//! **The real `npm install` + `vite build` is opt-in**, behind `SC_TEST_NPM=1`.
//! It is the only honest end-to-end proof that a scaffolded project builds — it
//! type-checks the generated hooks against the generated client — but it needs a
//! Node toolchain and a network, which the rest of the Rust suite deliberately
//! does not. Everything else here runs unconditionally.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, AppRequest, Application, ClientUpdate, CodeFramework, FrameworkRef,
    app_source_from_config, build_application, emit_app_runtime, save_application, scaffold_app,
    update_app_client,
};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-scaffold-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// A catalog over a real Postgres holding one `tasks` table — the app's data
/// model, and what the scaffold generates its pages and hooks against.
async fn catalog_with_tasks(db: &TestDb) -> sc_error::Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE tasks (\
               id bigint generated by default as identity primary key, \
               title text not null, \
               done boolean)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// The whole configuration of a React app: a store and a project name.
fn todo_app() -> Application {
    Application::new(
        "Todo",
        "todo",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "todo"),
    )
    .with_table(TableId("tasks".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn the_server_writes_a_complete_project_against_the_apps_own_tables() -> sc_error::Result<()>
{
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    // The roles a server has from its first boot, plus one this installation
    // invented: the generated documentation names them, because `feldspar auth
    // token --role NAME` takes a name and the project has no other way to know.
    sc_auth::bootstrap(&cat).await?;
    sc_auth::save_role(&cat, &sc_auth::Role::new(40, "Editor")).await?;
    let tmp = TempDir::new("write")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;
    // What the boot path does with `--base-domain`: the generated documentation
    // needs it to say where the application can be opened.
    cat.set_public_origin(sc_catalog::PublicOrigin::new("example.com", 3032));

    let report = scaffold_app(&cat, &todo_app(), None).await?;
    assert_eq!(report.project, "todo");

    // Everything `npm install && npm run build` needs, with no shell step: the
    // MVP tutorial's `npm create vite`, `npm install` and `git init` are all
    // gone from the admin's hands.
    let project = tmp.path().join("todo");
    for expected in [
        "package.json",
        "vite.config.ts",
        "tsconfig.json",
        "index.html",
        ".gitignore",
        "src/main.tsx",
        "src/App.tsx",
        "src/routes.tsx",
        "src/auth.tsx",
        "src/Login.tsx",
        "src/SetPassword.tsx",
        "src/app.css",
        "AGENTS.md",
        "CLAUDE.md",
        "src/feldspar/client.ts",
        "src/feldspar/helper.ts",
        "src/feldspar/hooks.ts",
        "src/feldspar/store.ts",
        "src/feldspar/messages.ts",
        "src/feldspar/i18n.tsx",
        "src/feldspar/schema.sql",
        "src/feldspar/README.md",
        "src/feldspar/SKILL.md",
    ] {
        assert!(project.join(expected).is_file(), "missing {expected}");
    }
    // 14 project files (`CLAUDE.md` importing `AGENTS.md`) + one page for the app's one table + the nine-file
    // runtime (the client, its helper, the hooks, the store, the two halves of
    // the message runtime, the schema, and the two documents — one for a
    // person, one for a coding agent).
    assert_eq!(report.files.len(), 24);

    // What a coding agent opening this project finds: a root file pointing at the
    // generated directory, and in it a README and a `schema.sql` describing the
    // app's real tables. The DDL is the *driver's* — the same text the database
    // was given — so it cannot drift from the columns that are actually there.
    let agents = std::fs::read_to_string(project.join("AGENTS.md"))?;
    assert!(agents.contains("src/feldspar/README.md"), "{agents}");
    assert!(agents.contains("`tasks`"), "{agents}");
    let schema = std::fs::read_to_string(project.join("src/feldspar/schema.sql"))?;
    assert!(schema.contains(r#"CREATE TABLE "tasks""#), "{schema}");
    assert!(schema.contains(r#""title" text NOT NULL"#), "{schema}");
    assert!(schema.contains(r#"PRIMARY KEY ("id")"#), "{schema}");
    // ...and beside that README, the map of the half of the application that is
    // *not* in this project (§13.6): the administration MCP tools, named from the
    // live surface rather than from prose, and the root file pointing at it.
    assert!(agents.contains("src/feldspar/SKILL.md"), "{agents}");
    let skill = std::fs::read_to_string(project.join("src/feldspar/SKILL.md"))?;
    assert!(skill.contains("- `edit_schema` — "), "{skill}");
    assert!(skill.contains("- `save_trigger` — "), "{skill}");
    assert!(skill.contains("- `buildApplication` — "), "{skill}");
    assert!(skill.contains("`client.ts`"), "{skill}");
    let readme = std::fs::read_to_string(project.join("src/feldspar/README.md"))?;
    assert!(readme.contains("feldspar api add-query"), "{readme}");
    assert!(readme.contains("--app todo"), "{readme}");
    assert!(readme.contains("--api /api"), "{readme}");

    // The catalog was told where this deployment serves (as `feldspar serve` and
    // the command-line build both do at boot), so both documents name the URL to
    // open rather than describing one — and the session command that gets a
    // browser past the sign-in page.
    assert!(agents.contains("http://todo.example.com:3032"), "{agents}");
    assert!(readme.contains("http://todo.example.com:3032"), "{readme}");
    assert!(
        agents.contains("feldspar auth token --app todo --admin"),
        "{agents}"
    );
    assert!(readme.contains("pkill -HUP feldspar"), "{readme}");
    // Both documents name this installation's roles — read out of the database
    // this scaffold ran against, not described in the abstract — and neither
    // asks for a password, because the command no longer takes one.
    for doc in [&agents, &readme] {
        assert!(
            doc.contains("Admin (1), Editor (40), Public (100)"),
            "{doc}"
        );
        assert!(!doc.contains("--password"), "{doc}");
        // The other thing that command needs is a base domain, and this process
        // was told one — so the documents give the command as it runs here,
        // without a paragraph about a setting the reader does not have to touch
        // or about the server's own configuration file.
        assert!(!doc.contains("--base-domain"), "{doc}");
        assert!(!doc.contains("feldspar.toml"), "{doc}");
    }
    // ...and the session file it writes is not committable.
    let ignore = std::fs::read_to_string(project.join(".gitignore"))?;
    assert!(ignore.contains(".feldspar-session.json"), "{ignore}");

    // Generated against the app's real table, not a placeholder: there is a page
    // for `tasks`, and the hooks carry its columns and their nullability.
    assert!(project.join("src/pages/Tasks.tsx").is_file());
    let hooks = std::fs::read_to_string(project.join("src/feldspar/hooks.ts"))?;
    assert!(hooks.contains("type TasksRow"), "{hooks}");
    assert!(hooks.contains("api.tasks.list()"), "{hooks}");
    // …and a store over the same table, so a write shows before it lands.
    let store = std::fs::read_to_string(project.join("src/feldspar/store.ts"))?;
    assert!(store.contains("export function useTasksStore()"), "{store}");

    // The client is generated at the conventional path the scaffold imports
    // from, so the two halves of the runtime meet without a setting. The row
    // type is the app's own columns, with their nullability.
    let client = std::fs::read_to_string(project.join("src/feldspar/client.ts"))?;
    assert!(client.contains("export interface TasksRow {"), "{client}");
    assert!(client.contains("title: string;"), "{client}");
    assert!(client.contains("done: boolean | null;"), "{client}");
    assert!(client.contains("tasks: TasksApi;"), "{client}");
    assert!(client.contains("/api/tasks"), "{client}");
    let routes = std::fs::read_to_string(project.join("src/routes.tsx"))?;
    assert!(routes.contains("./pages/Tasks"), "{routes}");

    // §13.3 expects an app's source to be a git repo; the store here is not one,
    // so the project became one. The MVP left this to the admin's shell.
    assert!(report.git_initialized);
    assert!(project.join(".git").exists());
    Ok(())
}

#[tokio::test]
async fn scaffolding_never_overwrites_an_occupied_directory() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("occupied")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // An admin's existing work — the case that must never be clobbered.
    let project = tmp.path().join("todo");
    std::fs::create_dir_all(project.join("src"))?;
    std::fs::write(project.join("src/App.tsx"), "// six months of work\n")?;

    let err = scaffold_app(&cat, &todo_app(), None)
        .await
        .expect_err("an occupied directory is refused")
        .to_string();
    assert!(err.contains("todo"), "should name the directory: {err}");
    assert!(err.contains("not empty"), "{err}");

    // And it is refused *before* anything is written: the file is byte-identical
    // and no scaffolded file appeared beside it.
    assert_eq!(
        std::fs::read_to_string(project.join("src/App.tsx"))?,
        "// six months of work\n"
    );
    assert!(!project.join("package.json").exists());
    Ok(())
}

/// A store dedicated to one application: the project directory is left blank and
/// the app *is* the store. This is the shape a git store cloned from the app's
/// own repository has — there is no sub-directory to name, and before §2.2 made
/// the setting optional there was no way to say so.
#[tokio::test]
async fn a_blank_project_directory_scaffolds_into_the_store_root() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("root")?;
    // An empty clone: the repository directory is there and nothing else. It must
    // not count as "occupied" — that would refuse exactly the case this is for.
    std::fs::create_dir_all(tmp.path().join(".git"))?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let mut app = todo_app();
    app.framework = FrameworkRef::new("react").with("store", "apps");

    let report = scaffold_app(&cat, &app, None).await?;
    assert_eq!(report.project, "");
    assert!(
        report.summary().contains("the store root"),
        "{}",
        report.summary()
    );

    // Every file landed at the root, with no leading slash and no directory named
    // after nothing.
    for expected in [
        "package.json",
        "index.html",
        "src/App.tsx",
        "src/pages/Tasks.tsx",
        "src/feldspar/client.ts",
        "src/feldspar/helper.ts",
        "src/feldspar/hooks.ts",
    ] {
        assert!(tmp.path().join(expected).is_file(), "missing {expected}");
    }
    assert!(report.files.contains(&"package.json".to_owned()));
    assert!(!report.files.iter().any(|f| f.starts_with('/')));

    // `npm` refuses a package with an empty name, so the blank directory borrows
    // the app's other machine-readable identity: its subdomain.
    let package = std::fs::read_to_string(tmp.path().join("package.json"))?;
    assert!(package.contains(r#""name": "todo""#), "{package}");

    // The store was already a repository, so no nested one was created inside it.
    assert!(!report.git_initialized);

    // And the build reads the same conventions back: source at the root, output
    // in `dist` beside it, the client where the scaffold imports it from.
    let source = app_source_from_config(&app.framework)?;
    assert_eq!(source.build.source_dir, "");
    assert_eq!(source.build.output_dir, "dist");
    assert_eq!(
        source.client_path.as_deref(),
        Some("src/feldspar/client.ts")
    );

    // A re-emit rewrites the generated directory in place, at the root.
    let written = emit_app_runtime(&cat, &app, &source, None).await?;
    assert_eq!(
        written,
        [
            "src/feldspar/hooks.ts",
            "src/feldspar/store.ts",
            "src/feldspar/i18n.tsx",
            "src/feldspar/README.md",
            "src/feldspar/client.ts",
            "src/feldspar/helper.ts",
            "src/feldspar/schema.sql",
            "src/feldspar/messages.ts",
            "src/feldspar/SKILL.md",
        ]
    );

    // Scaffolding again is refused, because now there *is* something to lose —
    // and the message says where rather than printing an empty directory name.
    let err = scaffold_app(&cat, &app, None)
        .await
        .expect_err("the root is no longer empty")
        .to_string();
    assert!(err.contains("the store root"), "{err}");
    assert!(err.contains("not empty"), "{err}");
    Ok(())
}

#[tokio::test]
async fn a_store_that_is_already_a_repo_does_not_get_a_nested_one() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("gitstore")?;
    // A store rooted at a git repo: the project lands *inside* it, so initialising
    // another repo in the sub-directory would leave the source tracked by a repo
    // nobody expects.
    std::fs::create_dir_all(tmp.path().join(".git"))?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let report = scaffold_app(&cat, &todo_app(), None).await?;
    assert!(!report.git_initialized);
    assert!(!tmp.path().join("todo/.git").exists());
    Ok(())
}

#[tokio::test]
async fn the_generated_runtime_is_rewritten_on_build_and_nothing_else_is() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("regen")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let mut app = todo_app();
    scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("todo");

    // The admin edits their own code — the half of the project that is theirs.
    let mine = "// my app\nexport default function App() { return null; }\n";
    std::fs::write(project.join("src/App.tsx"), mine)?;
    // Including the root `AGENTS.md`, which a coding agent appends to. It is
    // written once, at scaffold time, and a re-emit that clobbered it would
    // destroy exactly the notes it exists to accumulate (decision 9).
    let notes = "# Todo\n\nThe invoice totals are cents, not euros.\n";
    std::fs::write(project.join("AGENTS.md"), notes)?;

    // A table is added to the app later. The runtime is regenerated from the
    // app's endpoints, so the new table's hooks simply exist — this is what makes
    // generating the runtime better than shipping it as a package (§2.1).
    db.client()
        .await?
        .batch_execute("CREATE TABLE notes (id bigint generated by default as identity primary key, body text)")
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    cat.reload().await?;
    app.tables.push(TableId("notes".to_owned()));

    let source = app_source_from_config(&app.framework)?;
    let written = emit_app_runtime(&cat, &app, &source, None).await?;
    assert_eq!(
        written,
        [
            "todo/src/feldspar/hooks.ts",
            "todo/src/feldspar/store.ts",
            "todo/src/feldspar/i18n.tsx",
            "todo/src/feldspar/README.md",
            "todo/src/feldspar/client.ts",
            "todo/src/feldspar/helper.ts",
            "todo/src/feldspar/schema.sql",
            "todo/src/feldspar/messages.ts",
            "todo/src/feldspar/SKILL.md",
        ]
    );

    let hooks = std::fs::read_to_string(project.join("src/feldspar/hooks.ts"))?;
    assert!(hooks.contains("export function useNotes()"), "{hooks}");
    assert!(hooks.contains("type NotesRow"), "{hooks}");
    // The schema description follows the tables, for the same reason and on the
    // same schedule: an agent writing SQL against this project must not be
    // reading last week's columns.
    let schema = std::fs::read_to_string(project.join("src/feldspar/schema.sql"))?;
    assert!(schema.contains(r#"CREATE TABLE "notes""#), "{schema}");
    assert!(schema.contains(r#""body" text"#), "{schema}");
    // Everything outside `src/feldspar/` is untouched — including the page for
    // the new table, which is the admin's to add or not, and the notes in
    // `AGENTS.md`.
    assert_eq!(std::fs::read_to_string(project.join("src/App.tsx"))?, mine);
    assert_eq!(std::fs::read_to_string(project.join("AGENTS.md"))?, notes);
    assert!(!project.join("src/pages/Notes.tsx").exists());
    Ok(())
}

/// The admin screen's "update code" button (`updateApplicationClient`), at the
/// layer that decides what it does: rewrite the generated directory, or — when
/// the project directory is empty — scaffold a whole project into it.
#[tokio::test]
async fn the_update_button_rescaffolds_an_empty_directory_and_re_emits_a_populated_one()
-> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("update")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;
    let app = todo_app();
    let project = tmp.path().join("todo");

    // Nothing there yet: re-emitting would leave a `src/feldspar/` with no
    // project around it, which cannot build. So it scaffolds, and says so.
    let update = update_app_client(&cat, &app, None).await?;
    assert!(matches!(update, ClientUpdate::Scaffolded(_)), "{update:?}");
    assert!(
        update.summary().contains("scaffolded"),
        "{}",
        update.summary()
    );
    assert!(project.join("package.json").is_file());
    assert!(project.join("src/feldspar/README.md").is_file());

    // Now it is populated, so the same button regenerates and leaves the
    // developer's own files alone.
    let mine = "// mine\nexport default function App() { return null; }\n";
    std::fs::write(project.join("src/App.tsx"), mine)?;
    let update = update_app_client(&cat, &app, None).await?;
    let ClientUpdate::Regenerated(files) = &update else {
        panic!("a populated project is regenerated, not scaffolded: {update:?}");
    };
    assert_eq!(
        files,
        &[
            "todo/src/feldspar/hooks.ts",
            "todo/src/feldspar/store.ts",
            "todo/src/feldspar/i18n.tsx",
            "todo/src/feldspar/README.md",
            "todo/src/feldspar/client.ts",
            "todo/src/feldspar/helper.ts",
            "todo/src/feldspar/schema.sql",
            "todo/src/feldspar/messages.ts",
            "todo/src/feldspar/SKILL.md",
        ]
    );
    assert_eq!(std::fs::read_to_string(project.join("src/App.tsx"))?, mine);
    Ok(())
}

/// Scaffold → install → build → serve, with a real Node toolchain.
///
/// Opt-in (`SC_TEST_NPM=1`) because it needs `npm` and a network; it is slow and
/// would make the whole suite depend on both. What it buys, and nothing else
/// does: the generated hooks are **type-checked against the generated client**
/// (the project's build script is `tsc --noEmit && vite build`), so a drift
/// between what `sc-api` emits and what the scaffold calls fails here — including
/// the client method a **custom SQL query** produces, whose result type came from
/// Postgres describing the statement rather than from anything in this repository.
#[tokio::test]
async fn a_scaffolded_app_installs_builds_and_serves_end_to_end() -> sc_error::Result<()> {
    if std::env::var("SC_TEST_NPM").as_deref() != Ok("1") {
        eprintln!("skipping: set SC_TEST_NPM=1 to run the real npm build");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("e2e")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // Saved rather than used as built: saving is what **describes** the custom
    // query, so the stored app carries the columns Postgres reported and the
    // generated method is typed from them.
    sc_app::bootstrap(&cat).await?;
    let mut app = todo_app();
    app.apis = vec![ApiConfig::new("rest", "/api").with(
        "queries",
        serde_json::json!([{
            "name": "countTasks",
            "method": "GET",
            "path": "/reports/count",
            "min_role": 1,
            "code": "SELECT count(*) AS n FROM tasks WHERE title = :title",
            "params": [{ "name": "title", "type": "text", "required": true }],
        }]),
    )];
    let app = save_application(&cat, &app).await?;

    let report = scaffold_app(&cat, &app, None).await?;
    assert!(!report.files.is_empty());

    // A caller of that method, in the developer's own half of the project. It is
    // never rendered; `tsc --noEmit` type-checks every file in the project, which
    // is the point — a custom query whose generated method did not match this
    // call fails the build.
    std::fs::write(
        tmp.path().join("todo/src/reports.ts"),
        "import { api } from \"./feldspar/hooks\";\n\
         \n\
         export async function countTasks(title: string): Promise<number> {\n\
         \x20 const rows = await api.countTasks({ title });\n\
         \x20 return rows[0]?.n ?? 0;\n\
         }\n",
    )?;

    // No shell step between scaffolding and a served bundle: the build installs
    // the dependencies the scaffold declared, then runs the bundler.
    let source = app_source_from_config(&app.framework)?;
    let report = build_application(&cat, &app, &source, None).await?;
    assert!(report.installed, "the first build installs dependencies");
    assert!(tmp.path().join("todo/node_modules").is_dir());

    let fw = CodeFramework::new("react", report.bundle);
    let index = fw.serve(&AppRequest::get("/"));
    assert_eq!(index.status, 200);
    assert_eq!(index.content_type, "text/html; charset=utf-8");
    assert!(String::from_utf8_lossy(&index.body).contains("<div id=\"root\">"));
    // A client-routed deep link resolves to the entry point.
    assert_eq!(fw.serve(&AppRequest::get("/tasks/42")).status, 200);

    // A second build does not reinstall — the marker is on disk.
    let again = build_application(&cat, &app, &source, None).await?;
    assert!(!again.installed);
    Ok(())
}
