//! Phase 6 of the Python code adapter: **plugin modules**.
//!
//! The milestone's second half of the definition of done, and every one of these
//! tests runs it rather than a piece of it: a real distribution, `pip`-installed
//! from a directory into a real virtual environment, imported on the real
//! interpreter, and then asked for exactly what a server asks a module for — an
//! action fired by a trigger, a function reached from a body and from a formula,
//! and a table read, filtered and written through the catalog.
//!
//! The fixture is `tests/fixtures/sc_plugin_pkg`, which supplies one of each
//! thing a Python plugin can supply, plus one action named after a built-in
//! because "reported and not installed" is a rule that needs a plugin which
//! breaks it. Nothing here reaches PyPI: the fixture's PEP 517 backend builds
//! its wheel with `zipfile` and has no requirements, so pip's build isolation
//! has nothing to download.
//!
//! # Why these tests share one environment, and take a lock
//!
//! There is **one** interpreter in a process (§1) and one `sys.modules` in it,
//! and a load is a re-import (§11). Two of these tests running at once would
//! therefore reset each other's plugin state half way through — which is not a
//! bug in the runtime, it is what one interpreter means, and the honest way to
//! test around it is to run them one at a time. So the environment is built once
//! and every test holds a lock for its length.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_action::{
    ActionRegistry, EventKind, Trigger, TriggerDispatcher, bootstrap_triggers, save_trigger,
};
use sc_catalog::{
    CallerContext, Catalog, DataField, ProvidedTableDef, ProvidedWrites, TableMeta,
    TableProviderHost, TableProviderHosts, bootstrap_table_meta, prefetch_bindings,
    save_table_meta,
};
use sc_core_actions::{CodeSurfaces, builtin_actions};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{
    CodeAdapter, Formula, ModuleFnHost, ModuleFnHosts, SchemaShape, TableShape, value_to_json,
};
use sc_module::{
    LoadedModule, Module, ModuleLanguage, ModuleSource, bootstrap_modules, redacted_configuration,
    save_module,
};
use sc_python::pymodule::{
    PyModuleFunctions, PyModuleHost, PyModuleModelProviders, PyModuleSet, PyModuleTableProviders,
};
use sc_python::{PythonEnv, PythonEnvironment, PythonRuntime, PythonSource};
use sc_query::{
    Assignment, BinOp, Delete, Expr, Insert, Projection, Select, Source, Statement, Update, Value,
};
use sc_test_harness::TestDb;
use sc_types::{BasicType, TypeRef};
use serde_json::{Value as Json, json};

/// The distribution the fixture installs as, as pip and `_fd_modules` name it.
const PACKAGE: &str = "sc-plugin-fixture";
/// The table provider it supplies.
const PROVIDER: &str = "Fixture rows";

/// One table for the fixture's action to write into.
const SCHEMA: &str = "
    CREATE TABLE notes (id bigint generated by default as identity primary key,
        what text, who text);
";

/// Say why a test did nothing, and return, so a skip is visible under
/// `-- --nocapture` rather than looking like a pass.
macro_rules! skip_without {
    ($cond:expr, $why:expr) => {
        if !$cond {
            eprintln!("skipping: {}", $why);
            return Ok(());
        }
    };
}

/// A JSON object as the attribute map every stored configuration is.
fn configuration(value: Json) -> sc_types::Attrs {
    match value {
        Json::Object(map) => map,
        _ => sc_types::Attrs::new(),
    }
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/sc_plugin_pkg")
}

/// Whether this machine can build an environment at all.
async fn have_toolchain() -> bool {
    let bin = PathBuf::from(sc_python::DEFAULT_PYTHON_BIN);
    sc_python::have_python(&bin).await && sc_python::have_pip(&bin).await
}

/// The one environment these tests share, with the fixture installed in it.
///
/// Built once for the whole binary: a `pip install` costs seconds, and every
/// test here wants the same distribution in the same place. It is *not* removed
/// afterwards for the same reason it is shared — the interpreter has its
/// `site-packages` on `sys.path` for the life of the process.
static ENVIRONMENT: tokio::sync::OnceCell<PathBuf> = tokio::sync::OnceCell::const_new();

/// Held for the length of every test: one interpreter, one `sys.modules`, and a
/// load is a re-import.
static ONE_AT_A_TIME: tokio::sync::Mutex<()> = tokio::sync::Mutex::const_new(());

async fn shared_environment() -> &'static Path {
    ENVIRONMENT
        .get_or_init(|| async {
            let dir =
                std::env::temp_dir().join(format!("sc-python-modules-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&dir);
            let environment = environment_at(&dir);
            environment
                .install(PythonSource::Local, &fixture_dir().display().to_string())
                .await
                .expect("the fixture plugin installs");
            dir
        })
        .await
        .as_path()
}

fn environment_at(dir: &Path) -> PythonEnvironment {
    PythonEnvironment::new(
        &PythonEnv {
            dir: Some(dir.to_path_buf()),
            bin: None,
        },
        None,
    )
    .expect("an explicit --python-dir needs no default")
}

/// A runtime pointed at the shared environment, and a module host over it.
fn host(dir: &Path) -> Arc<PyModuleHost> {
    let python = Arc::new(PythonRuntime::new().with_env(PythonEnv {
        dir: Some(dir.to_path_buf()),
        bin: None,
    }));
    Arc::new(PyModuleHost::new(python))
}

/// The `_fd_modules` row an admin's install would have written.
async fn install_row(catalog: &Catalog, configuration: Json) -> Result<()> {
    bootstrap_modules(catalog).await?;
    let mut module = Module::new(
        PACKAGE,
        ModuleSource::Local,
        fixture_dir().display().to_string(),
    )
    .in_language(ModuleLanguage::Python);
    module.version = Some("0.2.0".to_owned());
    if let Json::Object(configuration) = configuration {
        module.configuration = configuration;
    }
    save_module(catalog, &module).await
}

/// Load every Python module in `catalog` into `registry`, over `host`.
async fn load_set(
    catalog: &Catalog,
    host: &Arc<PyModuleHost>,
    registry: &mut ActionRegistry,
) -> Result<Vec<LoadedModule>> {
    let surfaces = Arc::new(CodeSurfaces::new()?);
    Ok(PyModuleSet::load(catalog, host, &surfaces, registry)
        .await?
        .into_modules())
}

async fn catalog_of(db: &TestDb) -> Result<Arc<Catalog>> {
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Ok(Arc::new(
        Catalog::init(driver as Arc<dyn DatabaseDriver>).await?,
    ))
}

// ---------------------------------------------------------------------------
// 6.1, 6.2, 6.6 — the decorators, the manifest, and the reload
// ---------------------------------------------------------------------------

/// What the fixture declares, read the way a server reads it: through the
/// distribution's **entry point**, with `on_load` called and its settings
/// answered in this system's own field vocabulary.
#[tokio::test]
async fn a_plugin_declares_an_action_a_function_a_provider_and_its_own_settings() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let host = host(shared_environment().await);

    let manifest = host
        .load(PACKAGE, &json!({ "api_key": "secret", "greeting": "hi" }))
        .await?;

    // Nothing went wrong that the plugin could see. An `on_load` that failed, an
    // `async def` action, a package that declared nothing — all of those are
    // issues here rather than a load that failed, so an admin still gets the
    // settings form that is where they would fix it.
    assert!(manifest.issues.is_empty(), "{:?}", manifest.issues);
    assert_eq!(manifest.name, PACKAGE);
    // The package the declarations were made in, which is not the distribution's
    // name and not the module the entry point named.
    assert_eq!(manifest.plugin_name.as_deref(), Some("sc_plugin_fixture"));

    let actions: Vec<&str> = manifest.actions.iter().map(|a| a.name.as_str()).collect();
    assert_eq!(actions, ["fixture_note", "insert_row"]);
    let note = &manifest.actions[0];
    assert_eq!(note.description, "Note something about a row");
    assert_eq!(note.config_fields.len(), 1);
    assert_eq!(note.config_fields[0]["name"], json!("note"));
    assert_eq!(note.config_fields[0]["required"], json!(true));

    // The **signature**, read with `inspect` — the one place this API is better
    // than the JavaScript one rather than merely different.
    let shout = manifest
        .functions
        .iter()
        .find(|f| f.name == "fixture_shout")
        .expect("the fixture supplies it");
    assert_eq!(shout.description, "Shout a string");
    assert!(!shout.is_async);
    assert_eq!(shout.arguments.len(), 1);
    assert_eq!(shout.arguments[0].name, "text");
    assert_eq!(shout.arguments[0].type_name.as_deref(), Some("string"));
    let add = manifest
        .functions
        .iter()
        .find(|f| f.name == "fixture_add")
        .expect("the fixture supplies it");
    assert_eq!(
        add.arguments
            .iter()
            .map(|a| a.type_name.as_deref())
            .collect::<Vec<_>>(),
        [Some("int"), Some("int")]
    );

    assert_eq!(manifest.table_providers.len(), 1);
    assert_eq!(manifest.table_providers[0].name, PROVIDER);
    assert_eq!(
        manifest.table_providers[0].config_fields[0]["name"],
        json!("min_size")
    );

    // Its own settings, in **this system's** vocabulary: `secret` is a flag on
    // the declaration rather than a `fieldview: "password"` to be guessed at.
    let settings: Vec<&str> = manifest
        .config_fields
        .iter()
        .map(|f| f["name"].as_str().unwrap_or_default())
        .collect();
    assert_eq!(settings, ["api_key", "greeting"]);
    assert_eq!(manifest.config_fields[0]["secret"], json!(true));
    assert_eq!(manifest.config_fields[1]["default"], json!("hello"));

    // Nothing this version does not load: a Python plugin has no decorator for a
    // view or a type, so there is nothing to count as unsupported.
    assert!(manifest.unsupported.is_empty());
    Ok(())
}

/// §11: a load is a **re-import**, and `on_load` is called again with the new
/// configuration — which is how a settings change reaches the client a plugin
/// built at load time.
#[tokio::test]
async fn a_configuration_change_reloads_the_package_and_calls_on_load_again() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let host = host(shared_environment().await);

    host.load(PACKAGE, &json!({ "api_key": "one", "greeting": "first" }))
        .await?;
    let first = host.call(PACKAGE, "fixture_loaded", Vec::new()).await?;
    assert_eq!(first["greeting"], json!("first"));
    assert_eq!(first["loads"], json!(1), "`on_load` ran");

    // Loaded again with a different configuration. `on_load` saw the new one —
    // and `loads` is **1 again rather than 2**, which is the evidence that the
    // package was dropped from `sys.modules` and imported afresh: its own
    // module-level state did not survive, exactly as §11 says a reload behaves
    // for a pure-Python package.
    let manifest = host
        .load(PACKAGE, &json!({ "api_key": "two", "greeting": "second" }))
        .await?;
    assert!(manifest.issues.is_empty(), "{:?}", manifest.issues);
    let second = host.call(PACKAGE, "fixture_loaded", Vec::new()).await?;
    assert_eq!(second["greeting"], json!("second"));
    assert_eq!(second["loads"], json!(1), "the package was imported again");
    Ok(())
}

/// §2: the five surfaces are bound **for the duration of a call**, and a call
/// that was lent none says so at the call site.
///
/// A function and a table provider are lent none — the first is hoisted into a
/// formula and the second is called from inside a query, and neither has a
/// caller's authority to lend — so the fixture's action reaching `sc.db` outside
/// a trigger is refused rather than quietly writing as the admin.
#[tokio::test]
async fn a_module_call_that_was_lent_no_surfaces_is_refused_at_the_call_site() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let host = host(shared_environment().await);
    host.load(PACKAGE, &json!({ "api_key": "one" })).await?;

    let refused = host
        .run(PACKAGE, "fixture_note", args("a note"), Default::default())
        .await
        .expect_err("no surfaces were lent")
        .to_string();
    assert!(refused.contains("database access"), "{refused}");
    // And the frames are the **plugin's own**, not fifteen of runtime: the file
    // that made the call, and the line in it.
    assert!(refused.contains("plugin.py"), "{refused}");
    Ok(())
}

/// The arguments a trigger would pass, for the calls that make them by hand.
fn args(note: &str) -> Json {
    json!({
        "row": { "who": "ada" },
        "old": null,
        "table": "notes",
        "user": null,
        "payload": null,
        "config": { "note": note },
        "trigger": "note it",
        "mode": "insert",
    })
}

// ---------------------------------------------------------------------------
// 6.3, 6.5 — the action, fired by a trigger, over the five surfaces
// ---------------------------------------------------------------------------

/// The milestone's own sentence: a Python plugin's action appears in the trigger
/// form with its own settings, fires on an event, and reaches `db`.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_python_modules_action_fires_from_a_trigger_and_writes_through_db() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let dir = shared_environment().await;

    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let catalog = catalog_of(&db).await?;
    bootstrap_triggers(&catalog).await?;
    install_row(&catalog, json!({ "api_key": "sk-live", "greeting": "hi" })).await?;

    let host = host(dir);
    let mut registry = builtin_actions()?;
    let loaded = load_set(&catalog, &host, &mut registry).await?;
    assert_eq!(loaded.len(), 1);
    let module = &loaded[0];

    // Its action is in the registry the dispatcher runs from, with the settings
    // the plugin declared — translated into the same `FormField`s every other
    // configurable thing here uses, so the trigger form renders it with no code
    // that knows what a Python module is.
    let action = registry.get("fixture_note").expect("registered");
    let spec = action.config_spec();
    assert_eq!(spec.len(), 1);
    assert_eq!(spec[0].name(), "note");
    assert!(spec[0].required);

    // And the one that claims a built-in's name is **reported and not
    // installed**: `insert_row` is still the built-in.
    assert_eq!(
        module.issues.len(),
        1,
        "only the collision is wrong: {:?}",
        module.issues
    );
    assert!(
        module.issues[0].contains("insert_row"),
        "{:?}",
        module.issues
    );
    assert_eq!(registry.get("insert_row").unwrap().description(), {
        let builtins = builtin_actions()?;
        builtins.get("insert_row").unwrap().description().to_owned()
    });

    // Now fire it, exactly as an admin's Run button would.
    let registry = Arc::new(registry);
    let dispatcher = Arc::new(
        TriggerDispatcher::new(Arc::clone(&registry))
            .with_adapter(Arc::new(PythonRuntime::new()) as Arc<dyn CodeAdapter>),
    );
    let trigger = Trigger::new("note it", EventKind::None, "fixture_note").config("note", "chased");
    save_trigger(&catalog, &registry, &trigger).await?;
    dispatcher.reload(&catalog).await?;

    let caller = CallerContext::new(1, Some(json!({ "email": "ada@example.com" })));
    let result = dispatcher
        .run_trigger(&catalog, "note it", json!({ "who": "ada" }), Some(&caller))
        .await?;

    // What the plugin returned: its own configured setting, the **module's**
    // settings which no trigger can change, and the count it read back through
    // the same `db` it wrote with.
    assert_eq!(result["noted"], json!("chased"));
    assert_eq!(result["greeting"], json!("hi"));
    assert_eq!(result["key"], json!("sk-live"));
    assert_eq!(result["trigger"], json!("note it"));
    assert_eq!(result["notes"], json!(1));

    // And the row is really there, written through the row layer.
    let rows = db
        .client()
        .await?
        .query("SELECT what FROM notes", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].get::<_, String>(0), "chased");

    // The settings form the Modules tab renders: the secret is **redacted** on
    // the way out, and submitting the sentinel back keeps what is stored.
    let redacted = redacted_configuration(module);
    assert_ne!(redacted["api_key"], json!("sk-live"));
    assert_eq!(redacted["greeting"], json!("hi"));
    let merged =
        sc_types::merge_secrets(&module.config_spec, &module.module.configuration, &redacted);
    assert_eq!(merged["api_key"], json!("sk-live"));
    Ok(())
}

// ---------------------------------------------------------------------------
// 6.4, 6.5 — the function, from a body and from a formula
// ---------------------------------------------------------------------------

/// A module function reached both ways it can be reached, through the
/// **composite** host — so what is asserted is also §8's merge: neither caller
/// knows there are two languages of module.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_python_modules_function_is_called_from_a_body_and_from_a_formula() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let dir = shared_environment().await;

    let db = TestDb::new().await?;
    let catalog = catalog_of(&db).await?;
    bootstrap_triggers(&catalog).await?;
    bootstrap_table_meta(&catalog).await?;
    catalog
        .create_table(
            "article",
            &[DataField::plain("notes", TypeRef::Basic(BasicType::Text))],
        )
        .await?;
    install_row(&catalog, json!({ "api_key": "k" })).await?;

    let host = host(dir);
    let mut registry = builtin_actions()?;
    let loaded = load_set(&catalog, &host, &mut registry).await?;
    let functions = Arc::new(PyModuleFunctions::new(&host, &loaded));
    assert_eq!(functions.functions().len(), 3);
    // Through the composite of §8, which is what a server installs: one host
    // over both languages, routed by the module a plan names.
    catalog.set_module_functions(Arc::new(ModuleFnHosts::new(vec![
        Arc::clone(&functions) as Arc<dyn ModuleFnHost>
    ])))?;

    // --- from a formula, hoisted ------------------------------------------
    let shape = SchemaShape::new()
        .table(
            "article",
            TableShape::new()
                .field("id")
                .field("notes")
                .primary_key("id"),
        )
        .module_function("fixture_shout", PACKAGE);
    let formula = Formula::parse("fixture_shout(notes)").unwrap();
    let analysis = formula.validate(&shape, "article").unwrap();
    let table = catalog.require("article")?;
    let mut values: BTreeMap<String, Value> =
        BTreeMap::from([("notes".to_owned(), Value::Text("hello".to_owned()))]);
    prefetch_bindings(&catalog, &table, &analysis, &shape, &mut values).await?;
    assert_eq!(
        values.get("fixture_shout(notes)").map(value_to_json),
        Some(Json::String("HELLO!".to_owned()))
    );

    // --- from a code body, through `modfn` --------------------------------
    let registry = Arc::new(registry);
    let dispatcher = Arc::new(
        TriggerDispatcher::new(Arc::clone(&registry))
            .with_adapter(Arc::new(PythonRuntime::new()) as Arc<dyn CodeAdapter>),
    );
    let trigger = Trigger::new("shout", EventKind::None, "run_python_code").config(
        "code",
        r#"
return {
    "short": modfn.fixture_shout(payload["what"]),
    "named": modfn("sc-plugin-fixture").fixture_add(2, 3),
    "known": sorted(f["name"] for f in modfn.functions),
}
"#,
    );
    save_trigger(&catalog, &registry, &trigger).await?;
    dispatcher.reload(&catalog).await?;
    let result = dispatcher
        .run_trigger(&catalog, "shout", json!({ "what": "quiet" }), None)
        .await?;
    assert_eq!(result["short"], json!("QUIET!"));
    assert_eq!(result["named"], json!(5));
    assert_eq!(
        result["known"],
        json!(["fixture_add", "fixture_loaded", "fixture_shout"])
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// 6.4 — the table provider, through a real provided table
// ---------------------------------------------------------------------------

/// A table whose `_fd_tables` row names a Python provider: its columns are the
/// plugin's answer, its rows are read and filtered through the ordinary query
/// path, and all three writes work because the class defines all three methods.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_table_backed_by_a_python_provider_is_read_filtered_and_written() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let dir = shared_environment().await;

    let db = TestDb::new().await?;
    let catalog = catalog_of(&db).await?;
    bootstrap_table_meta(&catalog).await?;
    install_row(&catalog, json!({ "api_key": "k" })).await?;

    let host = host(dir);
    let mut registry = ActionRegistry::new();
    let loaded = load_set(&catalog, &host, &mut registry).await?;
    let providers = Arc::new(PyModuleTableProviders::new(&host, &loaded));
    assert_eq!(providers.providers().len(), 1);
    assert_eq!(providers.providers()[0].config_spec[0].name(), "min_size");
    // The composite again: one provider host over both languages.
    catalog.set_table_providers(Arc::new(TableProviderHosts::new(vec![
        Arc::clone(&providers) as Arc<dyn TableProviderHost>,
    ])))?;

    // The row that *is* the table.
    let mut meta = TableMeta::new("fixtures").label("Fixtures");
    meta.set_provider(Some(
        &ProvidedTableDef::new(PACKAGE, PROVIDER)
            .configuration(configuration(json!({ "min_size": 0 }))),
    ));
    save_table_meta(&catalog, &meta).await?;

    let table = catalog.require("fixtures")?;
    assert!(
        catalog.provided_table_issues().is_empty(),
        "{:?}",
        catalog.provided_table_issues()
    );
    // Its columns are what `fields(configuration)` answered, including which of
    // them is the key — without one, no write could name a row.
    let columns: Vec<&str> = table.fields.iter().map(|f| f.base.name.as_str()).collect();
    assert_eq!(columns, ["id", "name", "size"]);
    assert_eq!(table.primary_key, ["id"]);
    // And it is writable, because the class defines all three write methods.
    assert_eq!(table.provided_writes(), ProvidedWrites::ALL);

    let provider = catalog.provider(&table)?;

    // --- read, filtered ----------------------------------------------------
    let mut select = Select::from(Source::table("fixtures"));
    select.filter = Some(Expr::binary(BinOp::Gt, Expr::col("size"), Expr::lit(5_i64)));
    let rows: Vec<_> = provider.query(&select).await?.try_collect().await?;
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].get("name"), Some(&Value::Text("beta".into())));

    // --- insert ------------------------------------------------------------
    let insert = Insert::row(
        "fixtures",
        vec!["name".to_owned(), "size".to_owned()],
        vec![Expr::lit("gamma"), Expr::lit(9_i64)],
    )
    .returning(vec![Projection::all()]);
    let rows: Vec<_> = provider
        .write(&Statement::from(insert))
        .await?
        .try_collect()
        .await?;
    assert_eq!(rows.len(), 1);
    // The key the plugin assigned, which nothing here sent.
    assert_eq!(rows[0].get("id"), Some(&Value::Int(3)));

    // --- update ------------------------------------------------------------
    let update = Update {
        table: "fixtures".to_owned(),
        assignments: vec![Assignment::new("name", Expr::lit("edited"))],
        filter: Some(Expr::col("id").eq(Expr::lit(1_i64))),
        returning: vec![Projection::all()],
    };
    let rows: Vec<_> = provider
        .write(&Statement::from(update))
        .await?
        .try_collect()
        .await?;
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].get("name"), Some(&Value::Text("edited".into())));

    // --- delete ------------------------------------------------------------
    let delete = Delete {
        table: "fixtures".to_owned(),
        filter: Some(Expr::col("id").eq(Expr::lit(2_i64))),
        returning: vec![Projection::all()],
    };
    let rows: Vec<_> = provider
        .write(&Statement::from(delete))
        .await?
        .try_collect()
        .await?;
    assert_eq!(rows.len(), 1);

    // What is left, read again through the whole path.
    let rows: Vec<_> = provider
        .query(&Select::from(Source::table("fixtures")))
        .await?
        .try_collect()
        .await?;
    let names: Vec<String> = rows
        .iter()
        .filter_map(|row| match row.get("name") {
            Some(Value::Text(name)) => Some(name.clone()),
            _ => None,
        })
        .collect();
    assert_eq!(names, ["edited", "gamma"]);
    Ok(())
}

// ---------------------------------------------------------------------------
// 7.2 — the model provider, over a columnar frame
// ---------------------------------------------------------------------------

/// `@sc.model_provider` in the fixture's `plugin.py`, read into the manifest and
/// then fitted and predicted with — the Python half of the seam `sc-module`
/// implements for the other language.
///
/// The two providers are arithmetic rather than machine learning on purpose:
/// this fixture is installed with no network, and what is under test is the
/// seam. The real thing is `plugins/sklearn`, in `bundled_sklearn.rs`.
#[tokio::test]
async fn a_python_model_provider_declares_itself_and_then_fits_and_predicts() -> Result<()> {
    let _guard = ONE_AT_A_TIME.lock().await;
    skip_without!(
        have_toolchain().await,
        "python3 with pip is not on the PATH"
    );
    skip_without!(
        cfg!(feature = "python-host"),
        "built without an interpreter"
    );
    let dir = shared_environment().await;

    let db = TestDb::new().await?;
    let catalog = catalog_of(&db).await?;
    install_row(&catalog, json!({ "api_key": "k" })).await?;

    let host = host(dir);
    let mut registry = ActionRegistry::new();
    let loaded = load_set(&catalog, &host, &mut registry).await?;
    let providers: Arc<dyn sc_model::ModelProviderHost> =
        Arc::new(PyModuleModelProviders::new(&host, &loaded));

    // The declaration crossed whole: the module it came from, the label picker
    // as a *query* over the dataset's numeric columns rather than an empty
    // option list, the hyperparameter, and the standardisation request.
    let mut kinds = providers.providers();
    kinds.sort_by(|a, b| a.name.cmp(&b.name));
    let names: Vec<&str> = kinds.iter().map(|k| k.name.as_str()).collect();
    assert_eq!(names, ["fixture_mean", "fixture_sign"]);
    assert_eq!(kinds[0].module.as_deref(), Some(PACKAGE));
    assert_eq!(kinds[0].description, "Predict the mean of the label");
    assert_eq!(
        kinds[0].config_spec[0].query(),
        Some(sc_model::NUMERIC_COLUMNS_QUERY)
    );
    assert_eq!(kinds[0].hyperparameters[0].name(), "shift");
    assert!(!kinds[0].standardise);
    assert!(kinds[1].standardise);

    // Through the registry, because that is how a fit reaches one.
    let mut models = sc_model::ModelRegistry::new();
    models.register_host(Arc::clone(&providers))?;

    let frame = sc_model::Frame::new(
        vec![
            (
                "area".to_owned(),
                sc_model::Column::Float(vec![Some(-2.0), Some(-1.0), Some(1.0), Some(3.0)]),
            ),
            (
                "price".to_owned(),
                sc_model::Column::Float(vec![Some(10.0), Some(20.0), Some(30.0), Some(40.0)]),
            ),
        ],
        Vec::new(),
    )?;

    let mean = models.require("fixture_mean")?;
    let fitted = mean
        .fit(
            &frame,
            &attrs_of(json!({ "label": "price" })),
            &attrs_of(json!({ "shift": 5 })),
        )
        .await?;
    // The hyperparameter arrived as a number: 25 + 5.
    assert_eq!(fitted.state["mean"].as_f64(), Some(30.0));
    assert_eq!(
        fitted.parameters[0],
        sc_model::ParameterBlock::scalar("Mean", 25.0)
    );
    match &fitted.parameters[1] {
        sc_model::ParameterBlock::Table { name, rows, .. } => {
            assert_eq!(name, "Rows seen");
            assert_eq!(rows[0].cells, vec![json!("price"), json!(4)]);
        }
        other => panic!("expected a table, got {other:?}"),
    }
    assert_eq!(
        mean.predict(&fitted.state, &frame).await?,
        vec![sc_model::Prediction::number(30.0); 4]
    );
    // A clean fit reports nothing.
    assert!(fitted.warnings.is_empty(), "{:?}", fitted.warnings);

    // A provider warns in its answer, and with `warnings.warn`, which the host
    // catches during `fit`.
    let warned = mean
        .fit(
            &frame,
            &attrs_of(json!({ "label": "price", "note": "only four rows: add more" })),
            &attrs_of(json!({ "shift": -1 })),
        )
        .await?;
    assert_eq!(
        warned.warnings,
        vec![
            "only four rows: add more".to_owned(),
            "UserWarning: a negative shift predicts below every mean".to_owned(),
        ]
    );

    // And the tagged direction: a cluster number is not a number a regression
    // predicts, so it crosses written out in full.
    let sign = models.require("fixture_sign")?;
    let fitted = sign
        .fit(
            &frame,
            &attrs_of(json!({ "on": "area" })),
            &sc_types::Attrs::new(),
        )
        .await?;
    assert_eq!(
        fitted.parameters[0],
        sc_model::ParameterBlock::text("Rule", "negative is 0, otherwise 1")
    );
    assert_eq!(
        sign.predict(&fitted.state, &frame).await?,
        vec![
            sc_model::Prediction::Cluster { cluster: 0 },
            sc_model::Prediction::Cluster { cluster: 0 },
            sc_model::Prediction::Cluster { cluster: 1 },
            sc_model::Prediction::Cluster { cluster: 1 },
        ]
    );
    Ok(())
}

/// The attributes of a JSON object, for a configuration written inline.
fn attrs_of(value: Json) -> sc_types::Attrs {
    value.as_object().expect("an object").clone()
}
