//! TypeScript consumer generation (design §13.1).
//!
//! [`generate_client`] turns an [`EndpointSet`] into a single TypeScript module
//! containing (a) request/response **type declarations** for every endpoint,
//! (b) a **row interface per table** the set carries a
//! [`ResourceModel`](crate::ResourceModel) for, and (c) a typed **API-consumer
//! client** — an `ApiClient` interface plus a `createClient` factory that calls
//! the endpoints over `fetch`. Both the admin UI and every code-framework
//! application get a type-checked client generated this way, so the client
//! cannot drift from the server contract.
//!
//! **A table is one object, not four methods.** An endpoint set that knows which
//! tables are behind it emits `api.tasks.list()` / `.create()` / `.update()` /
//! `.delete()` over a generated `TasksRow`, rather than `listTasks()` … returning
//! `unknown`. Endpoints with no table behind them — the app's own auth, exposed
//! triggers, custom SQL queries — stay loose methods, because that is what they
//! are.
//!
//! **A `select` is typed by the compiler.** `?select=title,author(name)` changes
//! the shape of what comes back, so `list`'s return type is computed *from the
//! select string* (see the `Selected<…>` types this emits). That is why there is
//! one `list` and not one method for rows and another for embeds: the string the
//! caller writes is the one the type is read from.
//!
//! The output is deterministic (endpoints in registration order) and is valid
//! strict-mode TypeScript: the factory's implementation is contextually typed by
//! the `ApiClient` interface, so a mismatch between a declared endpoint and the
//! generated call is a compile error — which is what the type-check test asserts.

use crate::endpoint::{Endpoint, EndpointSet, PathSegment};
use crate::resource::{ResourceField, ResourceModel};
use crate::schema::TypeSchema;
use std::collections::HashSet;
use std::fmt::Write;

/// The file the generic half of a generated client lives in, beside the
/// `client.ts` that imports it.
///
/// Public because every emitter writes the pair: the scaffold's runtime
/// directory, an app's configured client path, and the two checked-in admin
/// clients all put this next to the client they generate.
pub const CLIENT_HELPER_FILE: &str = "helper.ts";

/// The generic half of a generated client: how a request is made, how a failure
/// is reported, and the types a table's reads are expressed in.
///
/// It is the *same text* for every application — nothing in it depends on an
/// endpoint or a table — so it is a file of its own rather than a hundred lines
/// of preamble in front of the part that is actually about this application.
/// [`generate_client`] imports from it by the name [`CLIENT_HELPER_FILE`].
pub fn client_helper() -> String {
    let mut out = String::new();
    out.push_str("// Code generated by sc-api. DO NOT EDIT.\n");
    out.push_str("// Regenerate with the sc-api TypeScript generator (design §13.1).\n");
    out.push_str(
        "//\n\
         // The half of a generated client that is the same in every application. \
         `client.ts`\n\
         // beside it is the half that is this one's: its endpoints, its tables and \
         their\n\
         // rows.\n\n",
    );
    out.push_str(REQUEST_HELPERS_HEAD);
    // The double-submit CSRF check every mutating request must satisfy (§16).
    // The session cookie is what authenticates a browser client, so the server
    // refuses a state-changing request that does not echo the non-`HttpOnly`
    // CSRF cookie in the header — including `login` itself, which is a POST like
    // any other. Emitting it here rather than leaving it to each consumer is the
    // point: a client generated from the server's own endpoint set should be able
    // to call the server it was generated from.
    //
    // Where there is no `document` — a React Native app on a phone, a node
    // script — there is no cookie to read either, so the token is the one the
    // server last sent in its `x-csrf-token` **response header** (every response
    // carries it; see `sc-server`'s `security` module). `trackCsrf` wraps the
    // client's `fetch` to remember it, so the first request a native app makes —
    // its `whoami` at startup, or even a refused `login` — arms the next one.
    let _ = write!(
        out,
        r#"/** The CSRF token the server last named in a response, for a client that
 * cannot read the cookie. */
let rememberedCsrf: string | undefined;

function csrfToken(): string | undefined {{
  if (typeof document !== "undefined") {{
    for (const part of document.cookie.split(";")) {{
      const [name, ...rest] = part.trim().split("=");
      if (name === "{cookie}") return decodeURIComponent(rest.join("="));
    }}
  }}
  return rememberedCsrf;
}}

/** `fetchImpl`, remembering the CSRF token each response names — how a client
 * with no `document.cookie` learns what its next write must echo.
 *
 * A write refused `403` with a token it did not send is sent **once more** with
 * that token: a native app reopened while still signed in has its session but
 * not the token it remembered, and its first write is how it finds out. */
export function trackCsrf(fetchImpl: typeof fetch): typeof fetch {{
  return (async (input: Parameters<typeof fetch>[0], init?: Parameters<typeof fetch>[1]) => {{
    const res = await fetchImpl(input, init);
    const token = res.headers.get("{header}");
    if (token) rememberedCsrf = token;
    const sent = new Headers(init?.headers).get("{header}");
    if (res.status === 403 && token && token !== sent) {{
      const headers = new Headers(init?.headers);
      headers.set("{header}", token);
      return fetchImpl(input, {{ ...init, headers }});
    }}
    return res;
  }}) as typeof fetch;
}}

/** The headers a request carries: its content type, its CSRF token, and — where
 * there is no `document`, i.e. a native app — that it is not a browser, so the
 * server lets its login outlive the app being closed. */
export function requestHeaders(method: string, hasBody: boolean): Record<string, string> {{
  const headers: Record<string, string> = {{}};
  if (hasBody) headers["content-type"] = "application/json";
  if (typeof document === "undefined") headers["{client_header}"] = "{native}";
  if (method !== "GET" && method !== "HEAD") {{
    const token = csrfToken();
    if (token) headers["{header}"] = token;
  }}
  return headers;
}}

"#,
        cookie = crate::auth::CSRF_COOKIE,
        header = crate::auth::CSRF_HEADER,
        client_header = crate::auth::CLIENT_KIND_HEADER,
        native = crate::auth::NATIVE_CLIENT,
    );
    out.push_str(READ_TYPES);
    out.push_str(LIVE_TYPES);
    out
}

/// One stream an application exposes to its pages (TODO "Streams" §10, TODO.md
/// "Live updates"), as the client generator needs it: what it is called, where
/// the live socket is, and what an element's `value` looks like.
///
/// A plain value rather than a `sc_stream::Stream`, and deliberately: this
/// crate types an endpoint set, and what it needs from a stream is a name, a
/// path and a shape. The caller that *has* streams — `sc-app`, which resolves
/// the app's declared subset against the stored rows and the provider registry
/// — translates the element type into a [`TypeSchema`] on the way in, which is
/// the same vocabulary every other generated type is written in.
#[derive(Debug, Clone, PartialEq)]
pub struct StreamExport {
    /// The stream's name — what it is subscribed to by, and what its accessor
    /// `live.{name}` is called.
    pub name: String,
    /// The live socket's path on this application, e.g. `/api/live` — the same
    /// for every stream of an application, which holds one socket for all of
    /// them.
    pub path: String,
    /// The shape of the envelope's `value`, from the stream's element type.
    pub value: TypeSchema,
}

/// Generate a TypeScript client module from an endpoint set.
///
/// The module imports the generic half of itself from [`CLIENT_HELPER_FILE`],
/// which [`client_helper`] emits and every caller writes beside this one.
pub fn generate_client(set: &EndpointSet) -> String {
    generate_client_with_streams(set, &[])
}

/// [`generate_client`] plus `live.{name}` per stream the application exposes
/// (TODO.md "Live updates" §6).
///
/// The socket is **beside** the endpoint set rather than in it: an
/// [`Endpoint`] is a typed request/response pair and a subscription has no
/// shape in that model — the same split the IDE's language server and the admin
/// chat already made. The streams are in the same generated module because that
/// is where the element type earns its keep: an app that declares a stream of
/// `{ temperature: float }` gets a callback whose argument is typed, checked by
/// the same compiler that checks its reads. Every accessor shares the client's
/// one [`LiveConnection`](LIVE_TYPES), so a page that watches three streams
/// holds one socket.
pub fn generate_client_with_streams(set: &EndpointSet, streams: &[StreamExport]) -> String {
    let mut out = String::new();

    out.push_str("// Code generated by sc-api. DO NOT EDIT.\n");
    out.push_str("// Regenerate with the sc-api TypeScript generator (design §13.1).\n\n");

    // The endpoints a table speaks for: those appear as that table's own
    // methods, so they get neither a loose method nor per-endpoint types.
    let owned: HashSet<&str> = set
        .resources()
        .flat_map(ResourceModel::endpoint_names)
        .collect();
    let loose: Vec<&Endpoint> = set
        .iter()
        .filter(|e| !owned.contains(e.name.as_str()))
        .collect();
    let tables = table_clients(set, &loose);

    // --- what this client borrows from the helper ---------------------------
    // Exactly what it goes on to name, and nothing more: an import of a helper
    // this client has no use for is a `noUnusedLocals` failure in generated
    // code, about generated code, in somebody else's project.
    let mut values: Vec<&str> = Vec::new();
    if !set.is_empty() {
        values.extend(["clientError", "requestHeaders", "trackCsrf"]);
    }
    if !streams.is_empty() {
        values.extend(["LiveConnection", "liveUrl"]);
    }
    let mut types: Vec<&str> = vec!["ClientOptions"];
    if !streams.is_empty() {
        types.push("LiveStream");
    }
    if !tables.is_empty() {
        types.push("Selected");
        if tables
            .iter()
            .any(|t| t.model.ops.create.is_some() || t.model.ops.update.is_some())
        {
            types.push("Insertable");
        }
        if tables.iter().any(|t| t.model.ops.delete.is_some()) {
            types.push("Deleted");
        }
        if tables.iter().any(|t| !t.model.ops.files.is_empty()) {
            types.push("FileApi");
        }
        for (param, name) in [("filter", "Filters"), ("order", "Order")] {
            if tables.iter().any(|t| t.declares_query_param(set, param)) {
                types.push(name);
            }
        }
    }
    types.sort_unstable();
    let borrowed: Vec<String> = values
        .into_iter()
        .map(str::to_owned)
        .chain(types.into_iter().map(|t| format!("type {t}")))
        .collect();
    let _ = writeln!(
        out,
        "import {{ {} }} from \"./{}\";\n",
        borrowed.join(", "),
        CLIENT_HELPER_FILE.trim_end_matches(".ts")
    );
    // Re-exported so a consumer has one module to import from: the vocabulary a
    // caller writes a read in belongs to the client they are calling, whichever
    // file it is declared in.
    out.push_str("export type { ClientOptions } from \"./helper\";\n");
    if !streams.is_empty() {
        out.push_str(
            "export { LiveConnection } from \"./helper\";\n\
             export type { LiveError, LiveHandlers, LiveOptions, LiveReady, LiveStatus, LiveStream, \
             LiveSubscription } from \"./helper\";\n",
        );
    }
    if !tables.is_empty() {
        out.push_str(
            "export type { Deleted, FileApi, FilterOp, FilterValue, Filters, Insertable, Order, \
             OrderKey, Selected, TableSchema } from \"./helper\";\n",
        );
    }
    out.push('\n');

    // --- per-endpoint request/response type declarations --------------------
    // Binary bodies get no named type: the client speaks `BodyInit` (upload) and
    // `Blob` (download) directly, which are the platform's own names for them.
    for ep in &loose {
        let pascal = to_pascal_case(&ep.name);
        if !ep.query.is_empty() {
            let _ = writeln!(out, "export type {pascal}Query = {};", query_type(ep));
        }
        if !ep.input.is_empty() && !ep.binary_input {
            let _ = writeln!(out, "export type {pascal}Request = {};", ts_type(&ep.input));
        }
        if !ep.output.is_empty() && !ep.binary_output {
            let _ = writeln!(
                out,
                "export type {pascal}Response = {};",
                ts_type(&ep.output)
            );
        }
    }
    out.push('\n');

    // --- the exposed streams: one envelope type each ------------------------
    // The §4 envelope, field for field, with `value` typed from this stream's
    // element type. It is a wire contract, so it is written out rather than
    // referred to: the same JSON the Observe screen renders and a trigger's
    // `only_if` reads.
    for stream in streams {
        let _ = writeln!(
            out,
            "/** One element of the `{}` stream, in its envelope. */\n\
             export type {}Envelope = {{\n\
             \x20 stream: string;\n\
             \x20 /** The topic it was published on, for a stream with topics. */\n\
             \x20 topic?: string;\n\
             \x20 value: {};\n\
             \x20 /** When *this server* saw it — not a claim about when it was produced. */\n\
             \x20 received_at: string;\n\
             \x20 /** The provider's own metadata (MQTT's topic, QoS, retain), absent when it has none. */\n\
             \x20 source?: unknown;\n\
             }};\n",
            stream.name,
            to_pascal_case(&stream.name),
            element_value_type(&stream.value),
        );
    }
    if !streams.is_empty() {
        out.push_str("/** The streams this application exposes, one accessor each. */\n");
        out.push_str("export interface LiveStreams {\n");
        for stream in streams {
            let _ = writeln!(
                out,
                "  /** The `{}` stream. */\n  readonly {}: LiveStream<{}Envelope>;",
                stream.name,
                stream.name,
                to_pascal_case(&stream.name),
            );
        }
        out.push_str("}\n\n");
    }

    // --- the tables: a row type and an object of methods each ---------------
    for table in &tables {
        out.push_str(&table.types(set));
    }

    // --- ApiClient interface ------------------------------------------------
    out.push_str("export interface ApiClient {\n");
    for ep in &loose {
        let _ = writeln!(out, "  {};", method_signature(ep));
    }
    for table in &tables {
        let _ = writeln!(out, "  /** The `{}` table. */", table.model.name);
        let _ = writeln!(out, "  {}: {}Api;", table.property, table.pascal);
    }
    if !streams.is_empty() {
        out.push_str(
            "  /** The streams this application exposes, over one live socket opened on first use. */\n\
             \x20 live: LiveStreams;\n",
        );
    }
    out.push_str("}\n\n");

    // An application that enables no API provider has an empty endpoint set, and
    // a client with nothing to call: the factory is still there, so the code
    // importing it still compiles, and it returns nothing because there is
    // nothing to return.
    if set.is_empty() && streams.is_empty() {
        out.push_str(
            "export function createClient(_options: ClientOptions = {}): ApiClient {\n             \x20 // This application enables no API provider, so it has no endpoints.\n             \x20 return {};\n             }\n",
        );
        return out;
    }

    out.push_str("export function createClient(options: ClientOptions = {}): ApiClient {\n");
    out.push_str("  const baseUrl = options.baseUrl ?? \"\";\n");
    // An application that exposes only streams never calls `fetch`, and an
    // unused binding is a `noUnusedLocals` error in somebody else's project.
    if !set.is_empty() {
        out.push_str("  const doFetch = trackCsrf(options.fetch ?? fetch);\n");
    }
    // One connection for every stream, opened on the first `subscribe`: a page
    // that never subscribes never connects.
    if let Some(stream) = streams.first() {
        let _ = writeln!(
            out,
            "  const connection = new LiveConnection(liveUrl(baseUrl, \"{}\"), options.live);",
            stream.path,
        );
    }
    // Each table is bound to a name before the client is assembled, so `get` can
    // call `list` without going through `this` — a generated method's `this` is
    // whatever the caller destructured it onto, which is nothing worth relying on.
    for table in &tables {
        out.push_str(&table.implementation(set));
    }
    out.push_str("  return {\n");
    for ep in &loose {
        emit_method_impl(&mut out, ep);
    }
    for table in &tables {
        let _ = writeln!(out, "    {},", table.property);
    }
    // A stream's name is letters, digits and `_`, never starting with a digit
    // (`check_stream_name`), so it is a property name as it stands.
    if !streams.is_empty() {
        out.push_str("    live: {\n");
        for stream in streams {
            let _ = writeln!(
                out,
                "      {}: connection.stream<{}Envelope>(\"{}\"),",
                stream.name,
                to_pascal_case(&stream.name),
                stream.name,
            );
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");

    out
}

/// The `ApiClient` interface signature for one endpoint, e.g.
/// `listRows(table: string): Promise<ListRowsResponse>`.
fn method_signature(ep: &Endpoint) -> String {
    let pascal = to_pascal_case(&ep.name);
    let mut params: Vec<String> = ep
        .path
        .params()
        .map(|(name, ty)| format!("{name}: {}", ty.ts_type()))
        .collect();
    if ep.binary_input {
        // An upload takes whatever `fetch` can send raw: a `Blob`/`File` from an
        // `<input type=file>`, an `ArrayBuffer`, a string.
        params.push("body: BodyInit".to_owned());
    } else if !ep.input.is_empty() {
        params.push(format!("body: {pascal}Request"));
    }
    // The query parameters arrive as one options object, last — and the argument
    // itself is optional when every parameter in it is, so declaring a `select`
    // nobody has to pass does not put an empty `{}` at every call site.
    if !ep.query.is_empty() {
        let opt = if query_arg_optional(ep) { "?" } else { "" };
        params.push(format!("{QUERY_ARG}{opt}: {pascal}Query"));
    }
    let ret = if ep.binary_output {
        "Blob".to_owned()
    } else if ep.output.is_empty() {
        "void".to_owned()
    } else {
        format!("{pascal}Response")
    };
    format!("{}({}): Promise<{ret}>", ep.name, params.join(", "))
}

/// Emit the factory's implementation of one endpoint method.
fn emit_method_impl(out: &mut String, ep: &Endpoint) {
    let pascal = to_pascal_case(&ep.name);
    let mut param_names: Vec<String> = ep.path.params().map(|(n, _)| n.to_owned()).collect();
    let has_body = ep.binary_input || !ep.input.is_empty();
    if has_body {
        param_names.push("body".to_owned());
    }
    if !ep.query.is_empty() {
        param_names.push(QUERY_ARG.to_owned());
    }

    let _ = writeln!(out, "    async {}({}) {{", ep.name, param_names.join(", "));
    let result = if ep.binary_output {
        Returns::Blob
    } else if ep.output.is_empty() {
        Returns::Nothing
    } else {
        Returns::Json(format!("{pascal}Response"))
    };
    emit_request(out, ep, &Request::new(&result));
    out.push_str("    },\n");
}

/// What a generated method does with the response body.
enum Returns {
    /// Read it as JSON and assert it is this type.
    Json(String),
    /// Read it as bytes.
    Blob,
    /// Read nothing.
    Nothing,
}

/// How one generated method calls its endpoint: what it does with the answer,
/// what it sends as the body, and how far in the statements are indented (a
/// table's file column nests one object deeper than everything else).
struct Request<'a> {
    result: &'a Returns,
    /// The expression the request body is taken from.
    body: &'a str,
    /// The indentation of the method's statements, in spaces.
    indent: usize,
}

impl<'a> Request<'a> {
    /// A call from a method of the returned client object: body in `body`,
    /// statements six spaces in.
    fn new(result: &'a Returns) -> Request<'a> {
        Request {
            result,
            body: "body",
            indent: 6,
        }
    }

    /// The same call, sending `body` and indented `indent` spaces.
    fn from(mut self, body: &'a str, indent: usize) -> Request<'a> {
        self.body = body;
        self.indent = indent;
        self
    }
}

/// Emit a method's body: query encoding, the `fetch` call, the error check and
/// the return. Shared by loose endpoint methods and a table's own, which differ
/// only in the signature above them and the type asserted below.
fn emit_request(out: &mut String, ep: &Endpoint, req: &Request<'_>) {
    let pad = " ".repeat(req.indent);
    emit_query_encoding(out, ep, &pad);
    let suffix = if ep.query.is_empty() {
        ""
    } else {
        // Nested template literal: the `?` disappears with the last parameter,
        // so an all-optional options object that was left empty produces exactly
        // the URL the endpoint had before it declared any.
        "${qs ? `?${qs}` : \"\"}"
    };
    let _ = writeln!(
        out,
        "{pad}const res = await doFetch(`${{baseUrl}}{}{suffix}`, {{",
        url_template(ep)
    );
    let _ = writeln!(out, "{pad}  method: \"{}\",", ep.method.as_str());
    let has_body = ep.binary_input || !ep.input.is_empty();
    // A binary body goes out as-is with no JSON content type — `fetch` derives
    // one from a `Blob` itself — so `hasBody` is false for the header helper
    // (which only decides the JSON content type; CSRF rides on the method).
    let _ = writeln!(
        out,
        "{pad}  headers: requestHeaders(\"{}\", {}),",
        ep.method.as_str(),
        has_body && !ep.binary_input
    );
    if ep.binary_input && req.body == "body" {
        // The parameter is already called `body`, which is the property's name.
        let _ = writeln!(out, "{pad}  body,");
    } else if ep.binary_input {
        let _ = writeln!(out, "{pad}  body: {},", req.body);
    } else if has_body {
        let _ = writeln!(out, "{pad}  body: JSON.stringify({}),", req.body);
    }
    let _ = writeln!(out, "{pad}}});");
    let _ = writeln!(
        out,
        "{pad}if (!res.ok) throw await clientError(\"{}\", res);",
        ep.name
    );
    match req.result {
        Returns::Blob => {
            let _ = writeln!(out, "{pad}return await res.blob();");
        }
        Returns::Nothing => {
            let _ = writeln!(out, "{pad}return;");
        }
        Returns::Json(ty) => {
            let _ = writeln!(out, "{pad}return (await res.json()) as {ty};");
        }
    }
}

/// Emit the `URLSearchParams` construction for an endpoint's query parameters.
///
/// Encoding is `URLSearchParams`'s, not a hand-rolled concatenation: a filter
/// value legitimately contains `&`, `=`, `+` and spaces (`title=eq.rock & roll`),
/// and a client that pasted those into the URL would send a *different* query
/// than the caller wrote. A repeated parameter appends once per element, which
/// is what makes `?published=gte.…&published=lt.…` expressible at all.
fn emit_query_encoding(out: &mut String, ep: &Endpoint, pad: &str) {
    if ep.query.is_empty() {
        return;
    }
    // When the whole options object is optional the caller may have omitted it,
    // so every read goes through `?.`.
    let base = if query_arg_optional(ep) {
        format!("{QUERY_ARG}?.")
    } else {
        format!("{QUERY_ARG}.")
    };
    let _ = writeln!(out, "{pad}const search = new URLSearchParams();");
    for p in &ep.query {
        let name = &p.name;
        if p.map {
            // The caller's own keys, each becoming a pair of its own — a filter
            // map is `?published=gte.2020-01-01`, not `?filter=…`.
            let _ = writeln!(
                out,
                "{pad}for (const [key, value] of Object.entries({base}{name} ?? {{}})) \
                 search.append(key, String(value));"
            );
        } else if p.repeated {
            let _ = writeln!(
                out,
                "{pad}for (const value of {base}{name} ?? []) search.append(\"{name}\", String(value));"
            );
        } else if p.required {
            // A required parameter implies the options object is required too,
            // so `base` is a plain `.` here and the value is always there.
            let _ = writeln!(out, "{pad}search.append(\"{name}\", String({base}{name}));");
        } else {
            // `null` as well as `undefined`: a caller threading a nullable value
            // through means "no value", and `String(null)` would send "null".
            let _ = writeln!(
                out,
                "{pad}if ({base}{name} !== undefined && {base}{name} !== null) \
                 search.append(\"{name}\", String({base}{name}));"
            );
        }
    }
    let _ = writeln!(out, "{pad}const qs = search.toString();");
}

/// The TypeScript type of an endpoint's query options object.
fn query_type(ep: &Endpoint) -> String {
    let members: Vec<String> = ep
        .query
        .iter()
        .map(|p| {
            let ty = if p.map {
                format!("Record<string, {}>", p.ty.ts_type())
            } else if p.repeated {
                format!("Array<{}>", p.ty.ts_type())
            } else {
                p.ty.ts_type().to_owned()
            };
            let opt = if p.required { "" } else { "?" };
            format!("{}{opt}: {ty}", p.name)
        })
        .collect();
    format!("{{ {} }}", members.join("; "))
}

/// Whether the options argument itself may be omitted — true when no query
/// parameter is required.
fn query_arg_optional(ep: &Endpoint) -> bool {
    !ep.query.iter().any(|p| p.required)
}

/// The name of the generated methods' query-options argument.
const QUERY_ARG: &str = "query";

/// The request URL as a JS template-literal body (path params interpolated and
/// escaped), e.g. `/api/tables/${encodeURIComponent(table)}/rows/${encodeURIComponent(id)}`.
///
/// Escaped because a name is free text: an agent called `Admin copilot`, or a
/// view with a `#` or `/` in it, must arrive as one segment. The server decodes
/// every path parameter before a handler sees it.
fn url_template(ep: &Endpoint) -> String {
    let mut out = String::from("/");
    for (i, seg) in ep.path.segments.iter().enumerate() {
        if i > 0 {
            out.push('/');
        }
        match seg {
            PathSegment::Literal(s) => out.push_str(s),
            PathSegment::Param { name, .. } => {
                let _ = write!(out, "${{encodeURIComponent({name})}}");
            }
        }
    }
    out
}

/// Render a [`TypeSchema`] as an inline TypeScript type.
fn ts_type(schema: &TypeSchema) -> String {
    match schema {
        TypeSchema::Value(v) => v.ts_type().to_owned(),
        TypeSchema::Struct(fields) if fields.is_empty() => "Record<string, never>".to_owned(),
        TypeSchema::Struct(fields) => {
            let members: Vec<String> = fields
                .iter()
                .map(|f| match &f.schema {
                    // An optional field is both `?`-optional and `| null`.
                    TypeSchema::Optional(inner) => {
                        format!("{}?: {} | null", f.name, ts_type(inner))
                    }
                    other => format!("{}: {}", f.name, ts_type(other)),
                })
                .collect();
            format!("{{ {} }}", members.join("; "))
        }
        TypeSchema::Array(inner) => format!("Array<{}>", ts_type(inner)),
        TypeSchema::Optional(inner) => format!("{} | null", ts_type(inner)),
    }
}

/// The TypeScript for an element's `value` — [`ts_type`], but a declared key
/// that may be null is `name: T | null` rather than `name?: T | null`.
///
/// The difference is §4's promise and it is worth the eight lines: **a declared
/// key that is absent is `null`**, so an element of a stream that declared five
/// keys has five keys. `?` would say the property might not be there, which is
/// true of a request body's optional field and false of every element that ever
/// arrives here — and it would make every consumer write `?? null` for a case
/// the server has already ruled out.
fn element_value_type(schema: &TypeSchema) -> String {
    match schema {
        TypeSchema::Struct(fields) if !fields.is_empty() => {
            let members: Vec<String> = fields
                .iter()
                .map(|f| format!("{}: {}", f.name, ts_type(&f.schema)))
                .collect();
            format!("{{ {} }}", members.join("; "))
        }
        other => ts_type(other),
    }
}

/// Convert a `camelCase` operation name to `PascalCase` for type names.
fn to_pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// --- tables -----------------------------------------------------------------

/// One table's place in the generated client: the model it comes from, the
/// property it hangs off `ApiClient` under, and the prefix its types are named
/// with.
struct TableClient<'a> {
    model: &'a ResourceModel,
    /// The `ApiClient` property, e.g. `tasks`.
    property: String,
    /// The type-name prefix, e.g. `Tasks` in `TasksRow`.
    pascal: String,
}

/// The property a table hangs off the generated client under — `api.tasks` for
/// `tasks` — or `None` when the set has no such table.
///
/// Public because generated code has to *call* the client: `sc-app`'s React
/// runtime writes hooks over `api.tasks.list()`, and a second copy of the naming
/// rule there would be free to disagree with the client it is calling.
pub fn client_property(set: &EndpointSet, table: &str) -> Option<String> {
    let owned: HashSet<&str> = set
        .resources()
        .flat_map(ResourceModel::endpoint_names)
        .collect();
    let loose: Vec<&Endpoint> = set
        .iter()
        .filter(|e| !owned.contains(e.name.as_str()))
        .collect();
    table_clients(set, &loose)
        .into_iter()
        .find(|t| t.model.name == table)
        .map(|t| t.property)
}

/// The tables of a set, with their client property names resolved.
///
/// A table is reached under its own name (`api.tasks`), which can collide with a
/// loose method — an application may well have a table called `login`, and §13.4
/// projects an endpoint of that name for every app. The table yields, taking a
/// `Table` suffix: the collision is between a name the *server* fixed and one
/// the admin chose, and renaming the endpoint would break every other app.
fn table_clients<'a>(set: &'a EndpointSet, loose: &[&Endpoint]) -> Vec<TableClient<'a>> {
    let taken: HashSet<&str> = loose.iter().map(|e| e.name.as_str()).collect();
    set.resources()
        .map(|model| {
            let pascal = crate::rest::op_name("", &model.name);
            let mut property = model.name.clone();
            if taken.contains(property.as_str()) || !is_identifier(&property) {
                property = format!("{}Table", lower_first(&pascal));
            }
            TableClient {
                model,
                property,
                pascal,
            }
        })
        .collect()
}

impl TableClient<'_> {
    /// The row, write-body, schema, query and API types for this table.
    fn types(&self, set: &EndpointSet) -> String {
        let name = &self.model.name;
        let p = &self.pascal;
        let mut out = format!("// --- {name} ---\n\n");

        let _ = writeln!(out, "/** A row of `{name}`, as its columns are today. */");
        let _ = writeln!(out, "export interface {p}Row {{");
        for f in &self.model.fields {
            let _ = writeln!(out, "  {}: {};", f.name, row_field_type(f));
        }
        out.push_str("}\n\n");

        if self.model.ops.create.is_some() || self.model.ops.update.is_some() {
            // Derived from the row rather than written out again: an insert
            // holds the same columns with the same types, and differs only in
            // which of them the *caller* has to supply. Saying that as two key
            // lists says it once — a column renamed in the row is renamed here,
            // and the two cannot describe different tables.
            let _ = writeln!(
                out,
                "/**\n \
                 * What an insert into `{name}` may say. The columns named here must be\n \
                 * given; the rest may be left out, because the database has something to\n \
                 * fall back on{read_only_note}.\n \
                 */",
                read_only_note = match self.read_only_keys().is_empty() {
                    true => String::new(),
                    false => ". The last list is the calculated columns, which no write may \
                              set"
                    .to_owned(),
                }
            );
            let required = key_union(&self.required_keys());
            let read_only = self.read_only_keys();
            let args = match read_only.is_empty() {
                true => format!("{p}Row, {required}"),
                false => format!("{p}Row, {required}, {}", key_union(&read_only)),
            };
            let _ = writeln!(out, "export type {p}Insert = Insertable<{args}>;\n");
            let _ = writeln!(out, "/** What an update of `{name}` may change. */");
            let _ = writeln!(out, "export type {p}Update = Partial<{p}Insert>;\n");
        }

        // The vocabulary a `select` is read against: this table's row, and the
        // tables its keys point at — recursively, so an embed of an embed types.
        let rels: Vec<String> = self
            .model
            .fields
            .iter()
            .filter_map(|f| {
                let target = f.references.as_deref()?;
                let target = set.resource(target)?;
                Some(format!(
                    "{}: {}Schema",
                    f.name,
                    crate::rest::op_name("", &target.name)
                ))
            })
            .collect();
        let _ = writeln!(
            out,
            "/** `{name}` and the tables its keys point at — what a `select` is read against. */"
        );
        let rels = match rels.is_empty() {
            true => "{}".to_owned(),
            false => format!("{{ {} }}", rels.join("; ")),
        };
        let _ = writeln!(
            out,
            "export type {p}Schema = {{ row: {p}Row; rels: {rels} }};\n"
        );

        let _ = writeln!(
            out,
            "/** What a read of `{name}` with the `select` `S` answers with. */"
        );
        let _ = writeln!(
            out,
            "export type {p}Selected<S extends string = \"\"> = Selected<{p}Schema, S>;\n"
        );

        if let Some(list) = self.list_endpoint(set) {
            let _ = writeln!(out, "/** What a read of `{name}` may say about itself. */");
            let _ = writeln!(out, "export type {p}Query<S extends string = \"\"> = {{");
            for param in &list.query {
                let _ = writeln!(out, "  {}", self.query_member(param));
            }
            out.push_str("};\n\n");
        }

        out.push_str(&self.api_interface(set));
        out
    }

    /// One member of the table's read-query type.
    ///
    /// Driven by what the *endpoint* declares, so a parameter that goes away
    /// goes away here too; the three the read layer gives a vocabulary to —
    /// `select`, `order` and the filter map — are typed against this table's own
    /// columns rather than as bare strings, because a column that is not there
    /// is a 400 the compiler can give instead.
    fn query_member(&self, param: &crate::endpoint::QueryParam) -> String {
        let p = &self.pascal;
        match param.name.as_str() {
            "select" => {
                "/** Columns and embeds to return, e.g. `\"id,title\"`. Omit for whole rows. */\n  \
                 select?: S;"
                    .to_owned()
            }
            "order" => format!(
                "/** `\"published.desc\"`, or a precedence list of such keys. */\n  order?: Order<{p}Row>;"
            ),
            "filter" if param.map => format!(
                "/** One entry per column, e.g. `{{ published: \"gte.2020-01-01\" }}`. */\n  \
                 filter?: Filters<{p}Row>;"
            ),
            other => {
                let ty = if param.map {
                    format!("Record<string, {}>", param.ty.ts_type())
                } else if param.repeated {
                    format!("Array<{}>", param.ty.ts_type())
                } else {
                    param.ty.ts_type().to_owned()
                };
                let opt = if param.required { "" } else { "?" };
                format!("{other}{opt}: {ty};")
            }
        }
    }

    /// The `TasksApi` interface: one method per operation the projection
    /// actually registered an endpoint for.
    fn api_interface(&self, set: &EndpointSet) -> String {
        let name = &self.model.name;
        let p = &self.pascal;
        let mut out = format!("/** Reading and writing `{name}`. */\nexport interface {p}Api {{\n");
        if self.list_endpoint(set).is_some() {
            let _ = writeln!(
                out,
                "  /**\n   \
                 * Rows of `{name}`. The `select` decides the shape of the answer, and the\n   \
                 * type follows it: `list()` answers whole rows, a `select` of columns\n   \
                 * answers those columns, and one that embeds a key nests the related row.\n   */"
            );
            let _ = writeln!(
                out,
                "  list<S extends string = \"\">(query?: {p}Query<S>): Promise<Array<{p}Selected<S>>>;"
            );
        }
        if let (Some(_), Some(id_ty)) = (self.list_endpoint(set), self.key_type()) {
            let _ = writeln!(
                out,
                "  /** One row by primary key, or `undefined` when there is none. */"
            );
            let _ = writeln!(
                out,
                "  get<S extends string = \"\">(id: {id_ty}, query?: {{ select?: S }}): Promise<{p}Selected<S> | undefined>;"
            );
        }
        if self.model.ops.create.is_some() {
            let _ = writeln!(out, "  /** Insert a row, answering the row as written. */");
            let _ = writeln!(out, "  create(row: {p}Insert): Promise<{p}Row>;");
        }
        if let Some(id_ty) = self.key_type() {
            if self.model.ops.update.is_some() {
                let _ = writeln!(
                    out,
                    "  /** Change a row, answering the row as it now is. */"
                );
                let _ = writeln!(
                    out,
                    "  update(id: {id_ty}, row: {p}Update): Promise<{p}Row>;"
                );
            }
            if self.model.ops.delete.is_some() {
                let _ = writeln!(out, "  /** Delete a row. */");
                let _ = writeln!(out, "  delete(id: {id_ty}): Promise<Deleted>;");
            }
            for file in &self.model.ops.files {
                let _ = writeln!(out, "  /** The bytes behind `{}`. */", file.field);
                let _ = writeln!(out, "  {}: FileApi<{id_ty}>;", file.field);
            }
        }
        out.push_str("}\n\n");
        out
    }

    /// The factory's implementation of this table's object.
    fn implementation(&self, set: &EndpointSet) -> String {
        let p = &self.pascal;
        let mut out = format!("  const {}: {p}Api = {{\n", self.property);

        if let Some(list) = self.list_endpoint(set) {
            let _ = writeln!(
                out,
                "    async list<S extends string = \"\">(query?: {p}Query<S>): Promise<Array<{p}Selected<S>>> {{"
            );
            let returns = Returns::Json(format!("Array<{p}Selected<S>>"));
            emit_request(&mut out, list, &Request::new(&returns));
            out.push_str("    },\n");

            if let (Some(pk), Some(id_ty)) = (self.model.primary_key.as_deref(), self.key_type()) {
                // `get` is `list` with the key filtered and one row asked for:
                // the read endpoint already answers this, so a second endpoint
                // for it would be a second way to be wrong about access.
                let _ = writeln!(
                    out,
                    "    async get<S extends string = \"\">(id: {id_ty}, query?: {{ select?: S }}): Promise<{p}Selected<S> | undefined> {{"
                );
                let _ = writeln!(
                    out,
                    "      const rows = await {}.list<S>({{ select: query?.select, filter: {{ {pk}: `eq.${{id}}` }}, limit: 1 }} as {p}Query<S>);",
                    self.property
                );
                out.push_str("      return rows[0];\n");
                out.push_str("    },\n");
            }
        }

        if let Some(create) = self.endpoint(set, self.model.ops.create.as_deref()) {
            let _ = writeln!(out, "    async create(row: {p}Insert): Promise<{p}Row> {{");
            let returns = Returns::Json(format!("{p}Row"));
            emit_request(&mut out, create, &Request::new(&returns).from("row", 6));
            out.push_str("    },\n");
        }
        if let Some(id_ty) = self.key_type() {
            if let Some(update) = self.endpoint(set, self.model.ops.update.as_deref()) {
                let _ = writeln!(
                    out,
                    "    async update(id: {id_ty}, row: {p}Update): Promise<{p}Row> {{"
                );
                let returns = Returns::Json(format!("{p}Row"));
                emit_request(&mut out, update, &Request::new(&returns).from("row", 6));
                out.push_str("    },\n");
            }
            if let Some(delete) = self.endpoint(set, self.model.ops.delete.as_deref()) {
                let _ = writeln!(out, "    async delete(id: {id_ty}): Promise<Deleted> {{");
                let returns = Returns::Json("Deleted".to_owned());
                emit_request(&mut out, delete, &Request::new(&returns));
                out.push_str("    },\n");
            }
            for file in &self.model.ops.files {
                let (Some(download), Some(upload)) = (
                    self.endpoint(set, Some(&file.download)),
                    self.endpoint(set, Some(&file.upload)),
                ) else {
                    continue;
                };
                let _ = writeln!(out, "    {}: {{", file.field);
                let _ = writeln!(out, "      async download(id: {id_ty}): Promise<Blob> {{");
                emit_request(
                    &mut out,
                    download,
                    &Request::new(&Returns::Blob).from("body", 8),
                );
                out.push_str("      },\n");
                let _ = writeln!(
                    out,
                    "      async upload(id: {id_ty}, filename: string, body: BodyInit): Promise<unknown> {{"
                );
                let returns = Returns::Json("unknown".to_owned());
                emit_request(&mut out, upload, &Request::new(&returns).from("body", 8));
                out.push_str("      },\n");
                out.push_str("    },\n");
            }
        }

        out.push_str("  };\n");
        out
    }

    /// The columns an insert must supply: writable, `NOT NULL`, and with nothing
    /// for the database to fall back on.
    fn required_keys(&self) -> Vec<&str> {
        self.model
            .fields
            .iter()
            .filter(|f| f.writable() && !f.optional_on_insert())
            .map(|f| f.name.as_str())
            .collect()
    }

    /// The columns no write may set: the calculated ones.
    fn read_only_keys(&self) -> Vec<&str> {
        self.model
            .fields
            .iter()
            .filter(|f| !f.writable())
            .map(|f| f.name.as_str())
            .collect()
    }

    /// Whether this table's read declares the query parameter `name` — which is
    /// what decides whether the client names the type that parameter is typed
    /// with.
    fn declares_query_param(&self, set: &EndpointSet, name: &str) -> bool {
        self.list_endpoint(set)
            .is_some_and(|ep| ep.query.iter().any(|p| p.name == name))
    }

    /// The endpoint behind an operation, when the projection registered one.
    fn endpoint<'s>(&self, set: &'s EndpointSet, name: Option<&str>) -> Option<&'s Endpoint> {
        set.find(name?)
    }

    /// The list endpoint, which every other read is expressed in terms of.
    fn list_endpoint<'s>(&self, set: &'s EndpointSet) -> Option<&'s Endpoint> {
        self.endpoint(set, self.model.ops.list.as_deref())
    }

    /// The TypeScript type of the primary key, when rows are addressable by one.
    fn key_type(&self) -> Option<&'static str> {
        self.model.key_field().map(|f| f.ty.ts_type())
    }
}

/// A column's type in a row: what it holds, `| null` unless the column is
/// `NOT NULL`. Every column is *present* in a whole row, so none of them is
/// `?`-optional — a missing property and a null one are different questions, and
/// only the second one a read can answer.
fn row_field_type(f: &ResourceField) -> String {
    let base = f.ty.ts_type();
    if f.required {
        base.to_owned()
    } else {
        format!("{base} | null")
    }
}

/// A set of column names as a TypeScript key union — `"title" | "author"`, or
/// `never` for none, which is the empty union `Pick`/`Omit` already understand.
fn key_union(keys: &[&str]) -> String {
    match keys.is_empty() {
        true => "never".to_owned(),
        false => keys
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

/// Whether a name can be written as a bare property (`api.tasks`) rather than
/// only as an index (`api["my table"]`).
fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// `BlogPosts` → `blogPosts`.
fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// `ClientOptions` and the error builder: the two things every request in every
/// generated client goes through.
///
/// The error carries the server's own message (the `{ "error": ... }` body every
/// endpoint answers a failure with) rather than just its status — this is what
/// lets a caller surface, e.g., a failed build's bundler diagnostics. The
/// `failed: <status>` prefix is kept stable for callers that parse the status
/// back out of the message.
const REQUEST_HELPERS_HEAD: &str = r#"/** How a client reaches its server. */
export interface ClientOptions {
  /** Prepended to every request path. */
  baseUrl?: string;
  /** Fetch implementation to use (defaults to global `fetch`). */
  fetch?: typeof fetch;
  /** How the live connection behaves, for an application that exposes streams. */
  live?: LiveOptions;
}

/** A failed request, as the error a caller sees: status, and what the server said. */
export async function clientError(op: string, res: Response): Promise<Error> {
  let detail = "";
  try {
    const body: unknown = await res.json();
    if (body && typeof body === "object" && "error" in body && typeof (body as { error: unknown }).error === "string") {
      detail = `: ${(body as { error: string }).error}`;
    }
  } catch {
    // Non-JSON body: the status alone will have to describe the failure.
  }
  return new Error(`${op} failed: ${res.status}${detail}`);
}

"#;

/// The live socket, as a client speaks it (TODO.md "Live updates" §4, §6).
///
/// In the helper rather than in `client.ts` because none of it is about *this*
/// application: how the socket is opened, kept open and multiplexed, and what a
/// subscriber is told, is the same for every app. What is this application's is
/// the **set of streams and their element types**, emitted beside the endpoints
/// as `client.live.<stream>`.
///
/// What [`LiveConnection`] does, deliberately:
///
/// - **One socket per client, opened lazily.** Nothing connects until the first
///   `subscribe`, and the socket is closed again when the last subscription is.
/// - **Reconnects by itself**, with a capped exponential backoff and jitter, and
///   resubscribes everything it had. Every subscriber is then told `resync()`:
///   what arrived while the socket was down is gone (delivery is at-most-once),
///   so anything built from the elements may be out of date.
/// - **A refused subscription is not retried.** An `error` before `ready`, or a
///   `revoked`, ends that subscription and is handed to its `error` handler; a
///   reconnect does not ask again for what the server already said no to.
/// - **It never throws on a frame it does not understand**, so a server that
///   grows a frame type does not break a client generated before it.
const LIVE_TYPES: &str = r#"// --- live updates -----------------------------------------------------------

/** Where a live connection is: connecting for the first time, open, or reconnecting after a loss. */
export type LiveStatus = "connecting" | "open" | "reconnecting";

/** What the server says when a subscription starts (and again if its stream restarts). */
export interface LiveReady {
  stream: string;
  /** How many of the elements that follow are history, not new arrivals. */
  replayed: number;
  /** What an element's `value` is, or `null` while the stream is not running on the server. */
  element_type: unknown;
  /** Whether this subscriber may publish on the stream. */
  can_publish: boolean;
  status: unknown;
  counters: unknown;
}

/** Why the server refused, ended or complained about a subscription. */
export interface LiveError {
  /** `unavailable`, `revoked`, `invalid`, `too_many_subscriptions`, `signed_out`, … */
  code: string;
  message: string;
}

/** What a subscriber is told. Only `element` is required. */
export interface LiveHandlers<E> {
  ready?(info: LiveReady): void;
  element(envelope: E): void;
  /** This subscription fell behind and lost `dropped` elements (it is never a silent gap). */
  lagged?(dropped: number): void;
  /** The connection was lost and re-established: anything built from earlier elements may be stale. */
  resync?(): void;
  status?(status: unknown): void;
  /** A refusal. Before `ready`, or as `revoked`, it ends the subscription, which is not retried. */
  error?(error: LiveError): void;
}

/** A live subscription. `close()` ends it. */
export interface LiveSubscription {
  close(): void;
}

/** One stream an application exposes, ready to subscribe to. */
export interface LiveStream<E> {
  readonly name: string;
  /** The connection it is subscribed over, for its `status`. */
  readonly connection: LiveConnection;
  subscribe(handlers: LiveHandlers<E>): LiveSubscription;
}

/** How a live connection behaves. */
export interface LiveOptions {
  /** The `WebSocket` constructor to use (defaults to the global one). */
  WebSocket?: typeof WebSocket;
  /** The first reconnect delay, in milliseconds. */
  minDelay?: number;
  /** The longest reconnect delay, in milliseconds. */
  maxDelay?: number;
}

/** The live socket's URL: `path` on the client's base URL, as `ws:` or `wss:`. */
export function liveUrl(baseUrl: string, path: string): string {
  const origin = baseUrl || (typeof location === "undefined" ? "http://localhost" : location.origin);
  const url = new URL(path, origin);
  url.protocol = url.protocol === "https:" ? "wss:" : "ws:";
  return url.toString();
}

type LiveEntry = { stream: string; handlers: LiveHandlers<unknown>; ready: boolean };

/** One socket, any number of subscriptions, reconnecting by itself. */
export class LiveConnection {
  private socket: WebSocket | undefined;
  private readonly entries = new Map<string, LiveEntry>();
  private readonly listeners = new Set<(status: LiveStatus) => void>();
  private nextSub = 1;
  private attempt = 0;
  private opened = false;
  private timer: ReturnType<typeof setTimeout> | undefined;
  private current: LiveStatus = "connecting";
  // Fields assigned in the body rather than as parameter properties: Node runs
  // this file by stripping its types, and a parameter property is not erasable.
  private readonly url: string;
  private readonly options: LiveOptions;

  constructor(url: string, options: LiveOptions = {}) {
    this.url = url;
    this.options = options;
  }

  /** Where the connection is now. */
  get status(): LiveStatus {
    return this.current;
  }

  /** Be told when the status changes. Returns the function that stops it. */
  onStatus(listener: (status: LiveStatus) => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  /** The accessor for the stream called `name`. */
  stream<E>(name: string): LiveStream<E> {
    return {
      name,
      connection: this,
      subscribe: (handlers: LiveHandlers<E>) => this.subscribe(name, handlers),
    };
  }

  /** Subscribe to `stream`, opening the socket if this is the first subscription. */
  subscribe<E>(stream: string, handlers: LiveHandlers<E>): LiveSubscription {
    const sub = `s${this.nextSub++}`;
    this.entries.set(sub, { stream, handlers: handlers as LiveHandlers<unknown>, ready: false });
    if (this.socket && this.socket.readyState === 1) {
      this.send({ type: "subscribe", sub, stream });
    } else {
      this.open();
    }
    let active = true;
    return {
      close: () => {
        if (!active) return;
        active = false;
        if (this.entries.delete(sub) && this.socket && this.socket.readyState === 1) {
          this.send({ type: "unsubscribe", sub });
        }
        if (this.entries.size === 0) this.shutdown();
      },
    };
  }

  /** End every subscription and close the socket. */
  close(): void {
    this.entries.clear();
    this.shutdown();
  }

  private setStatus(status: LiveStatus): void {
    if (status === this.current) return;
    this.current = status;
    this.listeners.forEach((listener) => listener(status));
  }

  private send(frame: Record<string, unknown>): void {
    this.socket?.send(JSON.stringify(frame));
  }

  private open(): void {
    if (this.socket || this.timer !== undefined) return;
    const Socket = this.options.WebSocket ?? (typeof WebSocket === "undefined" ? undefined : WebSocket);
    if (!Socket) throw new Error("live updates need a WebSocket implementation (LiveOptions.WebSocket)");
    const socket = new Socket(this.url);
    this.socket = socket;
    socket.onopen = () => {
      const reconnect = this.opened;
      this.opened = true;
      this.attempt = 0;
      this.setStatus("open");
      this.entries.forEach((entry, sub) => {
        entry.ready = false;
        this.send({ type: "subscribe", sub, stream: entry.stream });
        if (reconnect) entry.handlers.resync?.();
      });
    };
    socket.onmessage = (event: MessageEvent) => this.receive(event.data);
    socket.onclose = () => {
      if (this.socket !== socket) return;
      this.socket = undefined;
      if (this.entries.size === 0) return;
      this.setStatus("reconnecting");
      const min = this.options.minDelay ?? 500;
      const max = this.options.maxDelay ?? 30000;
      const delay = Math.min(max, min * 2 ** this.attempt);
      this.attempt += 1;
      // Half the delay, plus up to half again at random: a server that restarts
      // is not met by every page reconnecting in the same millisecond.
      this.timer = setTimeout(() => {
        this.timer = undefined;
        this.open();
      }, delay / 2 + Math.random() * (delay / 2));
    };
  }

  private shutdown(): void {
    if (this.timer !== undefined) {
      clearTimeout(this.timer);
      this.timer = undefined;
    }
    const socket = this.socket;
    this.socket = undefined;
    this.opened = false;
    this.attempt = 0;
    socket?.close();
    this.setStatus("connecting");
  }

  private receive(data: unknown): void {
    let frame: Record<string, unknown>;
    try {
      const parsed: unknown = JSON.parse(String(data));
      if (!parsed || typeof parsed !== "object") return;
      frame = parsed as Record<string, unknown>;
    } catch {
      return;
    }
    const sub = typeof frame["sub"] === "string" ? frame["sub"] : undefined;
    const entry = sub === undefined ? undefined : this.entries.get(sub);
    switch (frame["type"]) {
      case "ready":
        if (entry) {
          entry.ready = true;
          entry.handlers.ready?.(frame as unknown as LiveReady);
        }
        break;
      case "element":
        entry?.handlers.element(frame["envelope"]);
        break;
      case "lagged":
        entry?.handlers.lagged?.(Number(frame["dropped"] ?? 0));
        break;
      case "status":
        entry?.handlers.status?.(frame["status"]);
        break;
      case "revoked":
        if (entry && sub !== undefined) {
          this.entries.delete(sub);
          entry.handlers.error?.({ code: "revoked", message: "access to this stream ended" });
        }
        break;
      case "error": {
        const error: LiveError = {
          code: String(frame["code"] ?? "error"),
          message: String(frame["message"] ?? ""),
        };
        if (sub === undefined) {
          // About the connection, not one subscription: everyone hears it, and
          // the reconnect that follows a close asks again.
          this.entries.forEach((each) => each.handlers.error?.(error));
        } else if (entry) {
          // Refused before `ready`: the subscription never started, so it ends.
          if (!entry.ready) this.entries.delete(sub);
          entry.handlers.error?.(error);
        }
        break;
      }
      default:
        // A frame this client was generated before: ignored, never thrown on.
        break;
    }
  }
}

"#;

/// The reading vocabulary shared by every table: what a delete answers, what a
/// filter and an order may say, a file column's two calls, and the types that
/// compute the shape of a `select`.
///
/// Emitted verbatim (only when the set has tables) rather than assembled,
/// because it is *one* piece of TypeScript: the select types are a small parser
/// written in the type system, and a parser is not clearer for being generated
/// line by line from Rust.
const READ_TYPES: &str = r#"// --- reading a table --------------------------------------------------------

/** What a delete answers with. */
export type Deleted = { deleted: true };

/** A comparison a filter may name. */
export type FilterOp =
  | "eq"
  | "ne"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "nin"
  | "like"
  | "ilike"
  | "is_null";

/** One column's filter: a comparison and its operand, e.g. `gte.2020-01-01`. */
export type FilterValue = `${FilterOp}.${string}`;

/** The filters a read may carry — one per column of the table being read. */
export type Filters<Row> = Partial<Record<Extract<keyof Row, string>, FilterValue>>;

/** One `order` key: a column, ascending unless it says otherwise. */
export type OrderKey<Row> =
  | Extract<keyof Row, string>
  | `${Extract<keyof Row, string>}.asc`
  | `${Extract<keyof Row, string>}.desc`;

/** `order`: one key, or a precedence list of them. */
export type Order<Row> = OrderKey<Row> | `${OrderKey<Row>},${string}`;

/** Flatten an intersection, so a hover shows the object rather than the pieces. */
type Flatten<T> = { [K in keyof T]: T[K] } & {};

/**
 * A write body over a table's row: `Required` must be given, everything else may
 * be, and `ReadOnly` cannot be given at all.
 *
 * A row and an insert hold the same columns with the same types and differ only
 * in which of them the *caller* has to supply — so a generated client says that
 * difference as two lists of column names rather than as a second copy of the
 * table, which could describe a different one.
 */
export type Insertable<
  Row,
  Required extends keyof Row,
  ReadOnly extends keyof Row = never,
> = Flatten<Pick<Row, Required> & Partial<Omit<Row, Required | ReadOnly>>>;

/** The bytes behind a file column. */
export interface FileApi<Id> {
  /** Read them. */
  download(id: Id): Promise<Blob>;
  /** Replace them with `body`, stored under `filename`. */
  upload(id: Id, filename: string, body: BodyInit): Promise<unknown>;
}

// --- the type of a `select` -------------------------------------------------
//
// A `select` changes the shape of what comes back, so what a read *returns* is a
// function of the string the caller wrote: `list({ select: "title,author(name)" })`
// answers `{ title, author: { name } }` and nothing else. The types below are
// that function, evaluated by the compiler — which is why there is one `list`
// rather than one for rows and another for embeds.
//
// A select assembled at runtime (typed `string`, not a literal) cannot be read
// this way. It degrades to the whole row plus unknown extras rather than
// failing: the compiler then knows exactly what the caller does.

/** A table's row type, and the tables its keys point at. */
export type TableSchema = { row: object; rels: { [field: string]: TableSchema } };

type Trim<S extends string> = S extends ` ${infer R}`
  ? Trim<R>
  : S extends `${infer R} `
    ? Trim<R>
    : S;

/** Split a select list on its top-level commas — the ones outside any `(…)`. */
type SplitItems<
  S extends string,
  Depth extends 0[] = [],
  Item extends string = "",
  Out extends string[] = [],
> = S extends `${infer C}${infer Rest}`
  ? C extends "("
    ? SplitItems<Rest, [...Depth, 0], `${Item}${C}`, Out>
    : C extends ")"
      ? SplitItems<
          Rest,
          Depth extends [0, ...infer Less extends 0[]] ? Less : [],
          `${Item}${C}`,
          Out
        >
      : C extends ","
        ? Depth["length"] extends 0
          ? SplitItems<Rest, Depth, "", [...Out, Item]>
          : SplitItems<Rest, Depth, `${Item}${C}`, Out>
        : SplitItems<Rest, Depth, `${Item}${C}`, Out>
  : [...Out, Item];

/** The type of one column — `unknown` for a name the table does not have. */
type ColumnOf<S extends TableSchema, Name extends string> = Name extends keyof S["row"]
  ? S["row"][Name]
  : unknown;

/**
 * The type of one embed: what was selected on the far side, and `null` when the
 * key itself is nullable — a null key answers `null` rather than an object of
 * nulls.
 */
type EmbedOf<S extends TableSchema, Name extends string, Inner extends string> = Name extends
  keyof S["rels"]
  ? Name extends keyof S["row"]
    ? null extends S["row"][Name]
      ? Selected<S["rels"][Name], Inner> | null
      : Selected<S["rels"][Name], Inner>
    : Selected<S["rels"][Name], Inner>
  : unknown;

/** One select item: `column`, `alias:column`, `key(…)` or `alias:key(…)`. */
type ItemOf<S extends TableSchema, Item extends string> = Trim<Item> extends
  `${infer Alias}:${infer Target}`
  ? { [K in Trim<Alias>]: TargetOf<S, Trim<Target>> }
  : Trim<Item> extends `${infer Name}(${infer Inner})`
    ? { [K in Trim<Name>]: EmbedOf<S, Trim<Name>, Inner> }
    : { [K in Trim<Item>]: ColumnOf<S, Trim<Item>> };

/** What an item points at, once any alias has been taken off the front. */
type TargetOf<S extends TableSchema, Target extends string> = Target extends
  `${infer Name}(${infer Inner})`
  ? EmbedOf<S, Trim<Name>, Inner>
  : ColumnOf<S, Target>;

type ItemsOf<S extends TableSchema, Items extends string[]> = {
  [I in keyof Items]: ItemOf<S, Items[I] & string>;
}[number];

type UnionToIntersection<U> = (U extends unknown ? (x: U) => void : never) extends
  (x: infer I) => void
  ? I
  : never;

/** What a read with the select `Sel` answers with. */
export type Selected<S extends TableSchema, Sel extends string> = string extends Sel
  ? S["row"] & Record<string, unknown>
  : Trim<Sel> extends ""
    ? S["row"]
    : Flatten<UnionToIntersection<ItemsOf<S, SplitItems<Sel>>>>;

"#;
