#![allow(clippy::unwrap_used, clippy::expect_used)]

//! The trigger half of `admin_copilot` against a **real** Postgres and the
//! **real** built-in actions.
//!
//! What is pinned here is what a mock could not have: a trigger the agent wrote
//! actually firing on the next insert, a configuration refused by the same
//! validation that stands in front of the admin's own form — carrying the
//! settings it should have used — and the grants deciding create, edit, delete
//! and who may run the thing afterwards.
//!
//! The tool set is the answer to "how does a model configure one of an
//! open-ended set of actions?": `describe_action` hands over one action's
//! settings when asked, and a wrong guess is refused with those settings
//! attached, rather than a second inference call filling them in out of sight.

use crate::common;

use common::{Env, as_user, config};
use sc_agent::RunCaller;
use sc_core_actions::builtin_actions;
use sc_error::Result;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

const TRAIT: &str = "admin_copilot";

/// The library plus the table a trigger writes to.
const SCHEMA: &str = "
    CREATE TABLE books (
        id bigint generated by default as identity primary key,
        title text,
        pages bigint
    );
    CREATE TABLE arrivals (
        id bigint generated by default as identity primary key,
        what text
    );
";

/// Everything granted — what an admin who ticked all four boxes has.
fn all_grants() -> Attrs {
    config(&[
        ("allow_create", json!(true)),
        ("allow_edit", json!(true)),
        ("allow_drop", json!(true)),
        ("allow_access_changes", json!(true)),
    ])
}

/// The default configuration: build and edit, never delete, never widen access.
fn default_grants() -> Attrs {
    config(&[])
}

async fn env() -> Result<Env> {
    Env::with_schema(SCHEMA)
        .await?
        .with_triggers(builtin_actions()?)
}

async fn call(env: &Env, cfg: &Attrs, tool: &str, args: Json) -> Result<Json> {
    env.call_tool(TRAIT, cfg, tool, args, &RunCaller::system())
        .await
}

/// The trigger an agent is asked for over and over below: every new book is
/// noted in `arrivals`.
fn note_arrival() -> Json {
    json!({
        "name": "note_arrival",
        "description": "Note every new book",
        "when": "insert",
        "table": "books",
        "action": "insert_row",
        "configuration": {
            "table": "arrivals",
            "values": { "what": "row.title" },
        },
    })
}

#[tokio::test]
async fn a_trigger_the_agent_wrote_fires_on_the_next_insert() -> Result<()> {
    let env = env().await?;
    let result = call(&env, &default_grants(), "save_trigger", note_arrival()).await?;
    assert_eq!(result["saved"], json!("note_arrival"));
    assert_eq!(result["created"], json!(true));
    // The whole trigger comes back, not an echo of the arguments.
    assert_eq!(result["trigger"]["when"], json!("insert"));
    assert_eq!(result["trigger"]["table"], json!("books"));
    assert_eq!(
        result["trigger"]["configuration"]["values"]["what"],
        json!("row.title")
    );
    // Nobody said who may run it, so it is admin-only — the safe reading, and
    // reported as the number it behaves as rather than as null.
    assert_eq!(result["trigger"]["min_role"], json!(1));

    // And it is **live**, with no reload of anybody's: the write goes through
    // the row layer, the table's events fire, and the trigger the agent wrote a
    // moment ago writes the row.
    env.call(
        "insert_row",
        &config(&[("table", json!("books"))]),
        json!({ "title": "Solaris", "pages": 204 }),
        &RunCaller::system(),
    )
    .await?;
    let arrivals = env.rows("arrivals").await?;
    assert_eq!(arrivals.len(), 1, "{arrivals:?}");
    assert_eq!(arrivals[0]["what"], json!("Solaris"));
    Ok(())
}

#[tokio::test]
async fn an_action_hands_over_its_settings_when_it_is_asked_for_them() -> Result<()> {
    let env = env().await?;

    // The index level: every action, one line each, no settings.
    let all = call(&env, &default_grants(), "describe_action", json!({})).await?;
    let names: Vec<&str> = all["actions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| a["name"].as_str().unwrap())
        .collect();
    assert!(names.contains(&"insert_row"), "{names:?}");
    assert!(names.contains(&"send_email"), "{names:?}");
    assert!(all["actions"][0]["settings"].is_null(), "{all}");

    // One action's settings — the keys of `configuration`, with what each is
    // for and whether it is required.
    let one = call(
        &env,
        &default_grants(),
        "describe_action",
        json!({ "action": "insert_row", "table": "books" }),
    )
    .await?;
    let settings = one["settings"].as_array().unwrap();
    let keys: Vec<&str> = settings
        .iter()
        .map(|s| s["name"].as_str().unwrap())
        .collect();
    assert_eq!(keys, vec!["table", "values"]);
    assert!(settings.iter().all(|s| s["required"] == json!(true)));
    assert_eq!(settings[0]["what_it_is"], json!("Table"));
    // Settings that are data carry no code reference…
    assert!(one["code_api"].is_null(), "{one}");

    // …and an action whose setting is a JavaScript body hands over the API
    // that body can call, so the code is written against it rather than
    // against an ORM the model already knows — the same page
    // `describe_code_api` answers on its own.
    let js = call(
        &env,
        &default_grants(),
        "describe_action",
        json!({ "action": "run_js_code", "table": "books" }),
    )
    .await?;
    let api = js["code_api"]
        .as_str()
        .expect("run_js_code carries code_api");
    assert!(api.contains(".where({ id: row.id }).update({"), "{api}");
    assert!(api.contains("db.t.update(id, values)"), "{api}");
    let alone = call(&env, &default_grants(), "describe_code_api", json!({})).await?;
    assert_eq!(alone["reference"].as_str(), Some(api));

    // A guessed name is refused with the alternatives, which is the whole
    // recovery a model needs.
    let err = call(
        &env,
        &default_grants(),
        "describe_action",
        json!({ "action": "send_mail" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("send_mail"), "{err}");
    assert!(err.contains("send_email"), "{err}");
    Ok(())
}

#[tokio::test]
async fn a_settings_mistake_is_refused_carrying_the_settings_it_should_have_used() -> Result<()> {
    let env = env().await?;
    let mut wrong = note_arrival();
    wrong["configuration"] = json!({ "tabel": "arrivals", "values": {} });
    let err = call(&env, &default_grants(), "save_trigger", wrong)
        .await
        .unwrap_err()
        .to_string();

    // The validation's own sentence, which names the setting that is missing…
    assert!(err.contains("`table` is required"), "{err}");
    // …and the settings the action does take, appended — so a model that
    // guessed instead of calling `describe_action` is put right in the turn it
    // was refused rather than in the turn after that.
    assert!(err.contains("The settings `insert_row` takes"), "{err}");
    assert!(err.contains("`values`"), "{err}");
    assert!(err.contains("Nothing was saved"), "{err}");

    // And nothing was: a refused save leaves no half-written trigger.
    assert!(sc_action::list_triggers(&env.catalog).await?.is_empty());

    // A setting the action does not declare is refused too, rather than stored
    // and silently ignored — which is what would happen if `configuration` were
    // merely passed through.
    let mut extra = note_arrival();
    extra["configuration"]["subject"] = json!("A new book");
    let err = call(&env, &default_grants(), "save_trigger", extra)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("unknown setting `subject`"), "{err}");

    // The same is true of a formula that does not resolve in the scope the
    // event will actually give it — checked properly, on save, not at fire time.
    let mut unresolvable = note_arrival();
    unresolvable["configuration"]["values"] = json!({ "what": "row.no_such_field" });
    let err = call(&env, &default_grants(), "save_trigger", unresolvable)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("no_such_field"), "{err}");
    assert!(sc_action::list_triggers(&env.catalog).await?.is_empty());
    Ok(())
}

#[tokio::test]
async fn an_edit_changes_only_what_it_names_and_the_name_is_the_identity() -> Result<()> {
    let env = env().await?;
    call(&env, &default_grants(), "save_trigger", note_arrival()).await?;

    let result = call(
        &env,
        &default_grants(),
        "save_trigger",
        json!({ "name": "note_arrival", "description": "Every arrival, noted" }),
    )
    .await?;
    // The same trigger, edited — the name is the identity, so there is no
    // second one.
    assert_eq!(result["created"], json!(false));
    assert_eq!(sc_action::list_triggers(&env.catalog).await?.len(), 1);
    let trigger = &result["trigger"];
    assert_eq!(trigger["description"], json!("Every arrival, noted"));
    // Everything the edit did not name is exactly as it was.
    assert_eq!(trigger["when"], json!("insert"));
    assert_eq!(trigger["table"], json!("books"));
    assert_eq!(trigger["action"], json!("insert_row"));
    assert_eq!(trigger["configuration"]["table"], json!("arrivals"));

    // Changing the action without its settings is refused rather than
    // half-applied: `send_email`'s settings are not `insert_row`'s.
    let err = call(
        &env,
        &default_grants(),
        "save_trigger",
        json!({ "name": "note_arrival", "action": "send_email" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("also needs a new `configuration`"), "{err}");
    assert!(err.contains("describe_action"), "{err}");
    Ok(())
}

#[tokio::test]
async fn the_grants_decide_creating_editing_deleting_and_who_may_run_it() -> Result<()> {
    let env = env().await?;
    let create_only = config(&[("allow_create", json!(true)), ("allow_edit", json!(false))]);

    call(&env, &create_only, "save_trigger", note_arrival()).await?;
    // Saving under a name that exists is an **edit**, and an agent that may only
    // create is refused rather than quietly rewriting the admin's trigger.
    let err = call(
        &env,
        &create_only,
        "save_trigger",
        json!({ "name": "note_arrival", "description": "mine now" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("allow_edit"), "{err}");
    assert!(err.contains("nothing was changed"), "{err}");

    // Who may run a trigger through the API is an access rule, so it needs the
    // access grant — not the edit grant that got the rest of the trigger saved.
    let err = call(
        &env,
        &default_grants(),
        "save_trigger",
        json!({ "name": "note_arrival", "min_role": 80 }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("allow_access_changes"), "{err}");
    let result = call(
        &env,
        &all_grants(),
        "save_trigger",
        json!({ "name": "note_arrival", "min_role": 80 }),
    )
    .await?;
    assert_eq!(result["trigger"]["min_role"], json!(80));

    // Deleting is behind the same checkbox dropping a table is.
    let err = call(
        &env,
        &default_grants(),
        "delete_trigger",
        json!({ "name": "note_arrival" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("allow_drop"), "{err}");
    assert_eq!(sc_action::list_triggers(&env.catalog).await?.len(), 1);

    let result = call(
        &env,
        &all_grants(),
        "delete_trigger",
        json!({ "name": "note_arrival" }),
    )
    .await?;
    assert_eq!(result["deleted"], json!("note_arrival"));
    // What it was, so an agent that deleted the wrong thing can put it back
    // from its own transcript.
    assert_eq!(result["was"]["configuration"]["table"], json!("arrivals"));
    assert!(sc_action::list_triggers(&env.catalog).await?.is_empty());
    // And it is gone from the live set too, not merely from the table.
    assert!(
        env.dispatcher
            .as_ref()
            .unwrap()
            .triggers()?
            .by_name("note_arrival")
            .is_none()
    );

    // The one it names does not exist any more, and the refusal says what does.
    let err = call(
        &env,
        &all_grants(),
        "delete_trigger",
        json!({ "name": "note_arrival" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("no triggers yet"), "{err}");
    Ok(())
}

#[tokio::test]
async fn changing_the_event_clears_what_the_new_one_cannot_have() -> Result<()> {
    let env = env().await?;
    let mut literal = note_arrival();
    // A configuration that does not read the row, so the trigger stays valid
    // when it stops having one.
    literal["configuration"]["values"] = json!({ "what": "'a book'" });
    literal["only_if"] = json!("pages > 100");
    call(&env, &default_grants(), "save_trigger", literal).await?;

    let result = call(
        &env,
        &default_grants(),
        "save_trigger",
        json!({ "name": "note_arrival", "when": "none" }),
    )
    .await?;
    assert_eq!(result["trigger"]["when"], json!("none"));
    // The table and the condition went with the event that gave them meaning,
    // and the model is told rather than left to notice.
    assert_eq!(result["trigger"]["table"], Json::Null);
    assert_eq!(result["trigger"]["only_if"], Json::Null);
    let notes = result["notes"].to_string();
    assert!(notes.contains("no row"), "{notes}");
    Ok(())
}

#[tokio::test]
async fn describe_triggers_lists_the_actions_and_why_a_trigger_is_not_usable() -> Result<()> {
    let env = env().await?;
    call(&env, &default_grants(), "save_trigger", note_arrival()).await?;

    let result = call(&env, &default_grants(), "describe_triggers", json!({})).await?;
    assert_eq!(result["triggers"].as_array().unwrap().len(), 1);
    assert_eq!(result["triggers"][0]["name"], json!("note_arrival"));
    assert!(result["triggers"][0]["error"].is_null(), "{result}");
    // The actions come with the listing, because they are what the next call
    // needs and they cost a line each.
    assert!(!result["actions"].as_array().unwrap().is_empty());

    // Now break it from the other half of the same trait, and reload the set the
    // way a restart would.
    call(
        &env,
        &all_grants(),
        "edit_schema",
        json!({"operations": [{"op": "drop_table", "table": "arrivals"}]}),
    )
    .await?;
    env.reload_triggers().await?;

    let result = call(
        &env,
        &default_grants(),
        "describe_triggers",
        json!({ "trigger": "note_arrival" }),
    )
    .await?;
    // Still listed — a trigger that has dropped out of the live set is exactly
    // the one an agent is asked to repair, so it is described with its reason
    // rather than hidden.
    let described = &result["triggers"][0];
    assert_eq!(described["name"], json!("note_arrival"));
    let problem = described["error"].as_str().unwrap_or_default();
    assert!(problem.contains("arrivals"), "{problem}");

    let err = call(
        &env,
        &default_grants(),
        "describe_triggers",
        json!({ "trigger": "note_arrivals" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("the triggers are note_arrival"), "{err}");
    Ok(())
}

#[tokio::test]
async fn every_tool_refuses_a_conversation_that_is_not_with_an_admin() -> Result<()> {
    let env = env().await?;
    call(&env, &default_grants(), "save_trigger", note_arrival()).await?;

    for (tool, args) in [
        ("describe_triggers", json!({})),
        ("describe_action", json!({ "action": "insert_row" })),
        ("save_trigger", note_arrival()),
        ("delete_trigger", json!({ "name": "note_arrival" })),
    ] {
        let err = env
            .call_tool(
                TRAIT,
                &all_grants(),
                tool,
                args,
                &as_user("member@example.com"),
            )
            .await
            .unwrap_err()
            .to_string();
        assert!(err.contains("only available to an administrator"), "{err}");
        assert!(err.contains("role-40"), "{err}");
    }
    // Nothing a role-40 user asked for happened.
    assert_eq!(sc_action::list_triggers(&env.catalog).await?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn the_trait_offers_seventeen_tools_and_the_trigger_ones_point_at_each_other() -> Result<()> {
    let env = env().await?;
    let tools = env.tools(TRAIT, &default_grants());
    let names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(
        names,
        vec![
            "describe_schema",
            "edit_schema",
            "describe_triggers",
            "describe_action",
            "save_trigger",
            "delete_trigger",
            "describe_code_api",
            "describe_applications",
            "create_file_store",
            "create_application",
            "update_application",
            "describe_translations",
            "save_translations",
            "save_api_query",
            "delete_api_query",
            "delegate_to_coding_agent",
            "publish_application",
        ]
    );
    let by_name = |name: &str| {
        tools
            .iter()
            .find(|t| t.name == name)
            .expect("the tool")
            .clone()
    };
    // The sequence the descriptions steer through — choose the action, then ask
    // what it takes, then save — is the one thing the model has to get right
    // without being told twice.
    assert!(
        by_name("describe_triggers")
            .description
            .contains("describe_action")
    );
    assert!(
        by_name("save_trigger")
            .description
            .contains("describe_action")
    );
    // And a code body is pointed at the API it is written against, with the
    // one shape models most often guess wrong spelled out.
    let save = by_name("save_trigger").description;
    assert!(save.contains("describe_code_api"), "{save}");
    assert!(
        save.contains("db.t.where({ id: row.id }).update("),
        "{save}"
    );
    // Nothing is compulsory but the name, so an edit sends what it is changing.
    assert_eq!(
        by_name("save_trigger").parameters["required"],
        json!(["name"])
    );
    Ok(())
}
