#![allow(clippy::unwrap_used, clippy::expect_used)]

//! The application half of `admin_copilot` against a **real** Postgres, a real
//! stored application and a real file store (§11.3, §13.4).
//!
//! What is pinned here is what a mock could not have: a query the agent wrote
//! being *prepared by the database*, so the columns it comes back with are the
//! ones Postgres reported rather than anybody's declaration; a statement that
//! will not prepare leaving the stored application exactly as it was; and the
//! application's generated TypeScript client growing the method in the same call,
//! because a client that disagrees with the definition is the drift the whole
//! §13.1 arrangement exists to prevent.
//!
//! The two **area** checkboxes are pinned here too, in the one place they are
//! visible: what an agent is offered.

use crate::common;

use common::{Env, as_user, config};
use sc_agent::RunCaller;
use sc_app::{
    ApiConfig, Application, FrameworkRef, load_application_by_subdomain, save_application,
};
use sc_core_traits::{
    CFG_ALLOW_APPLICATIONS, CFG_ALLOW_TRIGGERS, TOOL_DELETE_QUERY, TOOL_DESCRIBE_APPS,
    TOOL_DESCRIBE_TRIGGERS, TOOL_SAVE_QUERY,
};
use sc_error::Result;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

const TRAIT: &str = "admin_copilot";

/// A library with authors, so a report has something to group by.
const SCHEMA: &str = "
    CREATE TABLE books (
        id bigint generated by default as identity primary key,
        title text,
        author text,
        year bigint
    );
    INSERT INTO books (title, author, year) VALUES
        ('Dune', 'Herbert', 1965),
        ('Emma', 'Austen', 1815),
        ('Ubik', 'Dick', 1969);
";

/// Everything granted — what an admin who ticked all four boxes has.
fn all_grants() -> Attrs {
    config(&[
        ("allow_create", json!(true)),
        ("allow_edit", json!(true)),
        ("allow_drop", json!(true)),
        ("allow_access_changes", json!(true)),
    ])
}

/// The default configuration: build and edit, never delete, never widen access.
fn default_grants() -> Attrs {
    config(&[])
}

async fn call(env: &Env, cfg: &Attrs, tool: &str, args: Json) -> Result<Json> {
    env.call_tool(TRAIT, cfg, tool, args, &RunCaller::system())
        .await
}

/// An application with a REST API and a source tree, so the generated client has
/// somewhere to land.
async fn app_with_api(env: &Env) -> Result<std::path::PathBuf> {
    let dir = env.with_file_store("apps", None).await?;
    env.put(&dir, "web/src/App.tsx", "export const App = 1;\n")?;
    let framework = FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/api.ts");
    let app = Application::new("Blog", "blog", framework)
        .with_table(sc_catalog::TableId("books".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"));
    save_application(&env.catalog, &app).await?;
    Ok(dir)
}

/// The query the agent is asked for over and over below: how many books each
/// author wrote, since a year the caller chooses.
fn top_authors() -> Json {
    json!({
        "application": "blog",
        "name": "topAuthors",
        "description": "Books per author since a year",
        "path": "/reports/top-authors",
        "code": "select author, count(*) as books from books where year > :since \
                group by author",
        "params": [{ "name": "since", "type": "int" }],
    })
}

/// The custom queries stored on `blog`'s API, read back from the row.
async fn stored(env: &Env) -> Result<Vec<sc_api::CustomQuery>> {
    let app = load_application_by_subdomain(&env.catalog, "blog")
        .await?
        .expect("the application is stored");
    sc_api::custom_queries(&app.apis[0].config)
}

#[tokio::test]
async fn a_query_the_agent_wrote_is_typed_by_the_database_and_lands_in_the_client() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    let dir = app_with_api(&env).await?;

    let result = call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;
    assert_eq!(result["saved"], json!("topAuthors"));
    assert_eq!(result["created"], json!(true));
    assert_eq!(result["api"], json!("/api"));
    // Nobody said who may call it, so it is admin-only — the safe reading.
    assert_eq!(result["query"]["min_role"], json!(1));
    assert_eq!(result["query"]["method"], json!("GET"));

    // The part no mock could produce: the shape is the *database's* answer to
    // `describe`, not the model's declaration and not this test's.
    let returns = result["query"]["returns"].as_array().unwrap();
    assert_eq!(returns.len(), 2, "{result}");
    assert_eq!(returns[0]["name"], json!("author"));
    assert_eq!(returns[0]["type"], json!("text"));
    assert_eq!(returns[1]["name"], json!("books"));
    assert_eq!(returns[1]["type"], json!("int"));

    // It is stored, with the columns beside the SQL that produced them.
    let stored = stored(&env).await?;
    assert_eq!(stored.len(), 1);
    assert_eq!(stored[0].name, "topAuthors");
    assert_eq!(stored[0].path, "/reports/top-authors");
    assert_eq!(stored[0].columns.len(), 2);

    // …and the app's generated client has the method, because the definition and
    // the source tree are not allowed to disagree (§13.1).
    let client = env.slurp(&dir, "web/src/api.ts")?;
    assert!(client.contains("topAuthors"), "{client}");
    assert!(client.contains("since"), "{client}");
    Ok(())
}

#[tokio::test]
async fn sql_the_database_refuses_leaves_the_application_exactly_as_it_was() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;

    let mut broken = top_authors();
    broken["name"] = json!("byPublisher");
    broken["path"] = json!("/reports/by-publisher");
    broken["code"] = json!("select publisher from books where year > :since");
    let err = call(&env, &default_grants(), TOOL_SAVE_QUERY, broken)
        .await
        .unwrap_err()
        .to_string();
    // Postgres's own message, so the model can fix the column rather than guess.
    assert!(err.contains("publisher"), "{err}");
    assert!(err.contains("Nothing was saved"), "{err}");

    // The refusal is whole: the query that was already there is untouched and the
    // broken one is not stored.
    let kept = stored(&env).await?;
    assert_eq!(kept.len(), 1, "{kept:?}");
    assert_eq!(kept[0].name, "topAuthors");

    // The same is true of the rules decided without the database: one statement,
    // and declared parameters matching the used ones.
    let mut two = top_authors();
    two["name"] = json!("twoStatements");
    two["path"] = json!("/reports/two");
    two["params"] = json!([]);
    two["code"] = json!("select 1 as n; select 2 as n");
    let err = call(&env, &default_grants(), TOOL_SAVE_QUERY, two)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("one statement"), "{err}");

    let mut undeclared = top_authors();
    undeclared["name"] = json!("undeclared");
    undeclared["path"] = json!("/reports/undeclared");
    undeclared["params"] = json!([]);
    let err = call(&env, &default_grants(), TOOL_SAVE_QUERY, undeclared)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains(":since"), "{err}");
    assert_eq!(stored(&env).await?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn an_edit_merges_into_what_is_stored_and_is_its_own_grant() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;

    // Only the SQL is named, so only the SQL changes — and the columns are
    // re-described, which is the point of re-preparing on every save.
    let result = call(
        &env,
        &default_grants(),
        TOOL_SAVE_QUERY,
        json!({
            "application": "blog",
            "name": "topAuthors",
            "code": "select author, count(*) as books, max(year) as latest from \
                    books where year > :since group by author",
        }),
    )
    .await?;
    assert_eq!(result["created"], json!(false));
    assert_eq!(result["query"]["path"], json!("/reports/top-authors"));
    assert_eq!(
        result["query"]["description"],
        json!("Books per author since a year")
    );
    assert_eq!(result["query"]["params"][0]["name"], json!("since"));
    let returns = result["query"]["returns"].as_array().unwrap();
    assert_eq!(returns.len(), 3, "{result}");
    assert_eq!(returns[2]["name"], json!("latest"));

    // An agent allowed to add queries cannot rewrite one an admin wrote by
    // reusing its name, and the refusal names the checkbox that would allow it.
    let create_only = config(&[("allow_edit", json!(false))]);
    let err = call(
        &env,
        &create_only,
        TOOL_SAVE_QUERY,
        json!({ "application": "blog", "name": "topAuthors", "code": "select 1 as n" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("allow_edit"), "{err}");
    assert!(err.contains("nothing was changed"), "{err}");

    // …and the mirror image: an agent allowed only to edit cannot add one.
    let edit_only = config(&[("allow_create", json!(false))]);
    let mut fresh = top_authors();
    fresh["name"] = json!("newest");
    fresh["path"] = json!("/reports/newest");
    fresh["code"] = json!("select title from books where year > :since");
    let err = call(&env, &edit_only, TOOL_SAVE_QUERY, fresh)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("allow_create"), "{err}");
    Ok(())
}

#[tokio::test]
async fn who_may_call_a_query_is_the_access_grant_and_admin_only_without_it() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;

    let mut public = top_authors();
    public["min_role"] = json!(100);
    let err = call(&env, &default_grants(), TOOL_SAVE_QUERY, public.clone())
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("allow_access_changes"), "{err}");
    // Refused before anything was written, which is the difference between a
    // grant and a warning.
    assert!(stored(&env).await?.is_empty());

    let result = call(&env, &all_grants(), TOOL_SAVE_QUERY, public).await?;
    assert_eq!(result["query"]["min_role"], json!(100));
    assert_eq!(stored(&env).await?[0].min_role, 100);

    // …and an edit that does not name it leaves it where it was, rather than
    // resetting a widened floor to admin behind the admin's back.
    call(
        &env,
        &all_grants(),
        TOOL_SAVE_QUERY,
        json!({
            "application": "blog",
            "name": "topAuthors",
            "description": "Books per author",
        }),
    )
    .await?;
    assert_eq!(stored(&env).await?[0].min_role, 100);
    Ok(())
}

#[tokio::test]
async fn deleting_a_query_needs_the_drop_grant_and_says_what_it_was() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    let dir = app_with_api(&env).await?;
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;

    let err = call(
        &env,
        &default_grants(),
        TOOL_DELETE_QUERY,
        json!({ "application": "blog", "name": "topAuthors" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("allow_drop"), "{err}");
    assert_eq!(stored(&env).await?.len(), 1);

    let result = call(
        &env,
        &all_grants(),
        TOOL_DELETE_QUERY,
        json!({ "application": "blog", "name": "topAuthors" }),
    )
    .await?;
    assert_eq!(result["deleted"], json!("topAuthors"));
    // What it was, so an agent that deleted the wrong endpoint can put it back
    // from its own transcript.
    assert!(
        result["was"]["code"]
            .as_str()
            .unwrap()
            .contains("count(*) as books"),
        "{result}"
    );
    assert!(stored(&env).await?.is_empty());
    // The client loses the method with it.
    let client = env.slurp(&dir, "web/src/api.ts")?;
    assert!(!client.contains("topAuthors"), "{client}");

    // …and deleting one that is not there names the ones that are.
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;
    let err = call(
        &env,
        &all_grants(),
        TOOL_DELETE_QUERY,
        json!({ "application": "blog", "name": "topAuthor" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("topAuthors"), "{err}");
    Ok(())
}

#[tokio::test]
async fn describing_the_applications_reports_the_apis_and_their_queries() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;

    let result = call(&env, &default_grants(), TOOL_DESCRIBE_APPS, json!({})).await?;
    let apps = result["applications"].as_array().unwrap();
    assert_eq!(apps.len(), 1, "{result}");
    assert_eq!(apps[0]["subdomain"], json!("blog"));
    assert_eq!(apps[0]["tables"], json!(["books"]));
    let api = &apps[0]["apis"][0];
    assert_eq!(api["mount"], json!("/api"));
    assert_eq!(api["serves_custom_queries"], json!(true));
    assert_eq!(api["queries"][0]["name"], json!("topAuthors"));
    assert_eq!(api["queries"][0]["params"][0]["type"], json!("int"));
    assert_eq!(api["queries"][0]["returns"][0]["name"], json!("author"));

    // An application nobody serves names the ones somebody does.
    let err = call(
        &env,
        &default_grants(),
        TOOL_DESCRIBE_APPS,
        json!({ "application": "shop" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("blog"), "{err}");
    Ok(())
}

#[tokio::test]
async fn the_areas_decide_which_tools_the_model_is_offered() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;

    let offered = |cfg: &Attrs| -> Vec<String> {
        env.tools(TRAIT, cfg)
            .into_iter()
            .map(|t| t.name)
            .collect::<Vec<_>>()
    };
    // Both areas are on unless the admin says otherwise, so the whole trait is
    // there by default.
    let all = offered(&default_grants());
    assert!(all.contains(&TOOL_DESCRIBE_APPS.to_owned()), "{all:?}");
    assert!(all.contains(&TOOL_DESCRIBE_TRIGGERS.to_owned()), "{all:?}");
    assert_eq!(all.len(), 17, "{all:?}");

    // Switched off, the tools are *gone* rather than present and refusing: a tool
    // the model can see is a tool it will try. The code-body reference stays, as
    // the schema tools do: it belongs to no area and grants nothing.
    let schema_only = config(&[
        (CFG_ALLOW_TRIGGERS, json!(false)),
        (CFG_ALLOW_APPLICATIONS, json!(false)),
    ]);
    assert_eq!(
        offered(&schema_only),
        vec!["describe_schema", "edit_schema", "describe_code_api"]
    );
    env.check(TRAIT, &schema_only).await?;

    // …and a name that arrives anyway is refused, naming the checkbox.
    let err = call(&env, &schema_only, TOOL_DESCRIBE_APPS, json!({}))
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains(CFG_ALLOW_APPLICATIONS), "{err}");
    let err = call(&env, &schema_only, TOOL_DESCRIBE_TRIGGERS, json!({}))
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains(CFG_ALLOW_TRIGGERS), "{err}");

    // Each area is independent of the other.
    let no_apps = config(&[(CFG_ALLOW_APPLICATIONS, json!(false))]);
    let names = offered(&no_apps);
    assert!(
        names.contains(&TOOL_DESCRIBE_TRIGGERS.to_owned()),
        "{names:?}"
    );
    assert!(!names.contains(&TOOL_SAVE_QUERY.to_owned()), "{names:?}");
    // The trait's own two are application work too, and go with the area.
    for own in [
        "delegate_to_coding_agent",
        "publish_application",
        "create_application",
    ] {
        assert!(all.contains(&own.to_owned()), "{all:?}");
        assert!(!names.contains(&own.to_owned()), "{names:?}");
    }
    Ok(())
}

#[tokio::test]
async fn naming_an_api_that_cannot_hold_a_query_is_refused_where_the_mistake_was_made() -> Result<()>
{
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;
    // Give the app a second API that does not serve custom SQL queries.
    let mut app = load_application_by_subdomain(&env.catalog, "blog")
        .await?
        .expect("the application is stored");
    app.apis.push(ApiConfig::new("graphql", "/graphql"));
    save_application(&env.catalog, &app).await?;

    let mut wrong = top_authors();
    wrong["api"] = json!("/graphql");
    let err = call(&env, &default_grants(), TOOL_SAVE_QUERY, wrong)
        .await
        .unwrap_err()
        .to_string();
    // The mistake, not its consequence two steps later: an "unknown setting
    // `queries`" out of the provider's spec would be a true message about the
    // wrong thing.
    assert!(err.contains("does not serve custom SQL"), "{err}");
    assert!(err.contains("/api"), "{err}");
    assert!(stored(&env).await?.is_empty());

    // …and the REST one is still found with nothing named, because it is still
    // the only candidate.
    call(&env, &default_grants(), TOOL_SAVE_QUERY, top_authors()).await?;
    assert_eq!(stored(&env).await?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn a_non_admin_caller_is_refused_by_every_application_tool() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;

    for (tool, args) in [
        (TOOL_DESCRIBE_APPS, json!({})),
        (TOOL_SAVE_QUERY, top_authors()),
        (
            TOOL_DELETE_QUERY,
            json!({ "application": "blog", "name": "topAuthors" }),
        ),
    ] {
        let err = env
            .call_tool(
                TRAIT,
                &all_grants(),
                tool,
                args,
                &as_user("reader@example.com"),
            )
            .await
            .unwrap_err()
            .to_string();
        assert!(err.contains("administrator"), "{tool}: {err}");
    }
    // Nothing was written on the way to any of those refusals.
    assert!(stored(&env).await?.is_empty());
    Ok(())
}

/// `update_application` checks a grant per section before it changes anything.
/// The CSP is a security boundary, so its section needs the access-rules grant,
/// and a call that names it without that grant is refused **whole** — the
/// tables named beside it are not touched either. A static directory is not a
/// grant, so the default configuration may add one; with no server to refresh
/// the mount, the record is saved and the answer says the change is served from
/// the next start rather than now.
#[tokio::test]
async fn update_application_checks_each_section_s_grant_before_changing_anything() -> Result<()> {
    let env = Env::with_schema(SCHEMA).await?;
    app_with_api(&env).await?;
    env.with_file_store("media", None).await?;
    let before = load_application_by_subdomain(&env.catalog, "blog")
        .await?
        .unwrap();

    let both = json!({
        "application": "blog",
        "tables": { "remove": ["books"] },
        "csp": { "frame-ancestors": ["https://admin.example.com"] },
    });
    let refused = call(&env, &default_grants(), "update_application", both.clone())
        .await
        .unwrap_err()
        .to_string();
    assert!(refused.contains("allow_access_changes"), "{refused}");
    let unchanged = load_application_by_subdomain(&env.catalog, "blog")
        .await?
        .unwrap();
    assert_eq!(unchanged.csp, before.csp);
    assert_eq!(unchanged.tables, before.tables);

    let changed = call(&env, &all_grants(), "update_application", both).await?;
    assert_eq!(
        changed["csp"]["frame-ancestors"],
        json!(["https://admin.example.com"]),
        "{changed}"
    );
    assert_eq!(changed["tables"], json!([]), "{changed}");
    assert_eq!(changed["was"]["tables"], json!(["books"]), "{changed}");

    // Under the API's mount: refused by the same validation the admin's form
    // runs, and nothing stored.
    let under_api = call(
        &env,
        &default_grants(),
        "update_application",
        json!({ "application": "blog", "static_dirs": {
                "add": [{ "mount": "/api/img", "file_store": "media" }] } }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(under_api.contains("under the `rest` API"), "{under_api}");

    let served = call(
        &env,
        &default_grants(),
        "update_application",
        json!({
            "application": "blog",
            "tables": { "add": ["books"] },
            "static_dirs": {
                "add": [{ "mount": "/img", "file_store": "media", "path": "covers" }],
            },
        }),
    )
    .await?;
    assert_eq!(
        served["connected_file_stores"],
        json!(["media"]),
        "{served}"
    );
    assert_eq!(served["tables"], json!(["books"]), "{served}");
    assert!(served.get("csp").is_none(), "{served}");
    assert!(
        served["notes"][0].as_str().unwrap().contains("next start"),
        "{served}"
    );
    let stored = load_application_by_subdomain(&env.catalog, "blog")
        .await?
        .unwrap();
    assert_eq!(stored.static_dirs.len(), 1);
    assert_eq!(stored.static_dirs[0].mount, "/img");
    assert_eq!(stored.static_dirs[0].path, "covers");
    // The CSP set above is kept: a section not named is left as it was.
    assert_eq!(
        stored.csp.directives["frame-ancestors"],
        vec!["https://admin.example.com".to_owned()]
    );

    let unknown = call(
        &env,
        &default_grants(),
        "update_application",
        json!({ "application": "blog", "static_dirs": { "remove": ["/nope"] } }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(unknown.contains("serves `/img`"), "{unknown}");

    let nothing = call(
        &env,
        &default_grants(),
        "update_application",
        json!({ "application": "blog" }),
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(nothing.contains("at least one of"), "{nothing}");
    Ok(())
}
