// Code generated by sc-api. DO NOT EDIT.
// Regenerate with the sc-api TypeScript generator (design §13.1).
//
// The half of a generated client that is the same in every application. `client.ts`
// beside it is the half that is this one's: its endpoints, its tables and their
// rows.

/** How a client reaches its server. */
export interface ClientOptions {
  /** Prepended to every request path. */
  baseUrl?: string;
  /** Fetch implementation to use (defaults to global `fetch`). */
  fetch?: typeof fetch;
  /** How the live connection behaves, for an application that exposes streams. */
  live?: LiveOptions;
}

/** A failed request, as the error a caller sees: status, and what the server said. */
export async function clientError(op: string, res: Response): Promise<Error> {
  let detail = "";
  try {
    const body: unknown = await res.json();
    if (body && typeof body === "object" && "error" in body && typeof (body as { error: unknown }).error === "string") {
      detail = `: ${(body as { error: string }).error}`;
    }
  } catch {
    // Non-JSON body: the status alone will have to describe the failure.
  }
  return new Error(`${op} failed: ${res.status}${detail}`);
}

/** The CSRF token the server last named in a response, for a client that
 * cannot read the cookie. */
let rememberedCsrf: string | undefined;

function csrfToken(): string | undefined {
  if (typeof document !== "undefined") {
    for (const part of document.cookie.split(";")) {
      const [name, ...rest] = part.trim().split("=");
      if (name === "sc_csrf") return decodeURIComponent(rest.join("="));
    }
  }
  return rememberedCsrf;
}

/** `fetchImpl`, remembering the CSRF token each response names — how a client
 * with no `document.cookie` learns what its next write must echo.
 *
 * A write refused `403` with a token it did not send is sent **once more** with
 * that token: a native app reopened while still signed in has its session but
 * not the token it remembered, and its first write is how it finds out. */
export function trackCsrf(fetchImpl: typeof fetch): typeof fetch {
  return (async (input: Parameters<typeof fetch>[0], init?: Parameters<typeof fetch>[1]) => {
    const res = await fetchImpl(input, init);
    const token = res.headers.get("x-csrf-token");
    if (token) rememberedCsrf = token;
    const sent = new Headers(init?.headers).get("x-csrf-token");
    if (res.status === 403 && token && token !== sent) {
      const headers = new Headers(init?.headers);
      headers.set("x-csrf-token", token);
      return fetchImpl(input, { ...init, headers });
    }
    return res;
  }) as typeof fetch;
}

/** The headers a request carries: its content type, its CSRF token, and — where
 * there is no `document`, i.e. a native app — that it is not a browser, so the
 * server lets its login outlive the app being closed. */
export function requestHeaders(method: string, hasBody: boolean): Record<string, string> {
  const headers: Record<string, string> = {};
  if (hasBody) headers["content-type"] = "application/json";
  if (typeof document === "undefined") headers["x-feldspar-client"] = "native";
  if (method !== "GET" && method !== "HEAD") {
    const token = csrfToken();
    if (token) headers["x-csrf-token"] = token;
  }
  return headers;
}

// --- reading a table --------------------------------------------------------

/** What a delete answers with. */
export type Deleted = { deleted: true };

/** A comparison a filter may name. */
export type FilterOp =
  | "eq"
  | "ne"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "nin"
  | "like"
  | "ilike"
  | "is_null";

/** One column's filter: a comparison and its operand, e.g. `gte.2020-01-01`. */
export type FilterValue = `${FilterOp}.${string}`;

/** The filters a read may carry — one per column of the table being read. */
export type Filters<Row> = Partial<Record<Extract<keyof Row, string>, FilterValue>>;

/** One `order` key: a column, ascending unless it says otherwise. */
export type OrderKey<Row> =
  | Extract<keyof Row, string>
  | `${Extract<keyof Row, string>}.asc`
  | `${Extract<keyof Row, string>}.desc`;

/** `order`: one key, or a precedence list of them. */
export type Order<Row> = OrderKey<Row> | `${OrderKey<Row>},${string}`;

/** Flatten an intersection, so a hover shows the object rather than the pieces. */
type Flatten<T> = { [K in keyof T]: T[K] } & {};

/**
 * A write body over a table's row: `Required` must be given, everything else may
 * be, and `ReadOnly` cannot be given at all.
 *
 * A row and an insert hold the same columns with the same types and differ only
 * in which of them the *caller* has to supply — so a generated client says that
 * difference as two lists of column names rather than as a second copy of the
 * table, which could describe a different one.
 */
export type Insertable<
  Row,
  Required extends keyof Row,
  ReadOnly extends keyof Row = never,
> = Flatten<Pick<Row, Required> & Partial<Omit<Row, Required | ReadOnly>>>;

/** The bytes behind a file column. */
export interface FileApi<Id> {
  /** Read them. */
  download(id: Id): Promise<Blob>;
  /** Replace them with `body`, stored under `filename`. */
  upload(id: Id, filename: string, body: BodyInit): Promise<unknown>;
}

// --- the type of a `select` -------------------------------------------------
//
// A `select` changes the shape of what comes back, so what a read *returns* is a
// function of the string the caller wrote: `list({ select: "title,author(name)" })`
// answers `{ title, author: { name } }` and nothing else. The types below are
// that function, evaluated by the compiler — which is why there is one `list`
// rather than one for rows and another for embeds.
//
// A select assembled at runtime (typed `string`, not a literal) cannot be read
// this way. It degrades to the whole row plus unknown extras rather than
// failing: the compiler then knows exactly what the caller does.

/** A table's row type, and the tables its keys point at. */
export type TableSchema = { row: object; rels: { [field: string]: TableSchema } };

type Trim<S extends string> = S extends ` ${infer R}`
  ? Trim<R>
  : S extends `${infer R} `
    ? Trim<R>
    : S;

/** Split a select list on its top-level commas — the ones outside any `(…)`. */
type SplitItems<
  S extends string,
  Depth extends 0[] = [],
  Item extends string = "",
  Out extends string[] = [],
> = S extends `${infer C}${infer Rest}`
  ? C extends "("
    ? SplitItems<Rest, [...Depth, 0], `${Item}${C}`, Out>
    : C extends ")"
      ? SplitItems<
          Rest,
          Depth extends [0, ...infer Less extends 0[]] ? Less : [],
          `${Item}${C}`,
          Out
        >
      : C extends ","
        ? Depth["length"] extends 0
          ? SplitItems<Rest, Depth, "", [...Out, Item]>
          : SplitItems<Rest, Depth, `${Item}${C}`, Out>
        : SplitItems<Rest, Depth, `${Item}${C}`, Out>
  : [...Out, Item];

/** The type of one column — `unknown` for a name the table does not have. */
type ColumnOf<S extends TableSchema, Name extends string> = Name extends keyof S["row"]
  ? S["row"][Name]
  : unknown;

/**
 * The type of one embed: what was selected on the far side, and `null` when the
 * key itself is nullable — a null key answers `null` rather than an object of
 * nulls.
 */
type EmbedOf<S extends TableSchema, Name extends string, Inner extends string> = Name extends
  keyof S["rels"]
  ? Name extends keyof S["row"]
    ? null extends S["row"][Name]
      ? Selected<S["rels"][Name], Inner> | null
      : Selected<S["rels"][Name], Inner>
    : Selected<S["rels"][Name], Inner>
  : unknown;

/** One select item: `column`, `alias:column`, `key(…)` or `alias:key(…)`. */
type ItemOf<S extends TableSchema, Item extends string> = Trim<Item> extends
  `${infer Alias}:${infer Target}`
  ? { [K in Trim<Alias>]: TargetOf<S, Trim<Target>> }
  : Trim<Item> extends `${infer Name}(${infer Inner})`
    ? { [K in Trim<Name>]: EmbedOf<S, Trim<Name>, Inner> }
    : { [K in Trim<Item>]: ColumnOf<S, Trim<Item>> };

/** What an item points at, once any alias has been taken off the front. */
type TargetOf<S extends TableSchema, Target extends string> = Target extends
  `${infer Name}(${infer Inner})`
  ? EmbedOf<S, Trim<Name>, Inner>
  : ColumnOf<S, Target>;

type ItemsOf<S extends TableSchema, Items extends string[]> = {
  [I in keyof Items]: ItemOf<S, Items[I] & string>;
}[number];

type UnionToIntersection<U> = (U extends unknown ? (x: U) => void : never) extends
  (x: infer I) => void
  ? I
  : never;

/** What a read with the select `Sel` answers with. */
export type Selected<S extends TableSchema, Sel extends string> = string extends Sel
  ? S["row"] & Record<string, unknown>
  : Trim<Sel> extends ""
    ? S["row"]
    : Flatten<UnionToIntersection<ItemsOf<S, SplitItems<Sel>>>>;

// --- live updates -----------------------------------------------------------

/** Where a live connection is: connecting for the first time, open, or reconnecting after a loss. */
export type LiveStatus = "connecting" | "open" | "reconnecting";

/** What the server says when a subscription starts (and again if its stream restarts). */
export interface LiveReady {
  stream: string;
  /** How many of the elements that follow are history, not new arrivals. */
  replayed: number;
  /** What an element's `value` is, or `null` while the stream is not running on the server. */
  element_type: unknown;
  /** Whether this subscriber may publish on the stream. */
  can_publish: boolean;
  status: unknown;
  counters: unknown;
}

/** Why the server refused, ended or complained about a subscription. */
export interface LiveError {
  /** `unavailable`, `revoked`, `invalid`, `too_many_subscriptions`, `signed_out`, … */
  code: string;
  message: string;
}

/** What a subscriber is told. Only `element` is required. */
export interface LiveHandlers<E> {
  ready?(info: LiveReady): void;
  element(envelope: E): void;
  /** This subscription fell behind and lost `dropped` elements (it is never a silent gap). */
  lagged?(dropped: number): void;
  /** The connection was lost and re-established: anything built from earlier elements may be stale. */
  resync?(): void;
  status?(status: unknown): void;
  /** A refusal. Before `ready`, or as `revoked`, it ends the subscription, which is not retried. */
  error?(error: LiveError): void;
}

/** A live subscription. `close()` ends it. */
export interface LiveSubscription {
  close(): void;
}

/** One stream an application exposes, ready to subscribe to. */
export interface LiveStream<E> {
  readonly name: string;
  /** The connection it is subscribed over, for its `status`. */
  readonly connection: LiveConnection;
  subscribe(handlers: LiveHandlers<E>): LiveSubscription;
}

/** How a live connection behaves. */
export interface LiveOptions {
  /** The `WebSocket` constructor to use (defaults to the global one). */
  WebSocket?: typeof WebSocket;
  /** The first reconnect delay, in milliseconds. */
  minDelay?: number;
  /** The longest reconnect delay, in milliseconds. */
  maxDelay?: number;
}

/** The live socket's URL: `path` on the client's base URL, as `ws:` or `wss:`. */
export function liveUrl(baseUrl: string, path: string): string {
  const origin = baseUrl || (typeof location === "undefined" ? "http://localhost" : location.origin);
  const url = new URL(path, origin);
  url.protocol = url.protocol === "https:" ? "wss:" : "ws:";
  return url.toString();
}

type LiveEntry = { stream: string; handlers: LiveHandlers<unknown>; ready: boolean };

/** One socket, any number of subscriptions, reconnecting by itself. */
export class LiveConnection {
  private socket: WebSocket | undefined;
  private readonly entries = new Map<string, LiveEntry>();
  private readonly listeners = new Set<(status: LiveStatus) => void>();
  private nextSub = 1;
  private attempt = 0;
  private opened = false;
  private timer: ReturnType<typeof setTimeout> | undefined;
  private current: LiveStatus = "connecting";
  // Fields assigned in the body rather than as parameter properties: Node runs
  // this file by stripping its types, and a parameter property is not erasable.
  private readonly url: string;
  private readonly options: LiveOptions;

  constructor(url: string, options: LiveOptions = {}) {
    this.url = url;
    this.options = options;
  }

  /** Where the connection is now. */
  get status(): LiveStatus {
    return this.current;
  }

  /** Be told when the status changes. Returns the function that stops it. */
  onStatus(listener: (status: LiveStatus) => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  /** The accessor for the stream called `name`. */
  stream<E>(name: string): LiveStream<E> {
    return {
      name,
      connection: this,
      subscribe: (handlers: LiveHandlers<E>) => this.subscribe(name, handlers),
    };
  }

  /** Subscribe to `stream`, opening the socket if this is the first subscription. */
  subscribe<E>(stream: string, handlers: LiveHandlers<E>): LiveSubscription {
    const sub = `s${this.nextSub++}`;
    this.entries.set(sub, { stream, handlers: handlers as LiveHandlers<unknown>, ready: false });
    if (this.socket && this.socket.readyState === 1) {
      this.send({ type: "subscribe", sub, stream });
    } else {
      this.open();
    }
    let active = true;
    return {
      close: () => {
        if (!active) return;
        active = false;
        if (this.entries.delete(sub) && this.socket && this.socket.readyState === 1) {
          this.send({ type: "unsubscribe", sub });
        }
        if (this.entries.size === 0) this.shutdown();
      },
    };
  }

  /** End every subscription and close the socket. */
  close(): void {
    this.entries.clear();
    this.shutdown();
  }

  private setStatus(status: LiveStatus): void {
    if (status === this.current) return;
    this.current = status;
    this.listeners.forEach((listener) => listener(status));
  }

  private send(frame: Record<string, unknown>): void {
    this.socket?.send(JSON.stringify(frame));
  }

  private open(): void {
    if (this.socket || this.timer !== undefined) return;
    const Socket = this.options.WebSocket ?? (typeof WebSocket === "undefined" ? undefined : WebSocket);
    if (!Socket) throw new Error("live updates need a WebSocket implementation (LiveOptions.WebSocket)");
    const socket = new Socket(this.url);
    this.socket = socket;
    socket.onopen = () => {
      const reconnect = this.opened;
      this.opened = true;
      this.attempt = 0;
      this.setStatus("open");
      this.entries.forEach((entry, sub) => {
        entry.ready = false;
        this.send({ type: "subscribe", sub, stream: entry.stream });
        if (reconnect) entry.handlers.resync?.();
      });
    };
    socket.onmessage = (event: MessageEvent) => this.receive(event.data);
    socket.onclose = () => {
      if (this.socket !== socket) return;
      this.socket = undefined;
      if (this.entries.size === 0) return;
      this.setStatus("reconnecting");
      const min = this.options.minDelay ?? 500;
      const max = this.options.maxDelay ?? 30000;
      const delay = Math.min(max, min * 2 ** this.attempt);
      this.attempt += 1;
      // Half the delay, plus up to half again at random: a server that restarts
      // is not met by every page reconnecting in the same millisecond.
      this.timer = setTimeout(() => {
        this.timer = undefined;
        this.open();
      }, delay / 2 + Math.random() * (delay / 2));
    };
  }

  private shutdown(): void {
    if (this.timer !== undefined) {
      clearTimeout(this.timer);
      this.timer = undefined;
    }
    const socket = this.socket;
    this.socket = undefined;
    this.opened = false;
    this.attempt = 0;
    socket?.close();
    this.setStatus("connecting");
  }

  private receive(data: unknown): void {
    let frame: Record<string, unknown>;
    try {
      const parsed: unknown = JSON.parse(String(data));
      if (!parsed || typeof parsed !== "object") return;
      frame = parsed as Record<string, unknown>;
    } catch {
      return;
    }
    const sub = typeof frame["sub"] === "string" ? frame["sub"] : undefined;
    const entry = sub === undefined ? undefined : this.entries.get(sub);
    switch (frame["type"]) {
      case "ready":
        if (entry) {
          entry.ready = true;
          entry.handlers.ready?.(frame as unknown as LiveReady);
        }
        break;
      case "element":
        entry?.handlers.element(frame["envelope"]);
        break;
      case "lagged":
        entry?.handlers.lagged?.(Number(frame["dropped"] ?? 0));
        break;
      case "status":
        entry?.handlers.status?.(frame["status"]);
        break;
      case "revoked":
        if (entry && sub !== undefined) {
          this.entries.delete(sub);
          entry.handlers.error?.({ code: "revoked", message: "access to this stream ended" });
        }
        break;
      case "error": {
        const error: LiveError = {
          code: String(frame["code"] ?? "error"),
          message: String(frame["message"] ?? ""),
        };
        if (sub === undefined) {
          // About the connection, not one subscription: everyone hears it, and
          // the reconnect that follows a close asks again.
          this.entries.forEach((each) => each.handlers.error?.(error));
        } else if (entry) {
          // Refused before `ready`: the subscription never started, so it ends.
          if (!entry.ready) this.entries.delete(sub);
          entry.handlers.error?.(error);
        }
        break;
      }
      default:
        // A frame this client was generated before: ignored, never thrown on.
        break;
    }
  }
}

