// Code generated by sc-api. DO NOT EDIT.
// Regenerate with the sc-api TypeScript generator (design §13.1).
//
// The half of a generated client that is the same in every application. `client.ts`
// beside it is the half that is this one's: its endpoints, its tables and their
// rows.

/** How a client reaches its server. */
export interface ClientOptions {
  /** Prepended to every request path. */
  baseUrl?: string;
  /** Fetch implementation to use (defaults to global `fetch`). */
  fetch?: typeof fetch;
}

/** A failed request, as the error a caller sees: status, and what the server said. */
export async function clientError(op: string, res: Response): Promise<Error> {
  let detail = "";
  try {
    const body: unknown = await res.json();
    if (body && typeof body === "object" && "error" in body && typeof (body as { error: unknown }).error === "string") {
      detail = `: ${(body as { error: string }).error}`;
    }
  } catch {
    // Non-JSON body: the status alone will have to describe the failure.
  }
  return new Error(`${op} failed: ${res.status}${detail}`);
}

function csrfToken(): string | undefined {
  if (typeof document === "undefined") return undefined;
  for (const part of document.cookie.split(";")) {
    const [name, ...rest] = part.trim().split("=");
    if (name === "sc_csrf") return decodeURIComponent(rest.join("="));
  }
  return undefined;
}

/** The headers a request carries: its content type, and its CSRF token. */
export function requestHeaders(method: string, hasBody: boolean): Record<string, string> {
  const headers: Record<string, string> = {};
  if (hasBody) headers["content-type"] = "application/json";
  if (method !== "GET" && method !== "HEAD") {
    const token = csrfToken();
    if (token) headers["x-csrf-token"] = token;
  }
  return headers;
}

// --- reading a table --------------------------------------------------------

/** What a delete answers with. */
export type Deleted = { deleted: true };

/** A comparison a filter may name. */
export type FilterOp =
  | "eq"
  | "ne"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "nin"
  | "like"
  | "ilike"
  | "is_null";

/** One column's filter: a comparison and its operand, e.g. `gte.2020-01-01`. */
export type FilterValue = `${FilterOp}.${string}`;

/** The filters a read may carry — one per column of the table being read. */
export type Filters<Row> = Partial<Record<Extract<keyof Row, string>, FilterValue>>;

/** One `order` key: a column, ascending unless it says otherwise. */
export type OrderKey<Row> =
  | Extract<keyof Row, string>
  | `${Extract<keyof Row, string>}.asc`
  | `${Extract<keyof Row, string>}.desc`;

/** `order`: one key, or a precedence list of them. */
export type Order<Row> = OrderKey<Row> | `${OrderKey<Row>},${string}`;

/** Flatten an intersection, so a hover shows the object rather than the pieces. */
type Flatten<T> = { [K in keyof T]: T[K] } & {};

/**
 * A write body over a table's row: `Required` must be given, everything else may
 * be, and `ReadOnly` cannot be given at all.
 *
 * A row and an insert hold the same columns with the same types and differ only
 * in which of them the *caller* has to supply — so a generated client says that
 * difference as two lists of column names rather than as a second copy of the
 * table, which could describe a different one.
 */
export type Insertable<
  Row,
  Required extends keyof Row,
  ReadOnly extends keyof Row = never,
> = Flatten<Pick<Row, Required> & Partial<Omit<Row, Required | ReadOnly>>>;

/** The bytes behind a file column. */
export interface FileApi<Id> {
  /** Read them. */
  download(id: Id): Promise<Blob>;
  /** Replace them with `body`, stored under `filename`. */
  upload(id: Id, filename: string, body: BodyInit): Promise<unknown>;
}

// --- the type of a `select` -------------------------------------------------
//
// A `select` changes the shape of what comes back, so what a read *returns* is a
// function of the string the caller wrote: `list({ select: "title,author(name)" })`
// answers `{ title, author: { name } }` and nothing else. The types below are
// that function, evaluated by the compiler — which is why there is one `list`
// rather than one for rows and another for embeds.
//
// A select assembled at runtime (typed `string`, not a literal) cannot be read
// this way. It degrades to the whole row plus unknown extras rather than
// failing: the compiler then knows exactly what the caller does.

/** A table's row type, and the tables its keys point at. */
export type TableSchema = { row: object; rels: { [field: string]: TableSchema } };

type Trim<S extends string> = S extends ` ${infer R}`
  ? Trim<R>
  : S extends `${infer R} `
    ? Trim<R>
    : S;

/** Split a select list on its top-level commas — the ones outside any `(…)`. */
type SplitItems<
  S extends string,
  Depth extends 0[] = [],
  Item extends string = "",
  Out extends string[] = [],
> = S extends `${infer C}${infer Rest}`
  ? C extends "("
    ? SplitItems<Rest, [...Depth, 0], `${Item}${C}`, Out>
    : C extends ")"
      ? SplitItems<
          Rest,
          Depth extends [0, ...infer Less extends 0[]] ? Less : [],
          `${Item}${C}`,
          Out
        >
      : C extends ","
        ? Depth["length"] extends 0
          ? SplitItems<Rest, Depth, "", [...Out, Item]>
          : SplitItems<Rest, Depth, `${Item}${C}`, Out>
        : SplitItems<Rest, Depth, `${Item}${C}`, Out>
  : [...Out, Item];

/** The type of one column — `unknown` for a name the table does not have. */
type ColumnOf<S extends TableSchema, Name extends string> = Name extends keyof S["row"]
  ? S["row"][Name]
  : unknown;

/**
 * The type of one embed: what was selected on the far side, and `null` when the
 * key itself is nullable — a null key answers `null` rather than an object of
 * nulls.
 */
type EmbedOf<S extends TableSchema, Name extends string, Inner extends string> = Name extends
  keyof S["rels"]
  ? Name extends keyof S["row"]
    ? null extends S["row"][Name]
      ? Selected<S["rels"][Name], Inner> | null
      : Selected<S["rels"][Name], Inner>
    : Selected<S["rels"][Name], Inner>
  : unknown;

/** One select item: `column`, `alias:column`, `key(…)` or `alias:key(…)`. */
type ItemOf<S extends TableSchema, Item extends string> = Trim<Item> extends
  `${infer Alias}:${infer Target}`
  ? { [K in Trim<Alias>]: TargetOf<S, Trim<Target>> }
  : Trim<Item> extends `${infer Name}(${infer Inner})`
    ? { [K in Trim<Name>]: EmbedOf<S, Trim<Name>, Inner> }
    : { [K in Trim<Item>]: ColumnOf<S, Trim<Item>> };

/** What an item points at, once any alias has been taken off the front. */
type TargetOf<S extends TableSchema, Target extends string> = Target extends
  `${infer Name}(${infer Inner})`
  ? EmbedOf<S, Trim<Name>, Inner>
  : ColumnOf<S, Target>;

type ItemsOf<S extends TableSchema, Items extends string[]> = {
  [I in keyof Items]: ItemOf<S, Items[I] & string>;
}[number];

type UnionToIntersection<U> = (U extends unknown ? (x: U) => void : never) extends
  (x: infer I) => void
  ? I
  : never;

/** What a read with the select `Sel` answers with. */
export type Selected<S extends TableSchema, Sel extends string> = string extends Sel
  ? S["row"] & Record<string, unknown>
  : Trim<Sel> extends ""
    ? S["row"]
    : Flatten<UnionToIntersection<ItemsOf<S, SplitItems<Sel>>>>;

// --- observing a stream -----------------------------------------------------

/** A live subscription to a stream's elements. `close()` stops it. */
export interface StreamSubscription {
  close(): void;
}

/** What the server says when the socket opens: the replay that follows, and the flow's state. */
export interface StreamReady {
  stream: string;
  /** How many of the elements that follow are history, not new arrivals. */
  replayed: number;
  status: unknown;
  counters: unknown;
}

/** What an observer is told. Only `element` is required. */
export interface StreamHandlers<E> {
  ready?(info: StreamReady): void;
  element(envelope: E): void;
  /** This client fell behind and lost `dropped` elements (it is never a silent gap). */
  lagged?(dropped: number): void;
  status?(status: unknown): void;
  error?(error: unknown): void;
  closed?(): void;
}

/** Open an observe socket on `path`, relative to the client's base URL. */
export function openStream<E>(
  baseUrl: string,
  path: string,
  handlers: StreamHandlers<E>,
): StreamSubscription {
  const origin = baseUrl || (typeof location === "undefined" ? "http://localhost" : location.origin);
  const url = new URL(path, origin);
  url.protocol = url.protocol === "https:" ? "wss:" : "ws:";
  const socket = new WebSocket(url.toString());
  socket.onmessage = (event: MessageEvent) => {
    let frame: unknown;
    try {
      frame = JSON.parse(String(event.data));
    } catch {
      return;
    }
    if (!frame || typeof frame !== "object") return;
    const f = frame as Record<string, unknown>;
    switch (f["type"]) {
      case "ready":
        handlers.ready?.(f as unknown as StreamReady);
        break;
      case "element":
        handlers.element(f["envelope"] as E);
        break;
      case "lagged":
        handlers.lagged?.(Number(f["dropped"] ?? 0));
        break;
      case "status":
        handlers.status?.(f["status"]);
        break;
      default:
        // A frame this client was generated before: ignored, never thrown on.
        break;
    }
  };
  socket.onerror = (event: Event) => handlers.error?.(event);
  socket.onclose = () => handlers.closed?.();
  return {
    close() {
      socket.close();
    },
  };
}

